COPY /y /B 											"01 - Forecast_SABB_Rates.SQL"								BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"02 - SABB_Regression_Coefficient.SQL"									BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"03 - Intraweek_PCs_Dist.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"03 - Intraweek_PCs_Dist.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"04 - Intraweek_ABs_Dist.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"05 - Intraweek_BCRQ_Dist.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"06 - PC_Duration_Dist.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"07 - PC_Status_Movement_Probabilities.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"08 - AB_Status_Movement_Probabilities.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"09 - SABB_Offer_Applied_Duration_Dist.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"10 - SABB_Build_ForeCAST_New_Cust_Sample.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"11 - SABB_Forecast_Activation_Vols.SQL"								BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"12 - SABB_Forecast_Create_Opening_Base.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"13 - SABB_my_sky_login_prob.SQL"										BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"14 - SABB_BB_Calls_prob.SQL"											BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"15 - SABB_ForeCAST_Create_ForeCAST_Loop_Table_2.SQL"					BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"16 - Forecast_SABB_Loop_Table_2_Actions.SQL"							BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"17 - SABB_Forecast_Insert_New_Custs_Into_Loop_Table_2.SQL"			BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"18 - SABB_Forecast_Loop_Table_2_Update_For_Nxt_Wk.SQL"				BB_churn_ALL_MODULES.SQL
COPY /y /B 		BB_churn_ALL_MODULES.SQL+"19 - SABB_Forecast_Create_New_Forecast_Loop_Table.SQL"				BB_churn_ALL_MODULES.SQL
