
--select top 100 * from v223_unbundling_viewing_summary_by_account;

create variable @total_programmes_3min_plus_sky_sports_champions_league integer;
set @total_programmes_3min_plus_sky_sports_champions_league
=( select count(*) from v223_unbundling_viewing_summary_by_account where annualised_programmes_3min_plus_football_champions_league_sky_sports>0);

create variable @total_programmes_3min_plus_non_sky_sports_champions_league integer;
set @total_programmes_3min_plus_non_sky_sports_champions_league
=( select count(*) from v223_unbundling_viewing_summary_by_account where annualised_programmes_3min_plus_football_champions_league_non_sky_sports>0);

create variable @total_programmes_3min_plus_sky_sports_premier_league integer;
set @total_programmes_3min_plus_sky_sports_premier_league
=( select count(*) from v223_unbundling_viewing_summary_by_account where annualised_programmes_3min_plus_football_premier_league_sky_sports>0);

create variable @total_programmes_3min_plus_non_sky_sports_premier_league integer;
set @total_programmes_3min_plus_sky_sports_premier_league
=( select count(*) from v223_unbundling_viewing_summary_by_account where annualised_programmes_3min_plus_football_premier_league_ESPN_BT>0);


alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_engaged_football_champions_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_engaged_football_champions_league_non_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_engaged_football_premier_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_engaged_football_premier_league_non_sky_sports integer;

alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_engaged_football_champions_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_engaged_football_champions_league_non_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_engaged_football_premier_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_engaged_football_premier_league_non_sky_sports integer;


update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_engaged_football_champions_league_sky_sports = case when annualised_programmes_3min_plus_football_champions_league_sky_sports=0 then 999 
when abs(rank_prog_engaged_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/100))+1 >100 then 100 
else abs(rank_prog_engaged_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/100))+1 end
,phase_2_decile_engaged_football_champions_league_sky_sports = case when  annualised_programmes_3min_plus_football_champions_league_sky_sports=0 then 99 
when abs(rank_prog_engaged_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/10))+1 >10 then 10 
else 
abs(rank_prog_engaged_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/10))+1 end
;
commit;

update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_engaged_football_champions_league_non_sky_sports = case when annualised_programmes_3min_plus_football_champions_league_non_sky_sports=0 then 999 
when abs(rank_prog_engaged_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/100))+1 >100 then 100 
else abs(rank_prog_engaged_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/100))+1 end
,phase_2_decile_engaged_football_champions_league_non_sky_sports = case when  annualised_programmes_3min_plus_football_champions_league_non_sky_sports=0 then 99 
when abs(rank_prog_engaged_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/10))+1 >10 then 10 
else 
abs(rank_prog_engaged_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/10))+1 end
;
commit;




update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_engaged_football_premier_league_sky_sports = case when annualised_programmes_3min_plus_football_premier_league_sky_sports=0 then 999 
when abs(rank_prog_engaged_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/100))+1 >100 then 100 
else abs(rank_prog_engaged_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/100))+1 end
,phase_2_decile_engaged_football_premier_league_sky_sports = case when  annualised_programmes_3min_plus_football_premier_league_sky_sports=0 then 99 
when abs(rank_prog_engaged_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/10))+1 >10 then 10 
else 
abs(rank_prog_engaged_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/10))+1 end
;
commit;



update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_engaged_football_premier_league_non_sky_sports = case when annualised_programmes_3min_plus_football_premier_league_ESPN_BT=0 then 999 
when abs(rank_prog_engaged_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/100))+1 >100 then 100 
else abs(rank_prog_engaged_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/100))+1 end
,phase_2_decile_engaged_football_premier_league_non_sky_sports = case when  annualised_programmes_3min_plus_football_premier_league_ESPN_BT=0 then 99 
when abs(rank_prog_engaged_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/10))+1 >10 then 10 
else 
abs(rank_prog_engaged_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/10))+1 end
;
commit;



alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_3min_plus_football_champions_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_3min_plus_football_champions_league_non_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_3min_plus_football_premier_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_percentile_3min_plus_football_premier_league_non_sky_sports integer;

alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_3min_plus_football_champions_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_3min_plus_football_champions_league_non_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_3min_plus_football_premier_league_sky_sports integer;
alter table v223_unbundling_viewing_summary_by_account  add phase_2_decile_3min_plus_football_premier_league_non_sky_sports integer;

update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_3min_plus_football_champions_league_sky_sports = case when annualised_programmes_3min_plus_football_champions_league_sky_sports=0 then 999 
when abs(rank_prog_3min_plus_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/100))+1 >100 then 100 
else abs(rank_prog_3min_plus_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/100))+1 end
,phase_2_decile_3min_plus_football_champions_league_sky_sports = case when  annualised_programmes_3min_plus_football_champions_league_sky_sports=0 then 99 
when abs(rank_prog_3min_plus_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/10))+1 >10 then 10 
else 
abs(rank_prog_3min_plus_football_champions_league_sky_sports/(@total_programmes_3min_plus_sky_sports_champions_league/10))+1 end
;
commit;

update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_3min_plus_football_champions_league_non_sky_sports = case when annualised_programmes_3min_plus_football_champions_league_non_sky_sports=0 then 999 
when abs(rank_prog_3min_plus_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/100))+1 >100 then 100 
else abs(rank_prog_3min_plus_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/100))+1 end
,phase_2_decile_3min_plus_football_champions_league_non_sky_sports = case when  annualised_programmes_3min_plus_football_champions_league_non_sky_sports=0 then 99 
when abs(rank_prog_3min_plus_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/10))+1 >10 then 10 
else 
abs(rank_prog_3min_plus_football_champions_league_non_sky_sports/(@total_programmes_3min_plus_non_sky_sports_champions_league/10))+1 end
;
commit;




update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_3min_plus_football_premier_league_sky_sports = case when annualised_programmes_3min_plus_football_premier_league_sky_sports=0 then 999 
when abs(rank_prog_3min_plus_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/100))+1 >100 then 100 
else abs(rank_prog_3min_plus_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/100))+1 end
,phase_2_decile_3min_plus_football_premier_league_sky_sports = case when  annualised_programmes_3min_plus_football_premier_league_sky_sports=0 then 99 
when abs(rank_prog_3min_plus_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/10))+1 >10 then 10 
else 
abs(rank_prog_3min_plus_football_premier_league_sky_sports/(@total_programmes_3min_plus_sky_sports_premier_league/10))+1 end
;
commit;

/*
select sum(case when  annualised_programmes_3min_plus_football_premier_league_sky_sports>0 then 1 else 0 end), @total_programmes_3min_plus_sky_sports_premier_league
from v223_unbundling_viewing_summary_by_account

select annualised_programmes_3min_plus_football_premier_league_sky_sports ,rank_prog_3min_plus_football_premier_league_sky_sports
-- count(*) 
from v223_unbundling_viewing_summary_by_account group by annualised_programmes_3min_plus_football_premier_league_sky_sports order by annualised_programmes_3min_plus_football_premier_league_sky_sports
*/


update v223_unbundling_viewing_summary_by_account
set phase_2_percentile_3min_plus_football_premier_league_non_sky_sports = case when annualised_programmes_3min_plus_football_premier_league_ESPN_BT=0 then 999 
when abs(rank_prog_3min_plus_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/100))+1 >100 then 100 
else abs(rank_prog_3min_plus_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/100))+1 end
,phase_2_decile_3min_plus_football_premier_league_non_sky_sports = case when  annualised_programmes_3min_plus_football_premier_league_ESPN_BT=0 then 99 
when abs(rank_prog_3min_plus_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/10))+1 >10 then 10 
else 
abs(rank_prog_3min_plus_football_premier_league_ESPN_BT/(@total_programmes_3min_plus_non_sky_sports_premier_league/10))+1 end
;
commit;





