SELECT 	CASE 	WHEN FCP.EVENT_TYPE='Live' THEN 1
			 	WHEN FCP.EVENT_TYPE='Playback' AND TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD'))=TRIM(TO_CHAR(FCP.EVENT_START_DATETIME,'YYYYMMDD')) 	THEN 2
			 	WHEN FCP.EVENT_TYPE='Playback' AND TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD'))<>TRIM(TO_CHAR(FCP.EVENT_START_DATETIME,'YYYYMMDD'))  	THEN 3 
		END VIEWING_TYPE
		,FSE.ACCOUNT_NUMBER
		,FHH.WEIGHT_SCALED_VALUE WEIGHT
		,SKS.DB2_STATION_CODE 
		,CASE 	WHEN SKA.CHANNEL_GENRE LIKE 'Movies%' THEN 'Movies'
				WHEN SKA.CHANNEL_GENRE LIKE 'Sports%' THEN 'Sports'
				WHEN SKA.CHANNEL_GENRE LIKE 'Music%' THEN 'Music'
				ELSE SKA.CHANNEL_GENRE 
		END CHANNEL_GENRE
		,TO_DATE	(	CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2) in ('00','01','02','03','04','05') THEN TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME-1,'YYYYMMDD'))
								ELSE TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD')) 
						END
						,'YYYYMMDD'
					) as BARB_DATE
		,CASE	WHEN EXTRACT(DOW FROM TO_DATE	(
													CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2) in ('00','01','02','03','04','05') THEN TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME-1,'YYYYMMDD'))
															ELSE TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD')) 
													END
													,'YYYYMMDD'
												)
							)=1 THEN 7 ELSE EXTRACT(DOW FROM TO_DATE	(
																			CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2) in ('00','01','02','03','04','05') 
																						THEN TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME-1,'YYYYMMDD'))
																					ELSE TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD')) 
																			END
																			,'YYYYMMDD'
																		)
													)-1 
		END DAY_OF_WEEK
		,CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2) in ('00','01','02','03','04','05') THEN 240000 
				ELSE 0 
		END + 
		TO_NUMBER	(
						(
							TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2)) 
							|| TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME,15,2))
							|| TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME,18,2))
						)
						,'999999'
					) as START_TIME
		,CASE	WHEN TO_NUMBER(SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2),'99')<6 AND TO_NUMBER(SUBSTR(FCP.TX_EVENT_START_DATETIME+FCP.EVENT_END_CAPPED_TIME,12,2),'99')>=6 THEN 295959
				ELSE	CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME+FCP.EVENT_END_CAPPED_TIME,12,2) in ('00','01','02','03','04','05')  THEN 240000 
								ELSE 0 
						END +
						TO_NUMBER	(
										(
											TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME+FCP.EVENT_END_CAPPED_TIME,12,2)) 
											|| TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME+FCP.EVENT_END_CAPPED_TIME,15,2))
											|| TRIM(SUBSTR(FCP.TX_EVENT_START_DATETIME+FCP.EVENT_END_CAPPED_TIME,18,2))
										)
										,'999999'
									) 
		END as END_TIME
		,case 	when cast(FCP.TX_EVENT_START_DATETIME as time) > '06:00:00' 
					then cast((cast(cast(FCP.TX_EVENT_START_DATETIME+1 as date) as varchar(20)) || ' 06:00:00')as timestamp)
					else cast((cast(cast(FCP.TX_EVENT_START_DATETIME as date) as varchar(20)) || ' 06:00:00')as timestamp)
		end		as vosdal_cutoff
		,case when event_start_datetime <= vosdal_cutoff and FCP.EVENT_TYPE = 'Playback' then 1 else 0 end as VESPA_VOSDAL
FROM 	(select * from DIS_REFERENCE..FINAL_CAPPED_EVENTS_HISTORY where TX_EVENT_START_DATETIME between '2013-03-01 00:00:00' and '2013-03-01 23:59:59' limit 1000) FCP -- > Sample
		--DIS_REFERENCE..FINAL_CAPPED_EVENTS_HISTORY FCP
		,DIS_REFERENCE..FINAL_SCALING_EVENT_HISTORY FSE
		,DIS_REFERENCE..FINAL_SCALING_HOUSEHOLD_HISTORY FHH
		,system..VESPA_SERVICE_KEY_DB2_STATION_copy SKS
		,DIS_REFERENCE..SERVICE_KEY_ATTRIBUTES SKA
WHERE 	FSE.DTH_VIEWING_EVENT_ID=FCP.DTH_VIEWING_EVENT_ID
AND 	FCP.CAPPED_SHORT_DURATION_FLAG<>1
AND 	FSE.ACCOUNT_NUMBER=FHH.ACCOUNT_NUMBER
AND 	FHH.EVENT_START_DATE = cast(FCP.TX_EVENT_START_DATETIME as date)
--AND 	FHH.EVENT_START_DATE=	CASE	WHEN SUBSTR(FCP.TX_EVENT_START_DATETIME,12,2) in ('00','01','02','03','04','05') 
--										THEN TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME-1,'YYYYMMDD'))
--										ELSE TRIM(TO_CHAR(FCP.TX_EVENT_START_DATETIME,'YYYYMMDD')) 
--								END
AND 	SKS.SERVICE_KEY=FCP.SERVICE_KEY 
AND 	FCP.SERVICE_KEY=SKA.SERVICE_KEY
AND FCP.TX_EVENT_START_DATETIME BETWEEN SKA.EFFECTIVE_FROM AND SKA.EFFECTIVE_TO
limit 	100