SELECT 
a.cb_key_household
, account_number
, max(CASE 	WHEN h_mosaic_uk_group_2014 LIKE 'A' THEN 'City Prosperity'
										WHEN h_mosaic_uk_group_2014 LIKE 'B' THEN 'Prestige Positions'
										WHEN h_mosaic_uk_group_2014 LIKE 'C' THEN 'Country Living'
										WHEN h_mosaic_uk_group_2014 LIKE 'D' THEN 'Rural Reality'
										WHEN h_mosaic_uk_group_2014 LIKE 'E' THEN 'Senior Security'
										WHEN h_mosaic_uk_group_2014 LIKE 'F' THEN 'Suburban Stability'
										WHEN h_mosaic_uk_group_2014 LIKE 'G' THEN 'Domestic Success'
										WHEN h_mosaic_uk_group_2014 LIKE 'H' THEN 'Aspiring Homemakers'
										WHEN h_mosaic_uk_group_2014 LIKE 'I' THEN 'Family Basics'
										WHEN h_mosaic_uk_group_2014 LIKE 'J' THEN 'Transient Renters'
										WHEN h_mosaic_uk_group_2014 LIKE 'K' THEN 'Municipal Challenge'
										WHEN h_mosaic_uk_group_2014 LIKE 'L' THEN 'Vintage Value'
										WHEN h_mosaic_uk_group_2014 LIKE 'M' THEN 'Modest Traditions'
										WHEN h_mosaic_uk_group_2014 LIKE 'N' THEN 'Urban Cohesion'
										WHEN h_mosaic_uk_group_2014 LIKE 'O' THEN 'Rental Hubs'
										ELSE 'Unknown' END) AS mosaic_2014_groups
, MAX(CASE	WHEN h_mosaic_uk_type_2014 LIKE '01' THEN 'World-Class Wealth'
									WHEN h_mosaic_uk_type_2014 LIKE '02' THEN 'Uptown Elite'
									WHEN h_mosaic_uk_type_2014 LIKE '03' THEN 'Penthouse Chic'
									WHEN h_mosaic_uk_type_2014 LIKE '04' THEN 'Metro High-Flyers'
									WHEN h_mosaic_uk_type_2014 LIKE '05' THEN 'Premium Fortunes'
									WHEN h_mosaic_uk_type_2014 LIKE '06' THEN 'Diamond Days'
									WHEN h_mosaic_uk_type_2014 LIKE '07' THEN 'Alpha Families'
									WHEN h_mosaic_uk_type_2014 LIKE '08' THEN 'Bank of Mum and Dad'
									WHEN h_mosaic_uk_type_2014 LIKE '09' THEN 'Empty-Nest Adventure'
									WHEN h_mosaic_uk_type_2014 LIKE '10' THEN 'Wealthy Landowners'
									WHEN h_mosaic_uk_type_2014 LIKE '11' THEN 'Rural Vogue'
									WHEN h_mosaic_uk_type_2014 LIKE '12' THEN 'Scattered Homesteads'
									WHEN h_mosaic_uk_type_2014 LIKE '13' THEN 'Village Retirement'
									WHEN h_mosaic_uk_type_2014 LIKE '14' THEN 'Satellite Settlers'
									WHEN h_mosaic_uk_type_2014 LIKE '15' THEN 'Local Focus'
									WHEN h_mosaic_uk_type_2014 LIKE '16' THEN 'Outlying Seniors'
									WHEN h_mosaic_uk_type_2014 LIKE '17' THEN 'Far-Flung Outposts'
									WHEN h_mosaic_uk_type_2014 LIKE '18' THEN 'Legacy Elders'
									WHEN h_mosaic_uk_type_2014 LIKE '19' THEN 'Bungalow Haven'
									WHEN h_mosaic_uk_type_2014 LIKE '20' THEN 'Classic Grandparents'
									WHEN h_mosaic_uk_type_2014 LIKE '21' THEN 'Solo Retirees'
									WHEN h_mosaic_uk_type_2014 LIKE '22' THEN 'Boomerang Boarders'
									WHEN h_mosaic_uk_type_2014 LIKE '23' THEN 'Family Ties'
									WHEN h_mosaic_uk_type_2014 LIKE '24' THEN 'Fledgling Free'
									WHEN h_mosaic_uk_type_2014 LIKE '25' THEN 'Dependable Me'
									WHEN h_mosaic_uk_type_2014 LIKE '26' THEN 'Cafés and Catchments'
									WHEN h_mosaic_uk_type_2014 LIKE '27' THEN 'Thriving Independence'
									WHEN h_mosaic_uk_type_2014 LIKE '28' THEN 'Modern Parents'
									WHEN h_mosaic_uk_type_2014 LIKE '29' THEN 'Mid-Career Convention'
									WHEN h_mosaic_uk_type_2014 LIKE '30' THEN 'Primary Ambitions'
									WHEN h_mosaic_uk_type_2014 LIKE '31' THEN 'Affordable Fringe'
									WHEN h_mosaic_uk_type_2014 LIKE '32' THEN 'First-Rung Futures'
									WHEN h_mosaic_uk_type_2014 LIKE '33' THEN 'Contemporary Starts'
									WHEN h_mosaic_uk_type_2014 LIKE '34' THEN 'New Foundations'
									WHEN h_mosaic_uk_type_2014 LIKE '35' THEN 'Flying Solo'
									WHEN h_mosaic_uk_type_2014 LIKE '36' THEN 'Solid Economy'
									WHEN h_mosaic_uk_type_2014 LIKE '37' THEN 'Budget Generations'
									WHEN h_mosaic_uk_type_2014 LIKE '38' THEN 'Childcare Squeeze'
									WHEN h_mosaic_uk_type_2014 LIKE '39' THEN 'Families with Needs'
									WHEN h_mosaic_uk_type_2014 LIKE '40' THEN 'Make Do & Move On'
									WHEN h_mosaic_uk_type_2014 LIKE '41' THEN 'Disconnected Youth'
									WHEN h_mosaic_uk_type_2014 LIKE '42' THEN 'Midlife Stopgap'
									WHEN h_mosaic_uk_type_2014 LIKE '43' THEN 'Renting A Room'
									WHEN h_mosaic_uk_type_2014 LIKE '44' THEN 'Inner City Stalwarts'
									WHEN h_mosaic_uk_type_2014 LIKE '45' THEN 'Crowded Kaleidoscope'
									WHEN h_mosaic_uk_type_2014 LIKE '46' THEN 'High Rise Residents'
									WHEN h_mosaic_uk_type_2014 LIKE '47' THEN 'Streetwise Singles'
									WHEN h_mosaic_uk_type_2014 LIKE '48' THEN 'Low Income Workers'
									WHEN h_mosaic_uk_type_2014 LIKE '49' THEN 'Dependent Greys'
									WHEN h_mosaic_uk_type_2014 LIKE '50' THEN 'Pocket Pensions'
									WHEN h_mosaic_uk_type_2014 LIKE '51' THEN 'Aided Elderly'
									WHEN h_mosaic_uk_type_2014 LIKE '52' THEN 'Estate Veterans'
									WHEN h_mosaic_uk_type_2014 LIKE '53' THEN 'Seasoned Survivors'
									WHEN h_mosaic_uk_type_2014 LIKE '54' THEN 'Down-to-Earth Owners'
									WHEN h_mosaic_uk_type_2014 LIKE '55' THEN 'Offspring Overspill'
									WHEN h_mosaic_uk_type_2014 LIKE '56' THEN 'Self Supporters'
									WHEN h_mosaic_uk_type_2014 LIKE '57' THEN 'Community Elders'
									WHEN h_mosaic_uk_type_2014 LIKE '58' THEN 'Cultural Comfort'
									WHEN h_mosaic_uk_type_2014 LIKE '59' THEN 'Asian Heritage'
									WHEN h_mosaic_uk_type_2014 LIKE '60' THEN 'Ageing Access'
									WHEN h_mosaic_uk_type_2014 LIKE '61' THEN 'Career Builders'
									WHEN h_mosaic_uk_type_2014 LIKE '62' THEN 'Central Pulse'
									WHEN h_mosaic_uk_type_2014 LIKE '63' THEN 'Flexible Workforce'
									WHEN h_mosaic_uk_type_2014 LIKE '64' THEN 'Bus-Route Renters'
									WHEN h_mosaic_uk_type_2014 LIKE '65' THEN 'Learners & Earners'
									WHEN h_mosaic_uk_type_2014 LIKE '66' THEN 'Student Scene'
									ELSE 'Unknown' END	)  AS mosaic_2014_types
FROM CUST_SIGLE_ACCOUNT_VIEW as a
JOIN EXPERIAN_CONSUMERVIEW as b ON a.cb_key_household = b.cb_key_household
GROUP BY a.cb_key_household
, account_number

			
