/* 7.1 Service Key BARB
Copy all DELETE statements generated by Excel.
Make sure the table name is correct and execute them.
Example:
DELETE FROM VESPA_ANALYSTS.CHANNEL_MAP_DEV_SERVICE_KEY_BARB WHERE service_key = 1372 AND log_station_code = 4238 AND STI_code = 0 AND effective_from = '2006-05-02 06:00:26'; --Terminated
Copy all SELECT statements generated by Excel.
Paste them after the following INSERT statement, remove UNION from the last record and execute.
Example:
INSERT INTO VESPA_ANALYSTS.CHANNEL_MAP_DEV_SERVICE_KEY_BARB
        (
        service_key,
        log_station_code,
        STI_code,
        panel_code,
        promo_panel_code,
        effective_from,
        effective_to,
        amend_date,
        version,
        dummy_barb_code
        )
SELECT 4216,4010,0,50,50,'2008-06-09 06:00:26','2013-07-22 06:00:25','2013-09-12',26,'' -- Channel renamed+new log_station_code

*/



