/* 7.2 Service Key Landmark
Copy all DELETE statements generated by Excel.
Make sure the table name is correct and execute them.
Example:
DELETE FROM VESPA_ANALYSTS.CHANNEL_MAP_DEV_SERVICE_KEY_LANDMARK WHERE SERVICE_KEY = 3619 AND SARE_NO = 3004 AND EFFECTIVE_FROM = '2012-08-07  06:00:26'; -- Terminated
Copy all SELECT statements generated by Excel.
Paste them after the following INSERT statement, remove UNION from the last record and execute.
Example:
INSERT INTO VESPA_ANALYSTS.channel_map_dev_service_key_landmark
        (
        SERVICE_KEY,
        SARE_NO,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        amend_date,
        version
        )
SELECT 3619 , 3004,'2012-08-07  06:00:26','2013-09-17  06:00:25','2013-09-12',26 – Terminated
*/






