-- ##############################################################################################################
-- ##### Create VESPA_Shared structures                                                                     #####
-- ##############################################################################################################


-- ##############################################################################################################
-- ##### "1 record per account per period" tables                                                           #####
-- ##############################################################################################################
-- call dba.sp_drop_table('vespa_shared', 'Aggr_Account_Attributes');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Account_Attributes',
                         '
                          Id                                      bigint            identity,
                          Account_Number                          varchar(20)       not null default null,
                          Cb_Key_Household                        bigint            null     default null,
                          Period_Key                              bigint            not null default 0,
                          Panel_Id                                tinyint           not null default 0,

                          Median_Scaling_Weight                   decimal(15, 6)    null     default 0,
                          Median_Scaling_Weight_Date              date              null     default null,
                          Scaling_Weight                          decimal(15, 6)    null     default 0,
                          Scaling_Weight_Date                     date              null     default null,

                          Days_Data_Returned                      smallint          null     default 0,
                          Days_Period                             smallint          null     default 0,

                            -- Other variables
                          Acc_Univ_Model_Score                    smallint          null     default 0,

                            -- Package/product portfolio variables
                          Ent_DTV_Sub                             bit               null     default 0,
                          Ent_DTV_Pack_Original                   bit               null     default 0,
                          Ent_DTV_Pack_Variety                    bit               null     default 0,
                          Ent_DTV_Pack_Family                     bit               null     default 0,
                          Ent_DTV_Prem_Sports                     bit               null     default 0,
                          Ent_DTV_Prem_Movies                     bit               null     default 0,
                          Ent_HD_Sub                              bit               null     default 0,
                          Ent_TV3D_Sub                            bit               null     default 0,
                          Ent_ESPN_Sub                            bit               null     default 0,
                          Ent_ChelseaTV_Sub                       bit               null     default 0,
                          Ent_MUTV_Sub                            bit               null     default 0,
                          Ent_MGM_Sub                             bit               null     default 0,
                          Ent_PVR_Enabled                         bit               null     default 0,

                            -- Package/product movement flags
                          Movmt_DTV_Sub                           bit               null     default 0,
                          Movmt_DTV_Pack_Original                 bit               null     default 0,
                          Movmt_DTV_Pack_Variety                  bit               null     default 0,
                          Movmt_DTV_Pack_Family                   bit               null     default 0,
                          Movmt_DTV_Prem_Sports                   bit               null     default 0,
                          Movmt_DTV_Prem_Movies                   bit               null     default 0,
                          Movmt_HD_Sub                            bit               null     default 0,
                          Movmt_TV3D_Sub                          bit               null     default 0,
                          Movmt_ESPN_Sub                          bit               null     default 0,
                          Movmt_ChelseaTV_Sub                     bit               null     default 0,
                          Movmt_MUTV_Sub                          bit               null     default 0,
                          Movmt_MGM_Sub                           bit               null     default 0,

                          Updated_On                              datetime          not null default  timestamp,
                          Updated_By                              varchar(30)       not null default  user_name()
                         '
);

create        hg index idx01 on VESPA_Shared.Aggr_Account_Attributes(Account_Number);
create        hg index idx02 on VESPA_Shared.Aggr_Account_Attributes(Cb_Key_Household);
create        hg index idx03 on VESPA_Shared.Aggr_Account_Attributes(Period_Key);
create unique hg index idx04 on VESPA_Shared.Aggr_Account_Attributes(Account_Number, Period_Key);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Summary_Raw_All');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Summary_Raw_All',
                         '
                          Raw_Summary_Key                                                       bigint            identity,
                          Account_Number                                                        varchar(20)       null     default null,
                          Period_Key                                                            bigint            not null default 0,
                          Period_Start                                                          datetime          null     default null,
                          Period_End                                                            datetime          null     default null,

                          Raw_AvDVw__All_TV                                                     decimal(30, 6)    null     default null,
                          Raw_AvDVw__Non_Premium                                                decimal(30, 6)    null     default null,
                          Raw_SOV__Prem_Movies                                                  decimal(30, 6)    null     default null,
                          Raw_SOV__Prem_Sports                                                  decimal(30, 6)    null     default null,
                          Raw_SOV__Prem_ALa_Carte                                               decimal(30, 6)    null     default null,
                          Raw_SOV__Pack_HD                                                      decimal(30, 6)    null     default null,
                          Raw_SOV__Pack_3D                                                      decimal(30, 6)    null     default null,
                          Raw_SOV__Prem_3rd_Party                                               decimal(30, 6)    null     default null,
                          Raw_SOV__Non_Premium_Pay_TV                                           decimal(30, 6)    null     default null,
                          Raw_SOV__Non_Premium_FTA_TV                                           decimal(30, 6)    null     default null,
                          Raw_SOV__Recorded_Viewing                                             decimal(30, 6)    null     default null,
                          Raw_SOV__All_Pay_TV                                                   decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Children                                      decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Movies                                        decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_News_Documentaries                            decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Sports                                        decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Action_SciFi                                  decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Arts_Lifestyle                                decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Comedy_Game_Shows                             decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Non_Prem_Drama_Crime                                   decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_Action_Adventure                           decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_Comedy                                     decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_Drama_Romance                              decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_Family                                     decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_Horror_Thriller                            decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Movies_SciFi_Fantasy                              decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_American                                   decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Boxing_Wrestling                           decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Cricket                                    decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Football                                   decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Golf                                       decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Motor_Extreme                              decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Rugby                                      decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Tennis                                     decimal(30, 6)    null     default null,
                          Raw_SOV__Genre_Prem_Sports_Niche_Sport                                decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_BBC_News                                             decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_BBC1_BBC2_BBC3_BB4                                   decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_BT_Sports                                            decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_CBeebies                                             decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Channel_4                                            decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Channel_5                                            decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Dave                                                 decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Discovery_All                                        decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_History                                              decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_ITV_All                                              decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_MTV                                                  decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_NatGeo_All                                           decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_1                                                decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_Atlantic                                         decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_Living                                           decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_News                                             decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_Sports_1                                         decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_Sports_2                                         decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Sky_Sports_F1                                        decimal(30, 6)    null     default null,
                          Raw_SOV__Channel_Watch                                                decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__All_TV                                               decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Non_Premium                                          decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Prem_Movies                                          decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Prem_Sports                                          decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Prem_ALa_Carte                                       decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Pack_HD                                              decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Pack_3D                                              decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Prem_3rd_Party                                       decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Non_Premium_Pay_TV                                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Non_Premium_FTA_TV                                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Recorded_Viewing                                     decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__All_Pay_TV                                           decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Children                              decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Movies                                decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_News_Documentaries                    decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Sports                                decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Action_SciFi                          decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Arts_Lifestyle                        decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Comedy_Game_Shows                     decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Non_Prem_Drama_Crime                           decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_Action_Adventure                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_Comedy                             decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_Drama_Romance                      decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_Family                             decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_Horror_Thriller                    decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Movies_SciFi_Fantasy                      decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_American                           decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Boxing_Wrestling                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Cricket                            decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Football                           decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Golf                               decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Motor_Extreme                      decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Rugby                              decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Tennis                             decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Genre_Prem_Sports_Niche_Sport                        decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_BBC_News                                     decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_BBC1_BBC2_BBC3_BB4                           decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_BT_Sports                                    decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_CBeebies                                     decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Channel_4                                    decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Channel_5                                    decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Dave                                         decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Discovery_All                                decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_History                                      decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_ITV_All                                      decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_MTV                                          decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_NatGeo_All                                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_1                                        decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_Atlantic                                 decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_Living                                   decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_News                                     decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_Sports_1                                 decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_Sports_2                                 decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Sky_Sports_F1                                decimal(30, 6)    null     default null,
                          Raw_AvDNumProgs__Channel_Watch                                        decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__All_TV                                       decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Non_Premium                                  decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Prem_Movies                                  decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Prem_Sports                                  decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Prem_ALa_Carte                               decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Pack_HD                                      decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Pack_3D                                      decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Prem_3rd_Party                               decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Non_Premium_Pay_TV                           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Non_Premium_FTA_TV                           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Recorded_Viewing                             decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__All_Pay_TV                                   decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Children                      decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Movies                        decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_News_Documentaries            decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Sports                        decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Action_SciFi                  decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Arts_Lifestyle                decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Comedy_Game_Shows             decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Non_Prem_Drama_Crime                   decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_Action_Adventure           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_Comedy                     decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_Drama_Romance              decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_Family                     decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_Horror_Thriller            decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Movies_SciFi_Fantasy              decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_American                   decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Boxing_Wrestling           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Cricket                    decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Football                   decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Golf                       decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Motor_Extreme              decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Rugby                      decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Tennis                     decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Genre_Prem_Sports_Niche_Sport                decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_BBC_News                             decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_BBC1_BBC2_BBC3_BB4                   decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_BT_Sports                            decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_CBeebies                             decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Channel_4                            decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Channel_5                            decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Dave                                 decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Discovery_All                        decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_History                              decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_ITV_All                              decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_MTV                                  decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_NatGeo_All                           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_1                                decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_Atlantic                         decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_Living                           decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_News                             decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_Sports_1                         decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_Sports_2                         decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Sky_Sports_F1                        decimal(30, 6)    null     default null,
                          Raw_AvDNumCompleteProgs__Channel_Watch                                decimal(30, 6)    null     default null,
                          Raw_Flag__Offer_Seeker                                                decimal(30, 6)    null     default null,

                          Updated_On                                                            datetime          null     default timestamp,
                          Updated_By                                                            varchar(30)       null     default user_name()
                         '
                        );

create hg   index idx1 on VESPA_Shared.Aggr_Summary_Raw_All(Account_Number);
create unique index idx2 on VESPA_Shared.Aggr_Summary_Raw_All(Account_Number, Period_Key);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Summary_Low_Level_All');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Summary_Low_Level_All',
                         '
                          LL_Summary_Key                                                        bigint            identity,
                          Account_Number                                                        varchar(20)       null     default null,
                          Period_Key                                                            bigint            not null default 0,
                          Period_Start                                                          datetime          null     default null,
                          Period_End                                                            datetime          null     default null,

                          LL_AvDVw__All_TV                                                      varchar(25)       null     default null,
                          LL_AvDVw__Non_Premium                                                 varchar(25)       null     default null,
                          LL_SOV__Prem_Movies                                                   varchar(25)       null     default null,
                          LL_SOV__Prem_Sports                                                   varchar(25)       null     default null,
                          LL_SOV__Prem_ALa_Carte                                                varchar(25)       null     default null,
                          LL_SOV__Pack_HD                                                       varchar(25)       null     default null,
                          LL_SOV__Pack_3D                                                       varchar(25)       null     default null,
                          LL_SOV__Prem_3rd_Party                                                varchar(25)       null     default null,
                          LL_SOV__Non_Premium_Pay_TV                                            varchar(25)       null     default null,
                          LL_SOV__Non_Premium_FTA_TV                                            varchar(25)       null     default null,
                          LL_SOV__Recorded_Viewing                                              varchar(25)       null     default null,
                          LL_SOV__All_Pay_TV                                                    varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Children                                       varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Movies                                         varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_News_Documentaries                             varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Sports                                         varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Action_SciFi                                   varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Arts_Lifestyle                                 varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Comedy_Game_Shows                              varchar(25)       null     default null,
                          LL_SOV__Genre_Non_Prem_Drama_Crime                                    varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_Action_Adventure                            varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_Comedy                                      varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_Drama_Romance                               varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_Family                                      varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_Horror_Thriller                             varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Movies_SciFi_Fantasy                               varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_American                                    varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Boxing_Wrestling                            varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Cricket                                     varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Football                                    varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Golf                                        varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Motor_Extreme                               varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Rugby                                       varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Tennis                                      varchar(25)       null     default null,
                          LL_SOV__Genre_Prem_Sports_Niche_Sport                                 varchar(25)       null     default null,
                          LL_SOV__Channel_BBC_News                                              varchar(25)       null     default null,
                          LL_SOV__Channel_BBC1_BBC2_BBC3_BB4                                    varchar(25)       null     default null,
                          LL_SOV__Channel_BT_Sports                                             varchar(25)       null     default null,
                          LL_SOV__Channel_CBeebies                                              varchar(25)       null     default null,
                          LL_SOV__Channel_Channel_4                                             varchar(25)       null     default null,
                          LL_SOV__Channel_Channel_5                                             varchar(25)       null     default null,
                          LL_SOV__Channel_Dave                                                  varchar(25)       null     default null,
                          LL_SOV__Channel_Discovery_All                                         varchar(25)       null     default null,
                          LL_SOV__Channel_History                                               varchar(25)       null     default null,
                          LL_SOV__Channel_ITV_All                                               varchar(25)       null     default null,
                          LL_SOV__Channel_MTV                                                   varchar(25)       null     default null,
                          LL_SOV__Channel_NatGeo_All                                            varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_1                                                 varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_Atlantic                                          varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_Living                                            varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_News                                              varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_Sports_1                                          varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_Sports_2                                          varchar(25)       null     default null,
                          LL_SOV__Channel_Sky_Sports_F1                                         varchar(25)       null     default null,
                          LL_SOV__Channel_Watch                                                 varchar(25)       null     default null,
                          LL_AvDNumProgs__All_TV                                                varchar(25)       null     default null,
                          LL_AvDNumProgs__Non_Premium                                           varchar(25)       null     default null,
                          LL_AvDNumProgs__Prem_Movies                                           varchar(25)       null     default null,
                          LL_AvDNumProgs__Prem_Sports                                           varchar(25)       null     default null,
                          LL_AvDNumProgs__Prem_ALa_Carte                                        varchar(25)       null     default null,
                          LL_AvDNumProgs__Pack_HD                                               varchar(25)       null     default null,
                          LL_AvDNumProgs__Pack_3D                                               varchar(25)       null     default null,
                          LL_AvDNumProgs__Prem_3rd_Party                                        varchar(25)       null     default null,
                          LL_AvDNumProgs__Non_Premium_Pay_TV                                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Non_Premium_FTA_TV                                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Recorded_Viewing                                      varchar(25)       null     default null,
                          LL_AvDNumProgs__All_Pay_TV                                            varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Children                               varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Movies                                 varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_News_Documentaries                     varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Sports                                 varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Action_SciFi                           varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Arts_Lifestyle                         varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Comedy_Game_Shows                      varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Non_Prem_Drama_Crime                            varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_Action_Adventure                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_Comedy                              varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_Drama_Romance                       varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_Family                              varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_Horror_Thriller                     varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Movies_SciFi_Fantasy                       varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_American                            varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Boxing_Wrestling                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Cricket                             varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Football                            varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Golf                                varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Motor_Extreme                       varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Rugby                               varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Tennis                              varchar(25)       null     default null,
                          LL_AvDNumProgs__Genre_Prem_Sports_Niche_Sport                         varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_BBC_News                                      varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_BBC1_BBC2_BBC3_BB4                            varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_BT_Sports                                     varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_CBeebies                                      varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Channel_4                                     varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Channel_5                                     varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Dave                                          varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Discovery_All                                 varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_History                                       varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_ITV_All                                       varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_MTV                                           varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_NatGeo_All                                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_1                                         varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_Atlantic                                  varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_Living                                    varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_News                                      varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_Sports_1                                  varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_Sports_2                                  varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Sky_Sports_F1                                 varchar(25)       null     default null,
                          LL_AvDNumProgs__Channel_Watch                                         varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__All_TV                                        varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Non_Premium                                   varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Prem_Movies                                   varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Prem_Sports                                   varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Prem_ALa_Carte                                varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Pack_HD                                       varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Pack_3D                                       varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Prem_3rd_Party                                varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Non_Premium_Pay_TV                            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Non_Premium_FTA_TV                            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Recorded_Viewing                              varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__All_Pay_TV                                    varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Children                       varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Movies                         varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_News_Documentaries             varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Sports                         varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Action_SciFi                   varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Arts_Lifestyle                 varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Comedy_Game_Shows              varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Non_Prem_Drama_Crime                    varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_Action_Adventure            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_Comedy                      varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_Drama_Romance               varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_Family                      varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_Horror_Thriller             varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Movies_SciFi_Fantasy               varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_American                    varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Boxing_Wrestling            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Cricket                     varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Football                    varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Golf                        varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Motor_Extreme               varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Rugby                       varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Tennis                      varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Genre_Prem_Sports_Niche_Sport                 varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_BBC_News                              varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_BBC1_BBC2_BBC3_BB4                    varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_BT_Sports                             varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_CBeebies                              varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Channel_4                             varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Channel_5                             varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Dave                                  varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Discovery_All                         varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_History                               varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_ITV_All                               varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_MTV                                   varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_NatGeo_All                            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_1                                 varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_Atlantic                          varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_Living                            varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_News                              varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_Sports_1                          varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_Sports_2                          varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Sky_Sports_F1                         varchar(25)       null     default null,
                          LL_AvDNumCompleteProgs__Channel_Watch                                 varchar(25)       null     default null,

                          Updated_On                                                            datetime          null     default timestamp,
                          Updated_By                                                            varchar(30)       null     default user_name()
                         '
                        );

create hg   index idx1 on VESPA_Shared.Aggr_Summary_Low_Level_All(Account_Number);
create unique index idx2 on VESPA_Shared.Aggr_Summary_Low_Level_All(Account_Number, Period_Key);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Summary_High_Level_All');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Summary_High_Level_All',
                         '
                          HL_Summary_Key                                                        bigint            identity,
                          Account_Number                                                        varchar(20)       null     default null,
                          Period_Key                                                            bigint            not null default 0,
                          Period_Start                                                          datetime          null     default null,
                          Period_End                                                            datetime          null     default null,

                          HL_AvDVw__All_TV                                                      varchar(25)       null     default null,
                          HL_AvDVw__Non_Premium                                                 varchar(25)       null     default null,
                          HL_SOV__Prem_Movies                                                   varchar(25)       null     default null,
                          HL_SOV__Prem_Sports                                                   varchar(25)       null     default null,
                          HL_SOV__Prem_ALa_Carte                                                varchar(25)       null     default null,
                          HL_SOV__Pack_HD                                                       varchar(25)       null     default null,
                          HL_SOV__Pack_3D                                                       varchar(25)       null     default null,
                          HL_SOV__Prem_3rd_Party                                                varchar(25)       null     default null,
                          HL_SOV__Non_Premium_Pay_TV                                            varchar(25)       null     default null,
                          HL_SOV__Non_Premium_FTA_TV                                            varchar(25)       null     default null,
                          HL_SOV__Recorded_Viewing                                              varchar(25)       null     default null,
                          HL_SOV__All_Pay_TV                                                    varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Children                                       varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Movies                                         varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_News_Documentaries                             varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Sports                                         varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Action_SciFi                                   varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Arts_Lifestyle                                 varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Comedy_Game_Shows                              varchar(25)       null     default null,
                          HL_SOV__Genre_Non_Prem_Drama_Crime                                    varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_Action_Adventure                            varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_Comedy                                      varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_Drama_Romance                               varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_Family                                      varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_Horror_Thriller                             varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Movies_SciFi_Fantasy                               varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_American                                    varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Boxing_Wrestling                            varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Cricket                                     varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Football                                    varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Golf                                        varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Motor_Extreme                               varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Rugby                                       varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Tennis                                      varchar(25)       null     default null,
                          HL_SOV__Genre_Prem_Sports_Niche_Sport                                 varchar(25)       null     default null,
                          HL_SOV__Channel_BBC_News                                              varchar(25)       null     default null,
                          HL_SOV__Channel_BBC1_BBC2_BBC3_BB4                                    varchar(25)       null     default null,
                          HL_SOV__Channel_BT_Sports                                             varchar(25)       null     default null,
                          HL_SOV__Channel_CBeebies                                              varchar(25)       null     default null,
                          HL_SOV__Channel_Channel_4                                             varchar(25)       null     default null,
                          HL_SOV__Channel_Channel_5                                             varchar(25)       null     default null,
                          HL_SOV__Channel_Dave                                                  varchar(25)       null     default null,
                          HL_SOV__Channel_Discovery_All                                         varchar(25)       null     default null,
                          HL_SOV__Channel_History                                               varchar(25)       null     default null,
                          HL_SOV__Channel_ITV_All                                               varchar(25)       null     default null,
                          HL_SOV__Channel_MTV                                                   varchar(25)       null     default null,
                          HL_SOV__Channel_NatGeo_All                                            varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_1                                                 varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_Atlantic                                          varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_Living                                            varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_News                                              varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_Sports_1                                          varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_Sports_2                                          varchar(25)       null     default null,
                          HL_SOV__Channel_Sky_Sports_F1                                         varchar(25)       null     default null,
                          HL_SOV__Channel_Watch                                                 varchar(25)       null     default null,
                          HL_AvDNumProgs__All_TV                                                varchar(25)       null     default null,
                          HL_AvDNumProgs__Non_Premium                                           varchar(25)       null     default null,
                          HL_AvDNumProgs__Prem_Movies                                           varchar(25)       null     default null,
                          HL_AvDNumProgs__Prem_Sports                                           varchar(25)       null     default null,
                          HL_AvDNumProgs__Prem_ALa_Carte                                        varchar(25)       null     default null,
                          HL_AvDNumProgs__Pack_HD                                               varchar(25)       null     default null,
                          HL_AvDNumProgs__Pack_3D                                               varchar(25)       null     default null,
                          HL_AvDNumProgs__Prem_3rd_Party                                        varchar(25)       null     default null,
                          HL_AvDNumProgs__Non_Premium_Pay_TV                                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Non_Premium_FTA_TV                                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Recorded_Viewing                                      varchar(25)       null     default null,
                          HL_AvDNumProgs__All_Pay_TV                                            varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Children                               varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Movies                                 varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_News_Documentaries                     varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Sports                                 varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Action_SciFi                           varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Arts_Lifestyle                         varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Comedy_Game_Shows                      varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Non_Prem_Drama_Crime                            varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_Action_Adventure                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_Comedy                              varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_Drama_Romance                       varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_Family                              varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_Horror_Thriller                     varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Movies_SciFi_Fantasy                       varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_American                            varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Boxing_Wrestling                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Cricket                             varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Football                            varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Golf                                varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Motor_Extreme                       varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Rugby                               varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Tennis                              varchar(25)       null     default null,
                          HL_AvDNumProgs__Genre_Prem_Sports_Niche_Sport                         varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_BBC_News                                      varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_BBC1_BBC2_BBC3_BB4                            varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_BT_Sports                                     varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_CBeebies                                      varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Channel_4                                     varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Channel_5                                     varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Dave                                          varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Discovery_All                                 varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_History                                       varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_ITV_All                                       varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_MTV                                           varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_NatGeo_All                                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_1                                         varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_Atlantic                                  varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_Living                                    varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_News                                      varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_Sports_1                                  varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_Sports_2                                  varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Sky_Sports_F1                                 varchar(25)       null     default null,
                          HL_AvDNumProgs__Channel_Watch                                         varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__All_TV                                        varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Non_Premium                                   varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Prem_Movies                                   varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Prem_Sports                                   varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Prem_ALa_Carte                                varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Pack_HD                                       varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Pack_3D                                       varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Prem_3rd_Party                                varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Non_Premium_Pay_TV                            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Non_Premium_FTA_TV                            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Recorded_Viewing                              varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__All_Pay_TV                                    varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Children                       varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Movies                         varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_News_Documentaries             varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Sports                         varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Action_SciFi                   varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Arts_Lifestyle                 varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Comedy_Game_Shows              varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Non_Prem_Drama_Crime                    varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_Action_Adventure            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_Comedy                      varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_Drama_Romance               varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_Family                      varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_Horror_Thriller             varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Movies_SciFi_Fantasy               varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_American                    varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Boxing_Wrestling            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Cricket                     varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Football                    varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Golf                        varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Motor_Extreme               varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Rugby                       varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Tennis                      varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Genre_Prem_Sports_Niche_Sport                 varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_BBC_News                              varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_BBC1_BBC2_BBC3_BB4                    varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_BT_Sports                             varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_CBeebies                              varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Channel_4                             varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Channel_5                             varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Dave                                  varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Discovery_All                         varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_History                               varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_ITV_All                               varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_MTV                                   varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_NatGeo_All                            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_1                                 varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_Atlantic                          varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_Living                            varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_News                              varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_Sports_1                          varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_Sports_2                          varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Sky_Sports_F1                         varchar(25)       null     default null,
                          HL_AvDNumCompleteProgs__Channel_Watch                                 varchar(25)       null     default null,

                          Updated_On                                                            datetime          null     default timestamp,
                          Updated_By                                                            varchar(30)       null     default user_name()
                         '
                        );

create hg   index idx1 on VESPA_Shared.Aggr_Summary_High_Level_All(Account_Number);
create unique index idx2 on VESPA_Shared.Aggr_Summary_High_Level_All(Account_Number, Period_Key);



-- ##############################################################################################################
-- ##### Create star schema tables                                                                          #####
-- ##############################################################################################################
-- call dba.sp_drop_table('vespa_shared', 'Aggr_Fact');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Fact',
                         '
                          Fact_Key                                bigint            not null identity,
                          Period_Key                              bigint            not null default 0,
                          Aggregation_Key                         bigint            not null default 0,
                          Metric_Group_Key                        bigint            null     default null,
                          Account_Number                          varchar(20)       not null,
                          Panel_Id                                tinyint           not null default 0,
                          Metric_Value                            decimal(30, 6)    not null default 0,
                          Updated_On                              datetime          not null default timestamp,
                          Updated_By                              varchar(30)       not null default user_name()
                         '
                        );

create        hg index idx01 on VESPA_Shared.Aggr_Fact(Aggregation_Key);
create        hg index idx02 on VESPA_Shared.Aggr_Fact(Period_Key);
create        hg index idx03 on VESPA_Shared.Aggr_Fact(Metric_Group_Key);
create        hg index idx04 on VESPA_Shared.Aggr_Fact(Account_Number);
create        lf index idx05 on VESPA_Shared.Aggr_Fact(Panel_Id);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Metric_Group_Dim');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Metric_Group_Dim',
                         '
                          Metric_Group_Key                        bigint            not null default 0,
                          Group_Name                              varchar(50)       null     default null,
                          Low_Level_Banding                       varchar(15)       null     default null,
                          High_Level_Banding                      varchar(15)       null     default null,
                          Low_Level_Banding_Min                   decimal(30, 6)    null     default null,
                          Low_Level_Banding_Max                   decimal(30, 6)    null     default null,
                          High_Level_Banding_Min                  decimal(30, 6)    null     default null,
                          High_Level_Banding_Max                  decimal(30, 6)    null     default null,
                          Updated_On                              datetime          not null default timestamp,
                          Updated_By                              varchar(30)       not null default user_name()
                         '
                        );

create unique hg index idx01 on VESPA_Shared.Aggr_Metric_Group_Dim(Metric_Group_Key);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Period_Dim');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Period_Dim',
                         '
                          Period_Key                              bigint            not null default 0,
                          Period_Start                            datetime          not null,
                          Period_End                              datetime          not null,
                          Period_Interval_Description             varchar(25)       null     default null,
                          Period_Num_Days                         smallint          null     default null,
                          Period_Num_Hours                        smallint          null     default null,
                          Period_Num_Minutes                      bigint            null     default null,
                          Period_Num_Seconds                      bigint            null     default null,
                          Updated_On                              datetime          not null default timestamp,
                          Updated_By                              varchar(30)       not null default user_name()
                         '
                        );

create unique hg index idx01 on VESPA_Shared.Aggr_Period_Dim(Period_Key);
create      dttm index idx02 on VESPA_Shared.Aggr_Period_Dim(Period_Start);
create      dttm index idx03 on VESPA_Shared.Aggr_Period_Dim(Period_End);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Aggregation_Dim');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Aggregation_Dim',
                         '
                          Aggregation_Key                         bigint            not null default 0,
                          Aggregation_Name                        varchar(100)      not null,
                          Aggregation_Dimension                   varchar(100)       not null,
                          Aggregation_Metric                      varchar(100)       not null,
                          Aggregation_Identifier                  varchar(100)       not null,
                          Aggregation_Description                 varchar(255)      null     default null,
                          Aggregation_Type                        varchar(15)       not null,
                          Updated_On                              datetime          not null default timestamp,
                          Updated_By                              varchar(30)       not null default user_name()
                         '
                        );

create unique hg index idx01 on VESPA_Shared.Aggr_Aggregation_Dim(Aggregation_Key);
create unique hg index idx02 on VESPA_Shared.Aggr_Aggregation_Dim(Aggregation_Name);
create        lf index idx03 on VESPA_Shared.Aggr_Aggregation_Dim(Aggregation_Type);



-- call dba.sp_drop_table('vespa_shared', 'Aggr_Low_Level_Group_Summaries');
call dba.sp_create_table('vespa_shared',
                         'Aggr_Low_Level_Group_Summaries',
                         '
                          Group_Summary_Key                       bigint            not null identity,
                          Period_Key                              bigint            not null default 0,
                          Aggregation_Key                         bigint            not null default null,
                          Metric_Group_Key                        bigint            not null default null,

                          Group_Name                              varchar(15)       null     default null,
                          Group_Lower_Boundary                    decimal(30, 6)    null     default null,
                          Group_Upper_Boundary                    decimal(30, 6)    null     default null,
                          Group_Width                             decimal(30, 6)    null     default null,

                          Median_Weights_Sum                      bigint            null     default 0,
                          Scaling_Weights_Sum                     bigint            null     default 0,
                          Non_Scaled_Volume                       bigint            null     default 0,
                          Non_Scaled_Mean                         decimal(30, 6)    null     default null,
                          Non_Scaled_Median                       decimal(30, 6)    null     default null,
                          Non_Scaled_Stdev                        decimal(30, 6)    null     default null,
                          Non_Scaled_Min                          decimal(30, 6)    null     default null,
                          Non_Scaled_Max                          decimal(30, 6)    null     default null,
                          Non_Scaled_Range                        decimal(30, 6)    null     default null,

                          Updated_On                              datetime          not null default timestamp,
                          Updated_By                              varchar(30)       not null default user_name()

                         '
                        );

create        hg index idx01 on VESPA_Shared.Aggr_Low_Level_Group_Summaries(Period_Key);
create        hg index idx02 on VESPA_Shared.Aggr_Low_Level_Group_Summaries(Aggregation_Key);
create        hg index idx03 on VESPA_Shared.Aggr_Low_Level_Group_Summaries(Metric_Group_Key);
create unique hg index idx04 on VESPA_Shared.Aggr_Low_Level_Group_Summaries(Period_Key, Aggregation_Key, Metric_Group_Key);










