/*###############################################################################
# Created on:   18/09/2013
# Created by:   Sebastian Bednaszynski (SBE)
# Description:  VESPA Aggregations - metadata information creation:
#               VAggr_Meta_Grouping_Rules
#
#               (updated for historical purposes only, not to be run unless all
#                data has to be recreated from scratch)
#
#################################################################################
# Dependencies
# ------------------------------------------------------------------------------
# => Tables/objects required:
#     - VESPA_Shared.VAggr_Meta_Grouping_Rules
#
#################################################################################
# Change log
# ------------------------------------------------------------------------------
# 18/09/2013  SBE   Initial version
# 10/11/2013  SBE   New rules added (programme genres & top 20 channels)
# 28/11/2013  SBE   Binning rules changed for some aggregations
#
###############################################################################*/



--truncate table VAggr_Meta_Grouping_Rules;
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (21, 1, 10, 'low level based', 1, 4, '1) High', 5, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (22, 1, 10, 'low level based', 1, 4, '1) High', 5, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (23, 1, 10, 'low level based', 1, 4, '1) High', 5, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (24, 1,  6, 'low level based', 1, 3, '1) High', 4, 6, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (25, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (26, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (27, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (28, 1, 10, 'low level based', 1, 3, '1) High', 4, 6, '2) Medium', 7, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (29, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (30, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (31, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (32, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (33, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (34, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (35, 1,  6, 'low level based', 1, 3, '1) High', 4, 6, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (36, 1,  6, 'low level based', 1, 3, '1) High', 4, 6, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (37, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (38, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (52, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (53, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (54, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (55, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (56, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (57, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (58, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (59, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (60, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (61, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (62, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (63, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (76, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (77, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (78, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (79, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (80, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (81, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (82, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (83, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (84, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (85, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (86, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (87, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (91, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (92, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (93, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (163, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (164, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (165, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (166, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (167, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (168, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (169, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (170, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (171, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (172, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (173, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (174, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (175, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (176, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (177, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (178, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (179, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (180, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (181, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (182, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (183, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (184, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (185, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (186, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (187, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (188, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (189, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (190, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (191, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (192, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (193, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (194, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (195, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (196, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (197, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (198, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (199, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (200, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (201, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (202, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (203, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (204, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (205, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (206, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (207, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (208, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (209, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (210, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (211, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (212, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (213, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (214, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (215, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (216, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (217, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (218, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (219, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (220, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (221, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (222, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (223, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (224, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (225, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (226, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (227, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (228, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (229, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (230, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (231, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (292, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (293, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (294, 1,  6, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (295, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (296, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (297, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (298, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (299, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (300, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (301, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (302, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (303, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (304, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (305, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (306, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (307, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (308, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (309, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (310, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (311, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (312, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (313, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (314, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (315, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (316, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (317, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (318, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (319, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (320, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (321, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (322, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (323, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (324, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (325, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (326, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (327, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (328, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (329, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (330, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (331, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
commit;

insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (332, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (333, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (334, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (335, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (336, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (337, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (338, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (339, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (340, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (341, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (342, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (343, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (344, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (345, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (346, 1,  6, 'low level based', 1, 1, '1) High', 2, 3, '2) Medium', 4,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (347, 1, 10, 'low level based', 1, 3, '1) High', 4, 7, '2) Medium', 8, 10, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (348, 1,  6, 'low level based', 1, 2, '1) High', 3, 4, '2) Medium', 5,  6, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (349, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label)                                                                  values (350, 1,  3, 'low level based', 1, 1, '1) High', 2, 3, '2) Low');
insert VAggr_Meta_Grouping_Rules (Aggregation_Key, Group_Scaled, LL_Bin_Number, HL_Type, HL_Group1_Upper_Cutoff, HL_Group1_Lower_Cutoff, HL_Group1_Label, HL_Group2_Upper_Cutoff, HL_Group2_Lower_Cutoff, HL_Group2_Label, HL_Group3_Upper_Cutoff, HL_Group3_Lower_Cutoff, HL_Group3_Label) values (351, 1,  3, 'low level based', 1, 1, '1) High', 2, 2, '2) Medium', 3,  3, '3) Low');
commit;


/*
update VAggr_Meta_Grouping_Rules
   set Group_Scaled             = ,
       LL_Bin_Number            = ,
       HL_Type                  = ,
       HL_Group1_Upper_Cutoff   = ,
       HL_Group1_Lower_Cutoff   = ,
       HL_Group1_Label          = ,
       HL_Group2_Upper_Cutoff   = ,
       HL_Group2_Lower_Cutoff   = ,
       HL_Group2_Label          = ,
       HL_Group3_Upper_Cutoff   = ,
       HL_Group3_Lower_Cutoff   = ,
       HL_Group3_Label          =
  where Aggregation_Key =
;
commit;
*/













