

(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_24052013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_14062013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_19072013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_12082013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_25092013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_25102013)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_12022014)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS)
UNION ALL
(SELECT START_DATE, SUBSCRIBER_ID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HISTORY)

select date(start_date),subscriberid, case when evstandbyin_et is not null then 'STANDBY_IN'
when evstandbyout_et is not null then 'STANDBY_OUT'
when evPOWERUP_et is not null then 'POWERUP'
when evSURF_et is not null then 'SURF'
when evTRACKSURF_et is not null then 'TRACK_SURF'
when evIDLE_et is not null then 'IDLE'
when evCHANGEVIEW_et is not null then 'CHANGE_VIEW'
--when evADSMART_et is not null then 'ADSMART'
--when evADSMARTNOSUBSTITUTION_et is not null then 'ADSMART_NO_SUBSTITUTION'
--when evVODPLAYBACK_et is not null then 'VOD_PLAYBACK'
when evEMPTYLOG_et is not null then 'EMPTY_LOG' ELSE 'NULL' END EVENT_TYPE,
count(1) FROM 
((SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_24052013
where subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_14062013
where subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_19072013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_12082013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_25092013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_25102013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HIST_12022014
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS
WHERE subscriberid = '14026775')
UNION ALL
(SELECT START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et
FROM ODS_ATOMIC..ATOMIC_VESPA_VIEWING_EVENTS_ODS_HISTORY
WHERE subscriberid = '14026775'))A
group by date(start_date),subscriberid,EVENT_TYPE







select table_ref,date(start_date),subscriberid, case when evstandbyin_et is not null then 'STANDBY_IN'
when evstandbyout_et is not null then 'STANDBY_OUT'
when evPOWERUP_et is not null then 'POWERUP'
when evSURF_et is not null then 'SURF'
when evTRACKSURF_et is not null then 'TRACK_SURF'
when evIDLE_et is not null then 'IDLE'
when evCHANGEVIEW_et is not null then 'CHANGE_VIEW'
when evADSMART_et is not null then 'ADSMART'
when evADSMARTNOSUBSTITUTION_et is not null then 'ADSMART_NO_SUBSTITUTION'
when evVODPLAYBACK_et is not null then 'VOD_PLAYBACK'
when evEMPTYLOG_et is not null then 'EMPTY_LOG' ELSE 'NULL' END EVENT_TYPE,
count(1) FROM 
((SELECT '1' table_ref, START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_24052013
where subscriberid = '14026775')
UNION ALL
(SELECT '2' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_14062013
where subscriberid = '14026775')
UNION ALL
(SELECT '3' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_19072013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '4' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_12082013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '5' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_25092013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '6' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_25102013
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '7' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HIST_12022014
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '8' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS
WHERE subscriberid = '14026775')
UNION ALL
(SELECT '9' table_ref,START_DATE, SUBSCRIBERID, EVSTANDBYIN_ET,
evstandbyout_et,evPOWERUP_et,evSURF_et,evTRACKSURF_et,
evIDLE_et,evCHANGEVIEW_et,evEMPTYLOG_et,evADSMART_et,evADSMARTNOSUBSTITUTION_et,evVODPLAYBACK_et
FROM ODS_ATOMIC..ATOMIC_AMS_VIEWING_EVENTS_ODS_HISTORY
WHERE subscriberid = '14026775'))A
group by table_ref,date(start_date),subscriberid,EVENT_TYPE
