WITH 		OC AS 		( 	SELECT SH.OWNING_CUST_ACCOUNT_ID
								, Cast(To_Char(SnapShotDate, 'YYYY-MM-DD') || ' 00:00:00' AS TIMESTAMP) AS SnapShotDateTime
								, MAX(CASE WHEN (SH.SUBSCRIPTION_TYPE = 'NOW TV') AND SH.STATUS_CODE IN ('AB', 'AC', 'PC') THEN PD.DESCRIPTION END) now_tv
								, Max(CASE WHEN SH.SUBSCRIPTION_SUB_TYPE IN ('Broadband DSL Line', 'NOW_TV_2.0_BROADBAND_LINE') THEN PD.DESCRIPTION END) BBSub
								, MAX(CASE WHEN (SubStr(SH.SUBSCRIPTION_SUB_TYPE, 1, 3) <> 'DTV' OR SH.SUBSCRIPTION_TYPE <> 'NOW TV') THEN Cast(SH.STATUS_START_DT AS DATE) END) CommsLastActiveDate
							FROM (SELECT CAST(CALENDAR_DATE AS DATE) SnapShotDate FROM WH_CALENDAR_DIM WHERE CALENDAR_DATE = '2016-06-30' ) DateParameter -- Period From
							JOIN WH_PH_SUBS_HIST SH 	ON DateParameter.SnapShotDate IS NOT NULL
							JOIN WH_PRODUCT_DIM PD 		ON PRODUCT_SK = ENT_CAT_PROD_SK
							WHERE SI_LATEST_SRC = 'CHORD' 
								AND SnapShotDateTime BETWEEN SH.EFFECTIVE_FROM_DT AND SH.EFFECTIVE_TO_DT 
								AND ((SH.SUBSCRIPTION_TYPE = 'NOW TV') OR (SH.SUBSCRIPTION_SUB_TYPE IN ('Broadband DSL Line', 'NOW_TV_2.0_BROADBAND_LINE')))
							GROUP BY SnapShotDate
								, SH.OWNING_CUST_ACCOUNT_ID
							HAVING now_tv IS NOT NULL

							) 		
							
			, CC AS ( SELECT SH.OWNING_CUST_ACCOUNT_ID
							, Cast(To_Char(SnapShotDate, 'YYYY-MM-DD') || ' 00:00:00' AS TIMESTAMP) SnapShotDateTime
							, MAX(CASE WHEN (SH.SUBSCRIPTION_TYPE = 'NOW TV') AND SH.STATUS_CODE IN ('AB', 'AC', 'PC') THEN PD.DESCRIPTION END) now_tv
							, Max(CASE WHEN SH.SUBSCRIPTION_SUB_TYPE IN ('Broadband DSL Line', 'NOW_TV_2.0_BROADBAND_LINE') THEN PD.DESCRIPTION END) BBSub
							, Max(CASE WHEN (SubStr(SH.SUBSCRIPTION_SUB_TYPE, 1, 3) <> 'DTV' OR SH.SUBSCRIPTION_TYPE <> 'NOW TV') THEN Cast(SH.STATUS_START_DT AS DATE) END) CommsLastActiveDate
						FROM (SELECT CAST(CALENDAR_DATE AS DATE) + 1 SnapShotDate FROM WH_CALENDAR_DIM WHERE CALENDAR_DATE = '2016-06-30') AS a
						INNER JOIN WH_PH_SUBS_HIST SH ON SnapShotDate IS NOT NULL
						INNER JOIN WH_PRODUCT_DIM PD ON PRODUCT_SK = ENT_CAT_PROD_SK
						WHERE SI_LATEST_SRC = 'CHORD' 
							AND SnapShotDateTime BETWEEN SH.EFFECTIVE_FROM_DT AND SH.EFFECTIVE_TO_DT 
							AND ((SH.SUBSCRIPTION_TYPE = 'NOW TV') OR (SH.SUBSCRIPTION_SUB_TYPE IN ('Broadband DSL Line', 'NOW_TV_2.0_BROADBAND_LINE')))
						GROUP BY SnapShotDate
							, SH.OWNING_CUST_ACCOUNT_ID
						HAVING now_tv IS NOT NULL
						)

			, TQ AS (	SELECT OC.OWNING_CUST_ACCOUNT_ID OC_CAID, OC.SnapShotDateTime OC_SnapShotDateTime
								  , OC.BBSub OC_BBSub
								  , CC.OWNING_CUST_ACCOUNT_ID CC_CAID, CC.SnapShotDateTime CC_SnapShotDateTime
								  , CC.BBSub CC_BBSub
								  , OC.now_tv oc_now_tv
								  , CC.now_tv cc_now_tv
						FROM 		  	OC 				
						FULL JOIN		CC ON CC.OWNING_CUST_ACCOUNT_ID=OC.OWNING_CUST_ACCOUNT_ID)
																					
SELECT   Max(CU.ACCOUNT_NUMBER) ACCNO
		,Max(CU.SRC_SYSTEM_ID) SYSTEM_ID
		,DECODE(CU.ORGANISATION_UNIT,10,'SKY',20,'NOW TV') ORGUNIT
		,Max(Case When OC_BBSub Is Null Then 0 Else 1 End) OC_BBActive
		,Max(Case When OC_now_tv Is Null Then 0 Else 1 End) OC_Now_tv_active 
		,Max(Case When CC_now_tv Is Null Then 0 Else 1 End) CC_Now_tv_active 
        ,Max(Case When  SUBSCRIPTION_TYPE = 'NOW TV' Then PD.DESCRIPTION End) BBSub
        ,Max(1) CustCount
		,Max(0) ForDummyBOJoin
FROM (SELECT Cast(To_Char(CALENDAR_DATE + 1, 'YYYY-MM-DD') || ' 00:00:00' AS TIMESTAMP) SnapShotDateTime   FROM WH_CALENDAR_DIM WHERE CALENDAR_DATE = '2016-06-30' ) 		AS d 
JOIN  TQ ON d.SnapShotDateTime IS Not Null   
LEFT JOIN WH_CUST_ACCOUNT_FO CU ON CU.SRC_SYSTEM_ID=NVL(OC_CAID,CC_CAID)
LEFT JOIN WH_PH_SUBS_HIST SH ON EFFECTIVE_FROM_DT	<=	d.SnapShotDateTime
							AND EFFECTIVE_TO_DT		>	d.SnapShotDateTime
							AND SH.OWNING_CUST_ACCOUNT_ID=NVL(OC_CAID,CC_CAID)
							AND (SUBSCRIPTION_SUB_TYPE In ('Broadband DSL Line','NOW_TV_2.0_BROADBAND_LINE','NOW_TV_2.0_TALK','NOW_TV_2.0_LINE_RENTAL') OR (SUBSCRIPTION_TYPE = 'NOW TV'))
LEFT JOIN WH_PRODUCT_DIM PD ON PRODUCT_SK	=	ENT_CAT_PROD_SK
GROUP BY OC_CAID,CC_CAID
	,DECODE(CU.ORGANISATION_UNIT,10,'SKY',20,'NOW TV')

	
	
	
	-------------------------------------------------------------------------------
 	SELECT DISTINCT 
			 CU.ACCOUNT_NUMBER
			,SH.EFFECTIVE_FROM_DT 
			,SH.EFFECTIVE_TO_DT 
			,SH.STATUS_CODE
	FROM  WH_PH_SUBS_HIST 	AS SH 	
	JOIN WH_PRODUCT_DIM 	AS PD 		ON PRODUCT_SK = ENT_CAT_PROD_SK
	JOIN WH_CUST_ACCOUNT_FO AS CU 		ON CU.SRC_SYSTEM_ID = SH.OWNING_CUST_ACCOUNT_ID
	WHERE SI_LATEST_SRC = 'CHORD'		 
		 AND SH.SUBSCRIPTION_TYPE = 'NOW TV'
		 AND SH.STATUS_CODE IN ('AB', 'AC', 'PC')
		 --------------------------------------------------
		 
		 
		 
	-------------------------------------------------------------------------------
WITH ALL_act AS ( 	SELECT DISTINCT 
						 CU.ACCOUNT_NUMBER
				FROM  WH_PH_SUBS_HIST 	AS SH 	
				JOIN WH_PRODUCT_DIM 	AS PD 		ON PRODUCT_SK = ENT_CAT_PROD_SK
				JOIN WH_CUST_ACCOUNT_FO AS CU 		ON CU.SRC_SYSTEM_ID = SH.OWNING_CUST_ACCOUNT_ID
				WHERE SI_LATEST_SRC = 'CHORD'		 
					 AND SUBSCRIPTION_SUB_TYPE In ('NOW_TV_2.0_BROADBAND_LINE')
					 AND SH.STATUS_CODE IN ('AB', 'AC', 'PC')
		 	)
			
	, now_tv AS (	SELECT DISTINCT 
							 CU.ACCOUNT_NUMBER
							,SH.EFFECTIVE_FROM_DT 
							,SH.EFFECTIVE_TO_DT 
							,SH.STATUS_CODE
							, CASE WHEN x.account_number IS NULL THEN 'NOW ONLY' ELSE 'Combo' end multiflag
					FROM  WH_PH_SUBS_HIST 	AS SH 	
					JOIN WH_PRODUCT_DIM 	AS PD 		ON PRODUCT_SK = ENT_CAT_PROD_SK
					JOIN WH_CUST_ACCOUNT_FO AS CU 		ON CU.SRC_SYSTEM_ID = SH.OWNING_CUST_ACCOUNT_ID
					LEFT JOIN ALL_act AS x ON x.account_number =  CU.ACCOUNT_NUMBER
					WHERE SI_LATEST_SRC = 'CHORD'		 
						 AND SH.SUBSCRIPTION_TYPE = 'NOW TV'
						 AND SH.STATUS_CODE IN ('AB', 'AC', 'PC')
 			)
 
 SELECT multiflag, count(*) hits FROM now_tv group by multiflag
 