---script to populate the data from Jitesh's schema

--PROD TABLES 

delete from CHANNEL_MAP_CBI_PROD_SERVICE_KEY_LANDMARK;
delete from CHANNEL_MAP_CBI_PROD_SERVICE_KEY_BARB;
delete from CHANNEL_MAP_CBI_PROD_SERVICE_KEY_ATTRIBUTES;

insert into CHANNEL_MAP_CBI_PROD_SERVICE_KEY_LANDMARK
select * from patelj.CHANNEL_MAP_CBI_PROD_SERVICE_KEY_LANDMARK;

commit;

insert into CHANNEL_MAP_CBI_PROD_SERVICE_KEY_BARB
select * from patelj.CHANNEL_MAP_CBI_PROD_SERVICE_KEY_BARB;

commit;

insert into CHANNEL_MAP_CBI_PROD_SERVICE_KEY_ATTRIBUTES
select * from patelj.CHANNEL_MAP_CBI_PROD_SERVICE_KEY_ATTRIBUTES;

commit;


-----DEV TABLES
delete from CHANNEL_MAP_DEV_SERVICE_KEY_LANDMARK;
delete from CHANNEL_MAP_DEV_SERVICE_KEY_BARB;
delete from CHANNEL_MAP_DEV_SERVICE_KEY_ATTRIBUTES;
delete from CHANNEL_MAP_DEV_LOG_STATION_PANEL;
delete from CHANNEL_MAP_DEV_IANS_SENSITIVE_CHANNELS;

COMMIT;

insert into CHANNEL_MAP_DEV_SERVICE_KEY_LANDMARK
select * from patelj.CHANNEL_MAP_DEV_SERVICE_KEY_LANDMARK;

commit;


insert into CHANNEL_MAP_DEV_SERVICE_KEY_BARB
select * from patelj.CHANNEL_MAP_DEV_SERVICE_KEY_BARB;

commit;


insert into CHANNEL_MAP_DEV_SERVICE_KEY_ATTRIBUTES
select * from patelj.CHANNEL_MAP_DEV_SERVICE_KEY_ATTRIBUTES;

commit;


insert into CHANNEL_MAP_DEV_LOG_STATION_PANEL
select * from patelj.CHANNEL_MAP_DEV_LOG_STATION_PANEL;

commit;


insert into CHANNEL_MAP_DEV_IANS_SENSITIVE_CHANNELS
select * from patelj.CHANNEL_MAP_DEV_IANS_SENSITIVE_CHANNELS;

commit;
