
-----
drop table dbarnett.v250_annualised_activity_table_analysis_metrics_SOV_SKY_SPORTS;
select account_number
,sum(viewing_duration_total) as total_sky_sports_duration
into #sky_sports_duration
 from dbarnett.v250_all_sports_programmes_viewed_deduped
where channel_name='Sky Sports'
group by account_number
;
commit;
CREATE HG INDEX idx1 ON #sky_sports_duration (account_number);
commit;

--alter table dbarnett.v250_master_account_list add total_viewing_duration_sky_sports integer;

update dbarnett.v250_master_account_list
set total_viewing_duration_sky_sports= case when b.total_sky_sports_duration is null then 0 else total_sky_sports_duration end
from dbarnett.v250_master_account_list as a
left outer join #sky_sports_duration as b
on a.account_number = b.account_number
;
--select top 100 total_viewing_duration_sky_sports from  dbarnett.v250_master_account_list
--select top 500 * from #sky_sports_duration;


drop table dbarnett.v250_annualised_activity_table_analysis_metrics_SOV_SKY_SPORTS;
select a.account_number
,total_days_with_viewing
, cast(total_viewing_duration_all as real)/60 * 365/total_days_with_viewing as annualised_total_viewing_duration_all
, cast(total_viewing_duration_sports as real)/60 * 365/total_days_with_viewing as annualised_total_viewing_duration_sports
, cast(total_viewing_duration_sky_sports as real)/60 * 365/total_days_with_viewing as annualised_total_viewing_duration_sky_sports
,a.account_weight
,case when b.ATGSS_broadcast_days_viewed=0 then 0  when b.ATGSS_broadcast_days_viewed is null then 0  when c.ATGSS_days_right_viewable =0 then 0 when c.ATGSS_days_right_broadcast=0 then 0  else b.ATGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATGSS_SOV_Sky_Sports_A
,case when b.ATPSS_broadcast_days_viewed=0 then 0  when b.ATPSS_broadcast_days_viewed is null then 0  when c.ATPSS_days_right_viewable =0 then 0 when c.ATPSS_days_right_broadcast=0 then 0  else b.ATPSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATPSS_SOV_Sky_Sports_A
,case when b.AHCSS_broadcast_days_viewed=0 then 0  when b.AHCSS_broadcast_days_viewed is null then 0  when c.AHCSS_days_right_viewable =0 then 0 when c.AHCSS_days_right_broadcast=0 then 0  else b.AHCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AHCSS_SOV_Sky_Sports_A
,case when b.BOXMSS_broadcast_days_viewed=0 then 0  when b.BOXMSS_broadcast_days_viewed is null then 0  when c.BOXMSS_days_right_viewable =0 then 0 when c.BOXMSS_days_right_broadcast=0 then 0  else b.BOXMSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXMSS_SOV_Sky_Sports_A
,case when b.BILSS_broadcast_days_viewed=0 then 0  when b.BILSS_broadcast_days_viewed is null then 0  when c.BILSS_days_right_viewable =0 then 0 when c.BILSS_days_right_broadcast=0 then 0  else b.BILSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BILSS_SOV_Sky_Sports_A
,case when b.ICCSS_broadcast_days_viewed=0 then 0  when b.ICCSS_broadcast_days_viewed is null then 0  when c.ICCSS_days_right_viewable =0 then 0 when c.ICCSS_days_right_broadcast=0 then 0  else b.ICCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ICCSS_SOV_Sky_Sports_A
,case when b.CUCISS_broadcast_days_viewed=0 then 0  when b.CUCISS_broadcast_days_viewed is null then 0  when c.CUCISS_days_right_viewable =0 then 0 when c.CUCISS_days_right_broadcast=0 then 0  else b.CUCISS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CUCISS_SOV_Sky_Sports_A
,case when b.GECRSS_broadcast_days_viewed=0 then 0  when b.GECRSS_broadcast_days_viewed is null then 0  when c.GECRSS_days_right_viewable =0 then 0 when c.GECRSS_days_right_broadcast=0 then 0  else b.GECRSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GECRSS_SOV_Sky_Sports_A
,case when b.ECBNSS_broadcast_days_viewed=0 then 0  when b.ECBNSS_broadcast_days_viewed is null then 0  when c.ECBNSS_days_right_viewable =0 then 0 when c.ECBNSS_days_right_broadcast=0 then 0  else b.ECBNSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBNSS_SOV_Sky_Sports_A
,case when b.ECBTSS_broadcast_days_viewed=0 then 0  when b.ECBTSS_broadcast_days_viewed is null then 0  when c.ECBTSS_days_right_viewable =0 then 0 when c.ECBTSS_days_right_broadcast=0 then 0  else b.ECBTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBTSS_SOV_Sky_Sports_A
,case when b.ENRSS_broadcast_days_viewed=0 then 0  when b.ENRSS_broadcast_days_viewed is null then 0  when c.ENRSS_days_right_viewable =0 then 0 when c.ENRSS_days_right_broadcast=0 then 0  else b.ENRSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ENRSS_SOV_Sky_Sports_A
,case when b.ETGSS_broadcast_days_viewed=0 then 0  when b.ETGSS_broadcast_days_viewed is null then 0  when c.ETGSS_days_right_viewable =0 then 0 when c.ETGSS_days_right_broadcast=0 then 0  else b.ETGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ETGSS_SOV_Sky_Sports_A
,case when b.GF1SS_broadcast_days_viewed=0 then 0  when b.GF1SS_broadcast_days_viewed is null then 0  when c.GF1SS_days_right_viewable =0 then 0 when c.GF1SS_days_right_broadcast=0 then 0  else b.GF1SS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GF1SS_SOV_Sky_Sports_A
,case when b.FLCCSS_broadcast_days_viewed=0 then 0  when b.FLCCSS_broadcast_days_viewed is null then 0  when c.FLCCSS_days_right_viewable =0 then 0 when c.FLCCSS_days_right_broadcast=0 then 0  else b.FLCCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLCCSS_SOV_Sky_Sports_A
,case when b.FLOTSS_broadcast_days_viewed=0 then 0  when b.FLOTSS_broadcast_days_viewed is null then 0  when c.FLOTSS_days_right_viewable =0 then 0 when c.FLOTSS_days_right_broadcast=0 then 0  else b.FLOTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLOTSS_SOV_Sky_Sports_A
,case when b.F1NSS_broadcast_days_viewed=0 then 0  when b.F1NSS_broadcast_days_viewed is null then 0  when c.F1NSS_days_right_viewable =0 then 0 when c.F1NSS_days_right_broadcast=0 then 0  else b.F1NSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1NSS_SOV_Sky_Sports_A
,case when b.F1PSS_broadcast_days_viewed=0 then 0  when b.F1PSS_broadcast_days_viewed is null then 0  when c.F1PSS_days_right_viewable =0 then 0 when c.F1PSS_days_right_broadcast=0 then 0  else b.F1PSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1PSS_SOV_Sky_Sports_A
,case when b.F1QSS_broadcast_days_viewed=0 then 0  when b.F1QSS_broadcast_days_viewed is null then 0  when c.F1QSS_days_right_viewable =0 then 0 when c.F1QSS_days_right_broadcast=0 then 0  else b.F1QSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1QSS_SOV_Sky_Sports_A
,case when b.F1RSS_broadcast_days_viewed=0 then 0  when b.F1RSS_broadcast_days_viewed is null then 0  when c.F1RSS_days_right_viewable =0 then 0 when c.F1RSS_days_right_broadcast=0 then 0  else b.F1RSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1RSS_SOV_Sky_Sports_A
,case when b.HECSS_broadcast_days_viewed=0 then 0  when b.HECSS_broadcast_days_viewed is null then 0  when c.HECSS_days_right_viewable =0 then 0 when c.HECSS_days_right_broadcast=0 then 0  else b.HECSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_HECSS_SOV_Sky_Sports_A
,case when b.IRBSS_broadcast_days_viewed=0 then 0  when b.IRBSS_broadcast_days_viewed is null then 0  when c.IRBSS_days_right_viewable =0 then 0 when c.IRBSS_days_right_broadcast=0 then 0  else b.IRBSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IRBSS_SOV_Sky_Sports_A
,case when b.IHCSS_broadcast_days_viewed=0 then 0  when b.IHCSS_broadcast_days_viewed is null then 0  when c.IHCSS_days_right_viewable =0 then 0 when c.IHCSS_days_right_broadcast=0 then 0  else b.IHCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHCSS_SOV_Sky_Sports_A
,case when b.MROSS_broadcast_days_viewed=0 then 0  when b.MROSS_broadcast_days_viewed is null then 0  when c.MROSS_days_right_viewable =0 then 0 when c.MROSS_days_right_broadcast=0 then 0  else b.MROSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MROSS_SOV_Sky_Sports_A
,case when b.MRPSS_broadcast_days_viewed=0 then 0  when b.MRPSS_broadcast_days_viewed is null then 0  when c.MRPSS_days_right_viewable =0 then 0 when c.MRPSS_days_right_broadcast=0 then 0  else b.MRPSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRPSS_SOV_Sky_Sports_A
,case when b.MRSSS_broadcast_days_viewed=0 then 0  when b.MRSSS_broadcast_days_viewed is null then 0  when c.MRSSS_days_right_viewable =0 then 0 when c.MRSSS_days_right_broadcast=0 then 0  else b.MRSSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRSSS_SOV_Sky_Sports_A
,case when b.NBASS_broadcast_days_viewed=0 then 0  when b.NBASS_broadcast_days_viewed is null then 0  when c.NBASS_days_right_viewable =0 then 0 when c.NBASS_days_right_broadcast=0 then 0  else b.NBASS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NBASS_SOV_Sky_Sports_A
,case when b.NFLSS_broadcast_days_viewed=0 then 0  when b.NFLSS_broadcast_days_viewed is null then 0  when c.NFLSS_days_right_viewable =0 then 0 when c.NFLSS_days_right_broadcast=0 then 0  else b.NFLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NFLSS_SOV_Sky_Sports_A
,case when b.NIFSS_broadcast_days_viewed=0 then 0  when b.NIFSS_broadcast_days_viewed is null then 0  when c.NIFSS_days_right_viewable =0 then 0 when c.NIFSS_days_right_broadcast=0 then 0  else b.NIFSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NIFSS_SOV_Sky_Sports_A
,case when b.PGASS_broadcast_days_viewed=0 then 0  when b.PGASS_broadcast_days_viewed is null then 0  when c.PGASS_days_right_viewable =0 then 0 when c.PGASS_days_right_broadcast=0 then 0  else b.PGASS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PGASS_SOV_Sky_Sports_A
,case when b.PLDSS_broadcast_days_viewed=0 then 0  when b.PLDSS_broadcast_days_viewed is null then 0  when c.PLDSS_days_right_viewable =0 then 0 when c.PLDSS_days_right_broadcast=0 then 0  else b.PLDSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLDSS_SOV_Sky_Sports_A
,case when b.GPLSS_broadcast_days_viewed=0 then 0  when b.GPLSS_broadcast_days_viewed is null then 0  when c.GPLSS_days_right_viewable =0 then 0 when c.GPLSS_days_right_broadcast=0 then 0  else b.GPLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GPLSS_SOV_Sky_Sports_A
,case when b.PLMCSS_broadcast_days_viewed=0 then 0  when b.PLMCSS_broadcast_days_viewed is null then 0  when c.PLMCSS_days_right_viewable =0 then 0 when c.PLMCSS_days_right_broadcast=0 then 0  else b.PLMCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMCSS_SOV_Sky_Sports_A
,case when b.PLMNFSS_broadcast_days_viewed=0 then 0  when b.PLMNFSS_broadcast_days_viewed is null then 0  when c.PLMNFSS_days_right_viewable =0 then 0 when c.PLMNFSS_days_right_broadcast=0 then 0  else b.PLMNFSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMNFSS_SOV_Sky_Sports_A
,case when b.PLNLSS_broadcast_days_viewed=0 then 0  when b.PLNLSS_broadcast_days_viewed is null then 0  when c.PLNLSS_days_right_viewable =0 then 0 when c.PLNLSS_days_right_broadcast=0 then 0  else b.PLNLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLNLSS_SOV_Sky_Sports_A
,case when b.PLOLSS_broadcast_days_viewed=0 then 0  when b.PLOLSS_broadcast_days_viewed is null then 0  when c.PLOLSS_days_right_viewable =0 then 0 when c.PLOLSS_days_right_broadcast=0 then 0  else b.PLOLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLOLSS_SOV_Sky_Sports_A
,case when b.PLSLSS_broadcast_days_viewed=0 then 0  when b.PLSLSS_broadcast_days_viewed is null then 0  when c.PLSLSS_days_right_viewable =0 then 0 when c.PLSLSS_days_right_broadcast=0 then 0  else b.PLSLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSLSS_SOV_Sky_Sports_A
,case when b.PLSNSS_broadcast_days_viewed=0 then 0  when b.PLSNSS_broadcast_days_viewed is null then 0  when c.PLSNSS_days_right_viewable =0 then 0 when c.PLSNSS_days_right_broadcast=0 then 0  else b.PLSNSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSNSS_SOV_Sky_Sports_A
,case when b.PLS4SS_broadcast_days_viewed=0 then 0  when b.PLS4SS_broadcast_days_viewed is null then 0  when c.PLS4SS_days_right_viewable =0 then 0 when c.PLS4SS_days_right_broadcast=0 then 0  else b.PLS4SS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLS4SS_SOV_Sky_Sports_A
,case when b.PLSULSS_broadcast_days_viewed=0 then 0  when b.PLSULSS_broadcast_days_viewed is null then 0  when c.PLSULSS_days_right_viewable =0 then 0 when c.PLSULSS_days_right_broadcast=0 then 0  else b.PLSULSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSULSS_SOV_Sky_Sports_A
,case when b.PRUSS_broadcast_days_viewed=0 then 0  when b.PRUSS_broadcast_days_viewed is null then 0  when c.PRUSS_days_right_viewable =0 then 0 when c.PRUSS_days_right_broadcast=0 then 0  else b.PRUSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PRUSS_SOV_Sky_Sports_A
,case when b.ROISS_broadcast_days_viewed=0 then 0  when b.ROISS_broadcast_days_viewed is null then 0  when c.ROISS_days_right_viewable =0 then 0 when c.ROISS_days_right_broadcast=0 then 0  else b.ROISS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ROISS_SOV_Sky_Sports_A
,case when b.RLGSS_broadcast_days_viewed=0 then 0  when b.RLGSS_broadcast_days_viewed is null then 0  when c.RLGSS_days_right_viewable =0 then 0 when c.RLGSS_days_right_broadcast=0 then 0  else b.RLGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RLGSS_SOV_Sky_Sports_A
,case when b.SARUSS_broadcast_days_viewed=0 then 0  when b.SARUSS_broadcast_days_viewed is null then 0  when c.SARUSS_days_right_viewable =0 then 0 when c.SARUSS_days_right_broadcast=0 then 0  else b.SARUSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SARUSS_SOV_Sky_Sports_A
,case when b.SFASS_broadcast_days_viewed=0 then 0  when b.SFASS_broadcast_days_viewed is null then 0  when c.SFASS_days_right_viewable =0 then 0 when c.SFASS_days_right_broadcast=0 then 0  else b.SFASS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SFASS_SOV_Sky_Sports_A
,case when b.AMSS_broadcast_days_viewed=0 then 0  when b.AMSS_broadcast_days_viewed is null then 0  when c.AMSS_days_right_viewable =0 then 0 when c.AMSS_days_right_broadcast=0 then 0  else b.AMSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AMSS_SOV_Sky_Sports_A
,case when b.ATHSS_broadcast_days_viewed=0 then 0  when b.ATHSS_broadcast_days_viewed is null then 0  when c.ATHSS_days_right_viewable =0 then 0 when c.ATHSS_days_right_broadcast=0 then 0  else b.ATHSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATHSS_SOV_Sky_Sports_A
,case when b.BASESS_broadcast_days_viewed=0 then 0  when b.BASESS_broadcast_days_viewed is null then 0  when c.BASESS_days_right_viewable =0 then 0 when c.BASESS_days_right_broadcast=0 then 0  else b.BASESS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASESS_SOV_Sky_Sports_A
,case when b.BASKSS_broadcast_days_viewed=0 then 0  when b.BASKSS_broadcast_days_viewed is null then 0  when c.BASKSS_days_right_viewable =0 then 0 when c.BASKSS_days_right_broadcast=0 then 0  else b.BASKSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASKSS_SOV_Sky_Sports_A
,case when b.BOXSS_broadcast_days_viewed=0 then 0  when b.BOXSS_broadcast_days_viewed is null then 0  when c.BOXSS_days_right_viewable =0 then 0 when c.BOXSS_days_right_broadcast=0 then 0  else b.BOXSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXSS_SOV_Sky_Sports_A
,case when b.CRISS_broadcast_days_viewed=0 then 0  when b.CRISS_broadcast_days_viewed is null then 0  when c.CRISS_days_right_viewable =0 then 0 when c.CRISS_days_right_broadcast=0 then 0  else b.CRISS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CRISS_SOV_Sky_Sports_A
,case when b.DARTSS_broadcast_days_viewed=0 then 0  when b.DARTSS_broadcast_days_viewed is null then 0  when c.DARTSS_days_right_viewable =0 then 0 when c.DARTSS_days_right_broadcast=0 then 0  else b.DARTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_DARTSS_SOV_Sky_Sports_A
,case when b.EQUSS_broadcast_days_viewed=0 then 0  when b.EQUSS_broadcast_days_viewed is null then 0  when c.EQUSS_days_right_viewable =0 then 0 when c.EQUSS_days_right_broadcast=0 then 0  else b.EQUSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EQUSS_SOV_Sky_Sports_A
,case when b.EXTSS_broadcast_days_viewed=0 then 0  when b.EXTSS_broadcast_days_viewed is null then 0  when c.EXTSS_days_right_viewable =0 then 0 when c.EXTSS_days_right_broadcast=0 then 0  else b.EXTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EXTSS_SOV_Sky_Sports_A
,case when b.FISHSS_broadcast_days_viewed=0 then 0  when b.FISHSS_broadcast_days_viewed is null then 0  when c.FISHSS_days_right_viewable =0 then 0 when c.FISHSS_days_right_broadcast=0 then 0  else b.FISHSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FISHSS_SOV_Sky_Sports_A
,case when b.FOOTSS_broadcast_days_viewed=0 then 0  when b.FOOTSS_broadcast_days_viewed is null then 0  when c.FOOTSS_days_right_viewable =0 then 0 when c.FOOTSS_days_right_broadcast=0 then 0  else b.FOOTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FOOTSS_SOV_Sky_Sports_A
,case when b.GOLFSS_broadcast_days_viewed=0 then 0  when b.GOLFSS_broadcast_days_viewed is null then 0  when c.GOLFSS_days_right_viewable =0 then 0 when c.GOLFSS_days_right_broadcast=0 then 0  else b.GOLFSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GOLFSS_SOV_Sky_Sports_A
,case when b.IHSS_broadcast_days_viewed=0 then 0  when b.IHSS_broadcast_days_viewed is null then 0  when c.IHSS_days_right_viewable =0 then 0 when c.IHSS_days_right_broadcast=0 then 0  else b.IHSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHSS_SOV_Sky_Sports_A
,case when b.MSPSS_broadcast_days_viewed=0 then 0  when b.MSPSS_broadcast_days_viewed is null then 0  when c.MSPSS_days_right_viewable =0 then 0 when c.MSPSS_days_right_broadcast=0 then 0  else b.MSPSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MSPSS_SOV_Sky_Sports_A
,case when b.RACSS_broadcast_days_viewed=0 then 0  when b.RACSS_broadcast_days_viewed is null then 0  when c.RACSS_days_right_viewable =0 then 0 when c.RACSS_days_right_broadcast=0 then 0  else b.RACSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RACSS_SOV_Sky_Sports_A
,case when b.RUGSS_broadcast_days_viewed=0 then 0  when b.RUGSS_broadcast_days_viewed is null then 0  when c.RUGSS_days_right_viewable =0 then 0 when c.RUGSS_days_right_broadcast=0 then 0  else b.RUGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RUGSS_SOV_Sky_Sports_A
,case when b.SNPSS_broadcast_days_viewed=0 then 0  when b.SNPSS_broadcast_days_viewed is null then 0  when c.SNPSS_days_right_viewable =0 then 0 when c.SNPSS_days_right_broadcast=0 then 0  else b.SNPSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SNPSS_SOV_Sky_Sports_A
,case when b.TENSS_broadcast_days_viewed=0 then 0  when b.TENSS_broadcast_days_viewed is null then 0  when c.TENSS_days_right_viewable =0 then 0 when c.TENSS_days_right_broadcast=0 then 0  else b.TENSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_TENSS_SOV_Sky_Sports_A
,case when b.UNKSS_broadcast_days_viewed=0 then 0  when b.UNKSS_broadcast_days_viewed is null then 0  when c.UNKSS_days_right_viewable =0 then 0 when c.UNKSS_days_right_broadcast=0 then 0  else b.UNKSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_UNKSS_SOV_Sky_Sports_A
,case when b.WATSS_broadcast_days_viewed=0 then 0  when b.WATSS_broadcast_days_viewed is null then 0  when c.WATSS_days_right_viewable =0 then 0 when c.WATSS_days_right_broadcast=0 then 0  else b.WATSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WATSS_SOV_Sky_Sports_A
,case when b.WINSS_broadcast_days_viewed=0 then 0  when b.WINSS_broadcast_days_viewed is null then 0  when c.WINSS_days_right_viewable =0 then 0 when c.WINSS_days_right_broadcast=0 then 0  else b.WINSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WINSS_SOV_Sky_Sports_A
,case when b.WRESS_broadcast_days_viewed=0 then 0  when b.WRESS_broadcast_days_viewed is null then 0  when c.WRESS_days_right_viewable =0 then 0 when c.WRESS_days_right_broadcast=0 then 0  else b.WRESS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WRESS_SOV_Sky_Sports_A
,case when b.SOLSS_broadcast_days_viewed=0 then 0  when b.SOLSS_broadcast_days_viewed is null then 0  when c.SOLSS_days_right_viewable =0 then 0 when c.SOLSS_days_right_broadcast=0 then 0  else b.SOLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SOLSS_SOV_Sky_Sports_A
,case when b.SACSS_broadcast_days_viewed=0 then 0  when b.SACSS_broadcast_days_viewed is null then 0  when c.SACSS_days_right_viewable =0 then 0 when c.SACSS_days_right_broadcast=0 then 0  else b.SACSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SACSS_SOV_Sky_Sports_A
,case when b.SPFSS_broadcast_days_viewed=0 then 0  when b.SPFSS_broadcast_days_viewed is null then 0  when c.SPFSS_days_right_viewable =0 then 0 when c.SPFSS_days_right_broadcast=0 then 0  else b.SPFSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPFSS_SOV_Sky_Sports_A
,case when b.SPLSS_broadcast_days_viewed=0 then 0  when b.SPLSS_broadcast_days_viewed is null then 0  when c.SPLSS_days_right_viewable =0 then 0 when c.SPLSS_days_right_broadcast=0 then 0  else b.SPLSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPLSS_SOV_Sky_Sports_A
,case when b.SP5SS_broadcast_days_viewed=0 then 0  when b.SP5SS_broadcast_days_viewed is null then 0  when c.SP5SS_days_right_viewable =0 then 0 when c.SP5SS_days_right_broadcast=0 then 0  else b.SP5SS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SP5SS_SOV_Sky_Sports_A
,case when b.USMGSS_broadcast_days_viewed=0 then 0  when b.USMGSS_broadcast_days_viewed is null then 0  when c.USMGSS_days_right_viewable =0 then 0 when c.USMGSS_days_right_broadcast=0 then 0  else b.USMGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USMGSS_SOV_Sky_Sports_A
,case when b.USOTSS_broadcast_days_viewed=0 then 0  when b.USOTSS_broadcast_days_viewed is null then 0  when c.USOTSS_days_right_viewable =0 then 0 when c.USOTSS_days_right_broadcast=0 then 0  else b.USOTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOTSS_SOV_Sky_Sports_A
,case when b.USOGSS_broadcast_days_viewed=0 then 0  when b.USOGSS_broadcast_days_viewed is null then 0  when c.USOGSS_days_right_viewable =0 then 0 when c.USOGSS_days_right_broadcast=0 then 0  else b.USOGSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOGSS_SOV_Sky_Sports_A
,case when b.CLASS_broadcast_days_viewed=0 then 0  when b.CLASS_broadcast_days_viewed is null then 0  when c.CLASS_days_right_viewable =0 then 0 when c.CLASS_days_right_broadcast=0 then 0  else b.CLASS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLASS_SOV_Sky_Sports_A
,case when b.CLNSS_broadcast_days_viewed=0 then 0  when b.CLNSS_broadcast_days_viewed is null then 0  when c.CLNSS_days_right_viewable =0 then 0 when c.CLNSS_days_right_broadcast=0 then 0  else b.CLNSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLNSS_SOV_Sky_Sports_A
,case when b.CLOSS_broadcast_days_viewed=0 then 0  when b.CLOSS_broadcast_days_viewed is null then 0  when c.CLOSS_days_right_viewable =0 then 0 when c.CLOSS_days_right_broadcast=0 then 0  else b.CLOSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLOSS_SOV_Sky_Sports_A
,case when b.CLTSS_broadcast_days_viewed=0 then 0  when b.CLTSS_broadcast_days_viewed is null then 0  when c.CLTSS_days_right_viewable =0 then 0 when c.CLTSS_days_right_broadcast=0 then 0  else b.CLTSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLTSS_SOV_Sky_Sports_A
,case when b.CLWSS_broadcast_days_viewed=0 then 0  when b.CLWSS_broadcast_days_viewed is null then 0  when c.CLWSS_days_right_viewable =0 then 0 when c.CLWSS_days_right_broadcast=0 then 0  else b.CLWSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLWSS_SOV_Sky_Sports_A
,case when b.USPGASS_broadcast_days_viewed=0 then 0  when b.USPGASS_broadcast_days_viewed is null then 0  when c.USPGASS_days_right_viewable =0 then 0 when c.USPGASS_days_right_broadcast=0 then 0  else b.USPGASS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USPGASS_SOV_Sky_Sports_A
,case when b.WIFSS_broadcast_days_viewed=0 then 0  when b.WIFSS_broadcast_days_viewed is null then 0  when c.WIFSS_days_right_viewable =0 then 0 when c.WIFSS_days_right_broadcast=0 then 0  else b.WIFSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WIFSS_SOV_Sky_Sports_A
,case when b.WICSS_broadcast_days_viewed=0 then 0  when b.WICSS_broadcast_days_viewed is null then 0  when c.WICSS_days_right_viewable =0 then 0 when c.WICSS_days_right_broadcast=0 then 0  else b.WICSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICSS_SOV_Sky_Sports_A
,case when b.WICCSS_broadcast_days_viewed=0 then 0  when b.WICCSS_broadcast_days_viewed is null then 0  when c.WICCSS_days_right_viewable =0 then 0 when c.WICCSS_days_right_broadcast=0 then 0  else b.WICCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICCSS_SOV_Sky_Sports_A
,case when b.WDCSS_broadcast_days_viewed=0 then 0  when b.WDCSS_broadcast_days_viewed is null then 0  when c.WDCSS_days_right_viewable =0 then 0 when c.WDCSS_days_right_broadcast=0 then 0  else b.WDCSS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WDCSS_SOV_Sky_Sports_A
,case when b.WWESS_broadcast_days_viewed=0 then 0  when b.WWESS_broadcast_days_viewed is null then 0  when c.WWESS_days_right_viewable =0 then 0 when c.WWESS_days_right_broadcast=0 then 0  else b.WWESS_total_seconds_viewed / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WWESS_SOV_Sky_Sports_A
,case when d.ATGSS_broadcast_days_viewed_LIVE=0 then 0  when d.ATGSS_broadcast_days_viewed_LIVE is null then 0  when e.ATGSS_days_right_viewable_LIVE =0 then 0 when e.ATGSS_days_right_broadcast_LIVE=0 then 0  else d.ATGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATGSS_SOV_Sky_Sports_L
,case when d.ATPSS_broadcast_days_viewed_LIVE=0 then 0  when d.ATPSS_broadcast_days_viewed_LIVE is null then 0  when e.ATPSS_days_right_viewable_LIVE =0 then 0 when e.ATPSS_days_right_broadcast_LIVE=0 then 0  else d.ATPSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATPSS_SOV_Sky_Sports_L
,case when d.AHCSS_broadcast_days_viewed_LIVE=0 then 0  when d.AHCSS_broadcast_days_viewed_LIVE is null then 0  when e.AHCSS_days_right_viewable_LIVE =0 then 0 when e.AHCSS_days_right_broadcast_LIVE=0 then 0  else d.AHCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AHCSS_SOV_Sky_Sports_L
,case when d.BOXMSS_broadcast_days_viewed_LIVE=0 then 0  when d.BOXMSS_broadcast_days_viewed_LIVE is null then 0  when e.BOXMSS_days_right_viewable_LIVE =0 then 0 when e.BOXMSS_days_right_broadcast_LIVE=0 then 0  else d.BOXMSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXMSS_SOV_Sky_Sports_L
,case when d.BILSS_broadcast_days_viewed_LIVE=0 then 0  when d.BILSS_broadcast_days_viewed_LIVE is null then 0  when e.BILSS_days_right_viewable_LIVE =0 then 0 when e.BILSS_days_right_broadcast_LIVE=0 then 0  else d.BILSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BILSS_SOV_Sky_Sports_L
,case when d.ICCSS_broadcast_days_viewed_LIVE=0 then 0  when d.ICCSS_broadcast_days_viewed_LIVE is null then 0  when e.ICCSS_days_right_viewable_LIVE =0 then 0 when e.ICCSS_days_right_broadcast_LIVE=0 then 0  else d.ICCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ICCSS_SOV_Sky_Sports_L
,case when d.CUCISS_broadcast_days_viewed_LIVE=0 then 0  when d.CUCISS_broadcast_days_viewed_LIVE is null then 0  when e.CUCISS_days_right_viewable_LIVE =0 then 0 when e.CUCISS_days_right_broadcast_LIVE=0 then 0  else d.CUCISS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CUCISS_SOV_Sky_Sports_L
,case when d.GECRSS_broadcast_days_viewed_LIVE=0 then 0  when d.GECRSS_broadcast_days_viewed_LIVE is null then 0  when e.GECRSS_days_right_viewable_LIVE =0 then 0 when e.GECRSS_days_right_broadcast_LIVE=0 then 0  else d.GECRSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GECRSS_SOV_Sky_Sports_L
,case when d.ECBNSS_broadcast_days_viewed_LIVE=0 then 0  when d.ECBNSS_broadcast_days_viewed_LIVE is null then 0  when e.ECBNSS_days_right_viewable_LIVE =0 then 0 when e.ECBNSS_days_right_broadcast_LIVE=0 then 0  else d.ECBNSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBNSS_SOV_Sky_Sports_L
,case when d.ECBTSS_broadcast_days_viewed_LIVE=0 then 0  when d.ECBTSS_broadcast_days_viewed_LIVE is null then 0  when e.ECBTSS_days_right_viewable_LIVE =0 then 0 when e.ECBTSS_days_right_broadcast_LIVE=0 then 0  else d.ECBTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBTSS_SOV_Sky_Sports_L
,case when d.ENRSS_broadcast_days_viewed_LIVE=0 then 0  when d.ENRSS_broadcast_days_viewed_LIVE is null then 0  when e.ENRSS_days_right_viewable_LIVE =0 then 0 when e.ENRSS_days_right_broadcast_LIVE=0 then 0  else d.ENRSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ENRSS_SOV_Sky_Sports_L
,case when d.ETGSS_broadcast_days_viewed_LIVE=0 then 0  when d.ETGSS_broadcast_days_viewed_LIVE is null then 0  when e.ETGSS_days_right_viewable_LIVE =0 then 0 when e.ETGSS_days_right_broadcast_LIVE=0 then 0  else d.ETGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ETGSS_SOV_Sky_Sports_L
,case when d.GF1SS_broadcast_days_viewed_LIVE=0 then 0  when d.GF1SS_broadcast_days_viewed_LIVE is null then 0  when e.GF1SS_days_right_viewable_LIVE =0 then 0 when e.GF1SS_days_right_broadcast_LIVE=0 then 0  else d.GF1SS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GF1SS_SOV_Sky_Sports_L
,case when d.FLCCSS_broadcast_days_viewed_LIVE=0 then 0  when d.FLCCSS_broadcast_days_viewed_LIVE is null then 0  when e.FLCCSS_days_right_viewable_LIVE =0 then 0 when e.FLCCSS_days_right_broadcast_LIVE=0 then 0  else d.FLCCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLCCSS_SOV_Sky_Sports_L
,case when d.FLOTSS_broadcast_days_viewed_LIVE=0 then 0  when d.FLOTSS_broadcast_days_viewed_LIVE is null then 0  when e.FLOTSS_days_right_viewable_LIVE =0 then 0 when e.FLOTSS_days_right_broadcast_LIVE=0 then 0  else d.FLOTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLOTSS_SOV_Sky_Sports_L
,case when d.F1NSS_broadcast_days_viewed_LIVE=0 then 0  when d.F1NSS_broadcast_days_viewed_LIVE is null then 0  when e.F1NSS_days_right_viewable_LIVE =0 then 0 when e.F1NSS_days_right_broadcast_LIVE=0 then 0  else d.F1NSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1NSS_SOV_Sky_Sports_L
,case when d.F1PSS_broadcast_days_viewed_LIVE=0 then 0  when d.F1PSS_broadcast_days_viewed_LIVE is null then 0  when e.F1PSS_days_right_viewable_LIVE =0 then 0 when e.F1PSS_days_right_broadcast_LIVE=0 then 0  else d.F1PSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1PSS_SOV_Sky_Sports_L
,case when d.F1QSS_broadcast_days_viewed_LIVE=0 then 0  when d.F1QSS_broadcast_days_viewed_LIVE is null then 0  when e.F1QSS_days_right_viewable_LIVE =0 then 0 when e.F1QSS_days_right_broadcast_LIVE=0 then 0  else d.F1QSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1QSS_SOV_Sky_Sports_L
,case when d.F1RSS_broadcast_days_viewed_LIVE=0 then 0  when d.F1RSS_broadcast_days_viewed_LIVE is null then 0  when e.F1RSS_days_right_viewable_LIVE =0 then 0 when e.F1RSS_days_right_broadcast_LIVE=0 then 0  else d.F1RSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1RSS_SOV_Sky_Sports_L
,case when d.HECSS_broadcast_days_viewed_LIVE=0 then 0  when d.HECSS_broadcast_days_viewed_LIVE is null then 0  when e.HECSS_days_right_viewable_LIVE =0 then 0 when e.HECSS_days_right_broadcast_LIVE=0 then 0  else d.HECSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_HECSS_SOV_Sky_Sports_L
,case when d.IRBSS_broadcast_days_viewed_LIVE=0 then 0  when d.IRBSS_broadcast_days_viewed_LIVE is null then 0  when e.IRBSS_days_right_viewable_LIVE =0 then 0 when e.IRBSS_days_right_broadcast_LIVE=0 then 0  else d.IRBSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IRBSS_SOV_Sky_Sports_L
,case when d.IHCSS_broadcast_days_viewed_LIVE=0 then 0  when d.IHCSS_broadcast_days_viewed_LIVE is null then 0  when e.IHCSS_days_right_viewable_LIVE =0 then 0 when e.IHCSS_days_right_broadcast_LIVE=0 then 0  else d.IHCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHCSS_SOV_Sky_Sports_L
,case when d.MROSS_broadcast_days_viewed_LIVE=0 then 0  when d.MROSS_broadcast_days_viewed_LIVE is null then 0  when e.MROSS_days_right_viewable_LIVE =0 then 0 when e.MROSS_days_right_broadcast_LIVE=0 then 0  else d.MROSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MROSS_SOV_Sky_Sports_L
,case when d.MRPSS_broadcast_days_viewed_LIVE=0 then 0  when d.MRPSS_broadcast_days_viewed_LIVE is null then 0  when e.MRPSS_days_right_viewable_LIVE =0 then 0 when e.MRPSS_days_right_broadcast_LIVE=0 then 0  else d.MRPSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRPSS_SOV_Sky_Sports_L
,case when d.MRSSS_broadcast_days_viewed_LIVE=0 then 0  when d.MRSSS_broadcast_days_viewed_LIVE is null then 0  when e.MRSSS_days_right_viewable_LIVE =0 then 0 when e.MRSSS_days_right_broadcast_LIVE=0 then 0  else d.MRSSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRSSS_SOV_Sky_Sports_L
,case when d.NBASS_broadcast_days_viewed_LIVE=0 then 0  when d.NBASS_broadcast_days_viewed_LIVE is null then 0  when e.NBASS_days_right_viewable_LIVE =0 then 0 when e.NBASS_days_right_broadcast_LIVE=0 then 0  else d.NBASS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NBASS_SOV_Sky_Sports_L
,case when d.NFLSS_broadcast_days_viewed_LIVE=0 then 0  when d.NFLSS_broadcast_days_viewed_LIVE is null then 0  when e.NFLSS_days_right_viewable_LIVE =0 then 0 when e.NFLSS_days_right_broadcast_LIVE=0 then 0  else d.NFLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NFLSS_SOV_Sky_Sports_L
,case when d.NIFSS_broadcast_days_viewed_LIVE=0 then 0  when d.NIFSS_broadcast_days_viewed_LIVE is null then 0  when e.NIFSS_days_right_viewable_LIVE =0 then 0 when e.NIFSS_days_right_broadcast_LIVE=0 then 0  else d.NIFSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NIFSS_SOV_Sky_Sports_L
,case when d.PGASS_broadcast_days_viewed_LIVE=0 then 0  when d.PGASS_broadcast_days_viewed_LIVE is null then 0  when e.PGASS_days_right_viewable_LIVE =0 then 0 when e.PGASS_days_right_broadcast_LIVE=0 then 0  else d.PGASS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PGASS_SOV_Sky_Sports_L
,case when d.PLDSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLDSS_broadcast_days_viewed_LIVE is null then 0  when e.PLDSS_days_right_viewable_LIVE =0 then 0 when e.PLDSS_days_right_broadcast_LIVE=0 then 0  else d.PLDSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLDSS_SOV_Sky_Sports_L
,case when d.GPLSS_broadcast_days_viewed_LIVE=0 then 0  when d.GPLSS_broadcast_days_viewed_LIVE is null then 0  when e.GPLSS_days_right_viewable_LIVE =0 then 0 when e.GPLSS_days_right_broadcast_LIVE=0 then 0  else d.GPLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GPLSS_SOV_Sky_Sports_L
,case when d.PLMCSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLMCSS_broadcast_days_viewed_LIVE is null then 0  when e.PLMCSS_days_right_viewable_LIVE =0 then 0 when e.PLMCSS_days_right_broadcast_LIVE=0 then 0  else d.PLMCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMCSS_SOV_Sky_Sports_L
,case when d.PLMNFSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLMNFSS_broadcast_days_viewed_LIVE is null then 0  when e.PLMNFSS_days_right_viewable_LIVE =0 then 0 when e.PLMNFSS_days_right_broadcast_LIVE=0 then 0  else d.PLMNFSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMNFSS_SOV_Sky_Sports_L
,case when d.PLNLSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLNLSS_broadcast_days_viewed_LIVE is null then 0  when e.PLNLSS_days_right_viewable_LIVE =0 then 0 when e.PLNLSS_days_right_broadcast_LIVE=0 then 0  else d.PLNLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLNLSS_SOV_Sky_Sports_L
,case when d.PLOLSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLOLSS_broadcast_days_viewed_LIVE is null then 0  when e.PLOLSS_days_right_viewable_LIVE =0 then 0 when e.PLOLSS_days_right_broadcast_LIVE=0 then 0  else d.PLOLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLOLSS_SOV_Sky_Sports_L
,case when d.PLSLSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLSLSS_broadcast_days_viewed_LIVE is null then 0  when e.PLSLSS_days_right_viewable_LIVE =0 then 0 when e.PLSLSS_days_right_broadcast_LIVE=0 then 0  else d.PLSLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSLSS_SOV_Sky_Sports_L
,case when d.PLSNSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLSNSS_broadcast_days_viewed_LIVE is null then 0  when e.PLSNSS_days_right_viewable_LIVE =0 then 0 when e.PLSNSS_days_right_broadcast_LIVE=0 then 0  else d.PLSNSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSNSS_SOV_Sky_Sports_L
,case when d.PLS4SS_broadcast_days_viewed_LIVE=0 then 0  when d.PLS4SS_broadcast_days_viewed_LIVE is null then 0  when e.PLS4SS_days_right_viewable_LIVE =0 then 0 when e.PLS4SS_days_right_broadcast_LIVE=0 then 0  else d.PLS4SS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLS4SS_SOV_Sky_Sports_L
,case when d.PLSULSS_broadcast_days_viewed_LIVE=0 then 0  when d.PLSULSS_broadcast_days_viewed_LIVE is null then 0  when e.PLSULSS_days_right_viewable_LIVE =0 then 0 when e.PLSULSS_days_right_broadcast_LIVE=0 then 0  else d.PLSULSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSULSS_SOV_Sky_Sports_L
,case when d.PRUSS_broadcast_days_viewed_LIVE=0 then 0  when d.PRUSS_broadcast_days_viewed_LIVE is null then 0  when e.PRUSS_days_right_viewable_LIVE =0 then 0 when e.PRUSS_days_right_broadcast_LIVE=0 then 0  else d.PRUSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PRUSS_SOV_Sky_Sports_L
,case when d.ROISS_broadcast_days_viewed_LIVE=0 then 0  when d.ROISS_broadcast_days_viewed_LIVE is null then 0  when e.ROISS_days_right_viewable_LIVE =0 then 0 when e.ROISS_days_right_broadcast_LIVE=0 then 0  else d.ROISS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ROISS_SOV_Sky_Sports_L
,case when d.RLGSS_broadcast_days_viewed_LIVE=0 then 0  when d.RLGSS_broadcast_days_viewed_LIVE is null then 0  when e.RLGSS_days_right_viewable_LIVE =0 then 0 when e.RLGSS_days_right_broadcast_LIVE=0 then 0  else d.RLGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RLGSS_SOV_Sky_Sports_L
,case when d.SARUSS_broadcast_days_viewed_LIVE=0 then 0  when d.SARUSS_broadcast_days_viewed_LIVE is null then 0  when e.SARUSS_days_right_viewable_LIVE =0 then 0 when e.SARUSS_days_right_broadcast_LIVE=0 then 0  else d.SARUSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SARUSS_SOV_Sky_Sports_L
,case when d.SFASS_broadcast_days_viewed_LIVE=0 then 0  when d.SFASS_broadcast_days_viewed_LIVE is null then 0  when e.SFASS_days_right_viewable_LIVE =0 then 0 when e.SFASS_days_right_broadcast_LIVE=0 then 0  else d.SFASS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SFASS_SOV_Sky_Sports_L
,case when d.AMSS_broadcast_days_viewed_LIVE=0 then 0  when d.AMSS_broadcast_days_viewed_LIVE is null then 0  when e.AMSS_days_right_viewable_LIVE =0 then 0 when e.AMSS_days_right_broadcast_LIVE=0 then 0  else d.AMSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AMSS_SOV_Sky_Sports_L
,case when d.ATHSS_broadcast_days_viewed_LIVE=0 then 0  when d.ATHSS_broadcast_days_viewed_LIVE is null then 0  when e.ATHSS_days_right_viewable_LIVE =0 then 0 when e.ATHSS_days_right_broadcast_LIVE=0 then 0  else d.ATHSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATHSS_SOV_Sky_Sports_L
,case when d.BASESS_broadcast_days_viewed_LIVE=0 then 0  when d.BASESS_broadcast_days_viewed_LIVE is null then 0  when e.BASESS_days_right_viewable_LIVE =0 then 0 when e.BASESS_days_right_broadcast_LIVE=0 then 0  else d.BASESS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASESS_SOV_Sky_Sports_L
,case when d.BASKSS_broadcast_days_viewed_LIVE=0 then 0  when d.BASKSS_broadcast_days_viewed_LIVE is null then 0  when e.BASKSS_days_right_viewable_LIVE =0 then 0 when e.BASKSS_days_right_broadcast_LIVE=0 then 0  else d.BASKSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASKSS_SOV_Sky_Sports_L
,case when d.BOXSS_broadcast_days_viewed_LIVE=0 then 0  when d.BOXSS_broadcast_days_viewed_LIVE is null then 0  when e.BOXSS_days_right_viewable_LIVE =0 then 0 when e.BOXSS_days_right_broadcast_LIVE=0 then 0  else d.BOXSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXSS_SOV_Sky_Sports_L
,case when d.CRISS_broadcast_days_viewed_LIVE=0 then 0  when d.CRISS_broadcast_days_viewed_LIVE is null then 0  when e.CRISS_days_right_viewable_LIVE =0 then 0 when e.CRISS_days_right_broadcast_LIVE=0 then 0  else d.CRISS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CRISS_SOV_Sky_Sports_L
,case when d.DARTSS_broadcast_days_viewed_LIVE=0 then 0  when d.DARTSS_broadcast_days_viewed_LIVE is null then 0  when e.DARTSS_days_right_viewable_LIVE =0 then 0 when e.DARTSS_days_right_broadcast_LIVE=0 then 0  else d.DARTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_DARTSS_SOV_Sky_Sports_L
,case when d.EQUSS_broadcast_days_viewed_LIVE=0 then 0  when d.EQUSS_broadcast_days_viewed_LIVE is null then 0  when e.EQUSS_days_right_viewable_LIVE =0 then 0 when e.EQUSS_days_right_broadcast_LIVE=0 then 0  else d.EQUSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EQUSS_SOV_Sky_Sports_L
,case when d.EXTSS_broadcast_days_viewed_LIVE=0 then 0  when d.EXTSS_broadcast_days_viewed_LIVE is null then 0  when e.EXTSS_days_right_viewable_LIVE =0 then 0 when e.EXTSS_days_right_broadcast_LIVE=0 then 0  else d.EXTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EXTSS_SOV_Sky_Sports_L
,case when d.FISHSS_broadcast_days_viewed_LIVE=0 then 0  when d.FISHSS_broadcast_days_viewed_LIVE is null then 0  when e.FISHSS_days_right_viewable_LIVE =0 then 0 when e.FISHSS_days_right_broadcast_LIVE=0 then 0  else d.FISHSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FISHSS_SOV_Sky_Sports_L
,case when d.FOOTSS_broadcast_days_viewed_LIVE=0 then 0  when d.FOOTSS_broadcast_days_viewed_LIVE is null then 0  when e.FOOTSS_days_right_viewable_LIVE =0 then 0 when e.FOOTSS_days_right_broadcast_LIVE=0 then 0  else d.FOOTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FOOTSS_SOV_Sky_Sports_L
,case when d.GOLFSS_broadcast_days_viewed_LIVE=0 then 0  when d.GOLFSS_broadcast_days_viewed_LIVE is null then 0  when e.GOLFSS_days_right_viewable_LIVE =0 then 0 when e.GOLFSS_days_right_broadcast_LIVE=0 then 0  else d.GOLFSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GOLFSS_SOV_Sky_Sports_L
,case when d.IHSS_broadcast_days_viewed_LIVE=0 then 0  when d.IHSS_broadcast_days_viewed_LIVE is null then 0  when e.IHSS_days_right_viewable_LIVE =0 then 0 when e.IHSS_days_right_broadcast_LIVE=0 then 0  else d.IHSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHSS_SOV_Sky_Sports_L
,case when d.MSPSS_broadcast_days_viewed_LIVE=0 then 0  when d.MSPSS_broadcast_days_viewed_LIVE is null then 0  when e.MSPSS_days_right_viewable_LIVE =0 then 0 when e.MSPSS_days_right_broadcast_LIVE=0 then 0  else d.MSPSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MSPSS_SOV_Sky_Sports_L
,case when d.RACSS_broadcast_days_viewed_LIVE=0 then 0  when d.RACSS_broadcast_days_viewed_LIVE is null then 0  when e.RACSS_days_right_viewable_LIVE =0 then 0 when e.RACSS_days_right_broadcast_LIVE=0 then 0  else d.RACSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RACSS_SOV_Sky_Sports_L
,case when d.RUGSS_broadcast_days_viewed_LIVE=0 then 0  when d.RUGSS_broadcast_days_viewed_LIVE is null then 0  when e.RUGSS_days_right_viewable_LIVE =0 then 0 when e.RUGSS_days_right_broadcast_LIVE=0 then 0  else d.RUGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RUGSS_SOV_Sky_Sports_L
,case when d.SNPSS_broadcast_days_viewed_LIVE=0 then 0  when d.SNPSS_broadcast_days_viewed_LIVE is null then 0  when e.SNPSS_days_right_viewable_LIVE =0 then 0 when e.SNPSS_days_right_broadcast_LIVE=0 then 0  else d.SNPSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SNPSS_SOV_Sky_Sports_L
,case when d.TENSS_broadcast_days_viewed_LIVE=0 then 0  when d.TENSS_broadcast_days_viewed_LIVE is null then 0  when e.TENSS_days_right_viewable_LIVE =0 then 0 when e.TENSS_days_right_broadcast_LIVE=0 then 0  else d.TENSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_TENSS_SOV_Sky_Sports_L
,case when d.UNKSS_broadcast_days_viewed_LIVE=0 then 0  when d.UNKSS_broadcast_days_viewed_LIVE is null then 0  when e.UNKSS_days_right_viewable_LIVE =0 then 0 when e.UNKSS_days_right_broadcast_LIVE=0 then 0  else d.UNKSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_UNKSS_SOV_Sky_Sports_L
,case when d.WATSS_broadcast_days_viewed_LIVE=0 then 0  when d.WATSS_broadcast_days_viewed_LIVE is null then 0  when e.WATSS_days_right_viewable_LIVE =0 then 0 when e.WATSS_days_right_broadcast_LIVE=0 then 0  else d.WATSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WATSS_SOV_Sky_Sports_L
,case when d.WINSS_broadcast_days_viewed_LIVE=0 then 0  when d.WINSS_broadcast_days_viewed_LIVE is null then 0  when e.WINSS_days_right_viewable_LIVE =0 then 0 when e.WINSS_days_right_broadcast_LIVE=0 then 0  else d.WINSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WINSS_SOV_Sky_Sports_L
,case when d.WRESS_broadcast_days_viewed_LIVE=0 then 0  when d.WRESS_broadcast_days_viewed_LIVE is null then 0  when e.WRESS_days_right_viewable_LIVE =0 then 0 when e.WRESS_days_right_broadcast_LIVE=0 then 0  else d.WRESS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WRESS_SOV_Sky_Sports_L
,case when d.SOLSS_broadcast_days_viewed_LIVE=0 then 0  when d.SOLSS_broadcast_days_viewed_LIVE is null then 0  when e.SOLSS_days_right_viewable_LIVE =0 then 0 when e.SOLSS_days_right_broadcast_LIVE=0 then 0  else d.SOLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SOLSS_SOV_Sky_Sports_L
,case when d.SACSS_broadcast_days_viewed_LIVE=0 then 0  when d.SACSS_broadcast_days_viewed_LIVE is null then 0  when e.SACSS_days_right_viewable_LIVE =0 then 0 when e.SACSS_days_right_broadcast_LIVE=0 then 0  else d.SACSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SACSS_SOV_Sky_Sports_L
,case when d.SPFSS_broadcast_days_viewed_LIVE=0 then 0  when d.SPFSS_broadcast_days_viewed_LIVE is null then 0  when e.SPFSS_days_right_viewable_LIVE =0 then 0 when e.SPFSS_days_right_broadcast_LIVE=0 then 0  else d.SPFSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPFSS_SOV_Sky_Sports_L
,case when d.SPLSS_broadcast_days_viewed_LIVE=0 then 0  when d.SPLSS_broadcast_days_viewed_LIVE is null then 0  when e.SPLSS_days_right_viewable_LIVE =0 then 0 when e.SPLSS_days_right_broadcast_LIVE=0 then 0  else d.SPLSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPLSS_SOV_Sky_Sports_L
,case when d.SP5SS_broadcast_days_viewed_LIVE=0 then 0  when d.SP5SS_broadcast_days_viewed_LIVE is null then 0  when e.SP5SS_days_right_viewable_LIVE =0 then 0 when e.SP5SS_days_right_broadcast_LIVE=0 then 0  else d.SP5SS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SP5SS_SOV_Sky_Sports_L
,case when d.USMGSS_broadcast_days_viewed_LIVE=0 then 0  when d.USMGSS_broadcast_days_viewed_LIVE is null then 0  when e.USMGSS_days_right_viewable_LIVE =0 then 0 when e.USMGSS_days_right_broadcast_LIVE=0 then 0  else d.USMGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USMGSS_SOV_Sky_Sports_L
,case when d.USOTSS_broadcast_days_viewed_LIVE=0 then 0  when d.USOTSS_broadcast_days_viewed_LIVE is null then 0  when e.USOTSS_days_right_viewable_LIVE =0 then 0 when e.USOTSS_days_right_broadcast_LIVE=0 then 0  else d.USOTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOTSS_SOV_Sky_Sports_L
,case when d.USOGSS_broadcast_days_viewed_LIVE=0 then 0  when d.USOGSS_broadcast_days_viewed_LIVE is null then 0  when e.USOGSS_days_right_viewable_LIVE =0 then 0 when e.USOGSS_days_right_broadcast_LIVE=0 then 0  else d.USOGSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOGSS_SOV_Sky_Sports_L
,case when d.CLASS_broadcast_days_viewed_LIVE=0 then 0  when d.CLASS_broadcast_days_viewed_LIVE is null then 0  when e.CLASS_days_right_viewable_LIVE =0 then 0 when e.CLASS_days_right_broadcast_LIVE=0 then 0  else d.CLASS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLASS_SOV_Sky_Sports_L
,case when d.CLNSS_broadcast_days_viewed_LIVE=0 then 0  when d.CLNSS_broadcast_days_viewed_LIVE is null then 0  when e.CLNSS_days_right_viewable_LIVE =0 then 0 when e.CLNSS_days_right_broadcast_LIVE=0 then 0  else d.CLNSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLNSS_SOV_Sky_Sports_L
,case when d.CLOSS_broadcast_days_viewed_LIVE=0 then 0  when d.CLOSS_broadcast_days_viewed_LIVE is null then 0  when e.CLOSS_days_right_viewable_LIVE =0 then 0 when e.CLOSS_days_right_broadcast_LIVE=0 then 0  else d.CLOSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLOSS_SOV_Sky_Sports_L
,case when d.CLTSS_broadcast_days_viewed_LIVE=0 then 0  when d.CLTSS_broadcast_days_viewed_LIVE is null then 0  when e.CLTSS_days_right_viewable_LIVE =0 then 0 when e.CLTSS_days_right_broadcast_LIVE=0 then 0  else d.CLTSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLTSS_SOV_Sky_Sports_L
,case when d.CLWSS_broadcast_days_viewed_LIVE=0 then 0  when d.CLWSS_broadcast_days_viewed_LIVE is null then 0  when e.CLWSS_days_right_viewable_LIVE =0 then 0 when e.CLWSS_days_right_broadcast_LIVE=0 then 0  else d.CLWSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLWSS_SOV_Sky_Sports_L
,case when d.USPGASS_broadcast_days_viewed_LIVE=0 then 0  when d.USPGASS_broadcast_days_viewed_LIVE is null then 0  when e.USPGASS_days_right_viewable_LIVE =0 then 0 when e.USPGASS_days_right_broadcast_LIVE=0 then 0  else d.USPGASS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USPGASS_SOV_Sky_Sports_L
,case when d.WIFSS_broadcast_days_viewed_LIVE=0 then 0  when d.WIFSS_broadcast_days_viewed_LIVE is null then 0  when e.WIFSS_days_right_viewable_LIVE =0 then 0 when e.WIFSS_days_right_broadcast_LIVE=0 then 0  else d.WIFSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WIFSS_SOV_Sky_Sports_L
,case when d.WICSS_broadcast_days_viewed_LIVE=0 then 0  when d.WICSS_broadcast_days_viewed_LIVE is null then 0  when e.WICSS_days_right_viewable_LIVE =0 then 0 when e.WICSS_days_right_broadcast_LIVE=0 then 0  else d.WICSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICSS_SOV_Sky_Sports_L
,case when d.WICCSS_broadcast_days_viewed_LIVE=0 then 0  when d.WICCSS_broadcast_days_viewed_LIVE is null then 0  when e.WICCSS_days_right_viewable_LIVE =0 then 0 when e.WICCSS_days_right_broadcast_LIVE=0 then 0  else d.WICCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICCSS_SOV_Sky_Sports_L
,case when d.WDCSS_broadcast_days_viewed_LIVE=0 then 0  when d.WDCSS_broadcast_days_viewed_LIVE is null then 0  when e.WDCSS_days_right_viewable_LIVE =0 then 0 when e.WDCSS_days_right_broadcast_LIVE=0 then 0  else d.WDCSS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WDCSS_SOV_Sky_Sports_L
,case when d.WWESS_broadcast_days_viewed_LIVE=0 then 0  when d.WWESS_broadcast_days_viewed_LIVE is null then 0  when e.WWESS_days_right_viewable_LIVE =0 then 0 when e.WWESS_days_right_broadcast_LIVE=0 then 0  else d.WWESS_total_seconds_viewed_LIVE / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WWESS_SOV_Sky_Sports_L
,case when d.ATGSS_broadcast_days_viewedNon_Live=0 then 0  when d.ATGSS_broadcast_days_viewedNon_Live is null then 0  when e.ATGSS_days_right_viewableNon_Live =0 then 0 when e.ATGSS_days_right_broadcastNon_Live=0 then 0  else d.ATGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATGSS_SOV_Sky_Sports_N
,case when d.ATPSS_broadcast_days_viewedNon_Live=0 then 0  when d.ATPSS_broadcast_days_viewedNon_Live is null then 0  when e.ATPSS_days_right_viewableNon_Live =0 then 0 when e.ATPSS_days_right_broadcastNon_Live=0 then 0  else d.ATPSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATPSS_SOV_Sky_Sports_N
,case when d.AHCSS_broadcast_days_viewedNon_Live=0 then 0  when d.AHCSS_broadcast_days_viewedNon_Live is null then 0  when e.AHCSS_days_right_viewableNon_Live =0 then 0 when e.AHCSS_days_right_broadcastNon_Live=0 then 0  else d.AHCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AHCSS_SOV_Sky_Sports_N
,case when d.BOXMSS_broadcast_days_viewedNon_Live=0 then 0  when d.BOXMSS_broadcast_days_viewedNon_Live is null then 0  when e.BOXMSS_days_right_viewableNon_Live =0 then 0 when e.BOXMSS_days_right_broadcastNon_Live=0 then 0  else d.BOXMSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXMSS_SOV_Sky_Sports_N
,case when d.BILSS_broadcast_days_viewedNon_Live=0 then 0  when d.BILSS_broadcast_days_viewedNon_Live is null then 0  when e.BILSS_days_right_viewableNon_Live =0 then 0 when e.BILSS_days_right_broadcastNon_Live=0 then 0  else d.BILSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BILSS_SOV_Sky_Sports_N
,case when d.ICCSS_broadcast_days_viewedNon_Live=0 then 0  when d.ICCSS_broadcast_days_viewedNon_Live is null then 0  when e.ICCSS_days_right_viewableNon_Live =0 then 0 when e.ICCSS_days_right_broadcastNon_Live=0 then 0  else d.ICCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ICCSS_SOV_Sky_Sports_N
,case when d.CUCISS_broadcast_days_viewedNon_Live=0 then 0  when d.CUCISS_broadcast_days_viewedNon_Live is null then 0  when e.CUCISS_days_right_viewableNon_Live =0 then 0 when e.CUCISS_days_right_broadcastNon_Live=0 then 0  else d.CUCISS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CUCISS_SOV_Sky_Sports_N
,case when d.GECRSS_broadcast_days_viewedNon_Live=0 then 0  when d.GECRSS_broadcast_days_viewedNon_Live is null then 0  when e.GECRSS_days_right_viewableNon_Live =0 then 0 when e.GECRSS_days_right_broadcastNon_Live=0 then 0  else d.GECRSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GECRSS_SOV_Sky_Sports_N
,case when d.ECBNSS_broadcast_days_viewedNon_Live=0 then 0  when d.ECBNSS_broadcast_days_viewedNon_Live is null then 0  when e.ECBNSS_days_right_viewableNon_Live =0 then 0 when e.ECBNSS_days_right_broadcastNon_Live=0 then 0  else d.ECBNSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBNSS_SOV_Sky_Sports_N
,case when d.ECBTSS_broadcast_days_viewedNon_Live=0 then 0  when d.ECBTSS_broadcast_days_viewedNon_Live is null then 0  when e.ECBTSS_days_right_viewableNon_Live =0 then 0 when e.ECBTSS_days_right_broadcastNon_Live=0 then 0  else d.ECBTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ECBTSS_SOV_Sky_Sports_N
,case when d.ENRSS_broadcast_days_viewedNon_Live=0 then 0  when d.ENRSS_broadcast_days_viewedNon_Live is null then 0  when e.ENRSS_days_right_viewableNon_Live =0 then 0 when e.ENRSS_days_right_broadcastNon_Live=0 then 0  else d.ENRSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ENRSS_SOV_Sky_Sports_N
,case when d.ETGSS_broadcast_days_viewedNon_Live=0 then 0  when d.ETGSS_broadcast_days_viewedNon_Live is null then 0  when e.ETGSS_days_right_viewableNon_Live =0 then 0 when e.ETGSS_days_right_broadcastNon_Live=0 then 0  else d.ETGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ETGSS_SOV_Sky_Sports_N
,case when d.GF1SS_broadcast_days_viewedNon_Live=0 then 0  when d.GF1SS_broadcast_days_viewedNon_Live is null then 0  when e.GF1SS_days_right_viewableNon_Live =0 then 0 when e.GF1SS_days_right_broadcastNon_Live=0 then 0  else d.GF1SS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GF1SS_SOV_Sky_Sports_N
,case when d.FLCCSS_broadcast_days_viewedNon_Live=0 then 0  when d.FLCCSS_broadcast_days_viewedNon_Live is null then 0  when e.FLCCSS_days_right_viewableNon_Live =0 then 0 when e.FLCCSS_days_right_broadcastNon_Live=0 then 0  else d.FLCCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLCCSS_SOV_Sky_Sports_N
,case when d.FLOTSS_broadcast_days_viewedNon_Live=0 then 0  when d.FLOTSS_broadcast_days_viewedNon_Live is null then 0  when e.FLOTSS_days_right_viewableNon_Live =0 then 0 when e.FLOTSS_days_right_broadcastNon_Live=0 then 0  else d.FLOTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FLOTSS_SOV_Sky_Sports_N
,case when d.F1NSS_broadcast_days_viewedNon_Live=0 then 0  when d.F1NSS_broadcast_days_viewedNon_Live is null then 0  when e.F1NSS_days_right_viewableNon_Live =0 then 0 when e.F1NSS_days_right_broadcastNon_Live=0 then 0  else d.F1NSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1NSS_SOV_Sky_Sports_N
,case when d.F1PSS_broadcast_days_viewedNon_Live=0 then 0  when d.F1PSS_broadcast_days_viewedNon_Live is null then 0  when e.F1PSS_days_right_viewableNon_Live =0 then 0 when e.F1PSS_days_right_broadcastNon_Live=0 then 0  else d.F1PSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1PSS_SOV_Sky_Sports_N
,case when d.F1QSS_broadcast_days_viewedNon_Live=0 then 0  when d.F1QSS_broadcast_days_viewedNon_Live is null then 0  when e.F1QSS_days_right_viewableNon_Live =0 then 0 when e.F1QSS_days_right_broadcastNon_Live=0 then 0  else d.F1QSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1QSS_SOV_Sky_Sports_N
,case when d.F1RSS_broadcast_days_viewedNon_Live=0 then 0  when d.F1RSS_broadcast_days_viewedNon_Live is null then 0  when e.F1RSS_days_right_viewableNon_Live =0 then 0 when e.F1RSS_days_right_broadcastNon_Live=0 then 0  else d.F1RSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_F1RSS_SOV_Sky_Sports_N
,case when d.HECSS_broadcast_days_viewedNon_Live=0 then 0  when d.HECSS_broadcast_days_viewedNon_Live is null then 0  when e.HECSS_days_right_viewableNon_Live =0 then 0 when e.HECSS_days_right_broadcastNon_Live=0 then 0  else d.HECSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_HECSS_SOV_Sky_Sports_N
,case when d.IRBSS_broadcast_days_viewedNon_Live=0 then 0  when d.IRBSS_broadcast_days_viewedNon_Live is null then 0  when e.IRBSS_days_right_viewableNon_Live =0 then 0 when e.IRBSS_days_right_broadcastNon_Live=0 then 0  else d.IRBSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IRBSS_SOV_Sky_Sports_N
,case when d.IHCSS_broadcast_days_viewedNon_Live=0 then 0  when d.IHCSS_broadcast_days_viewedNon_Live is null then 0  when e.IHCSS_days_right_viewableNon_Live =0 then 0 when e.IHCSS_days_right_broadcastNon_Live=0 then 0  else d.IHCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHCSS_SOV_Sky_Sports_N
,case when d.MROSS_broadcast_days_viewedNon_Live=0 then 0  when d.MROSS_broadcast_days_viewedNon_Live is null then 0  when e.MROSS_days_right_viewableNon_Live =0 then 0 when e.MROSS_days_right_broadcastNon_Live=0 then 0  else d.MROSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MROSS_SOV_Sky_Sports_N
,case when d.MRPSS_broadcast_days_viewedNon_Live=0 then 0  when d.MRPSS_broadcast_days_viewedNon_Live is null then 0  when e.MRPSS_days_right_viewableNon_Live =0 then 0 when e.MRPSS_days_right_broadcastNon_Live=0 then 0  else d.MRPSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRPSS_SOV_Sky_Sports_N
,case when d.MRSSS_broadcast_days_viewedNon_Live=0 then 0  when d.MRSSS_broadcast_days_viewedNon_Live is null then 0  when e.MRSSS_days_right_viewableNon_Live =0 then 0 when e.MRSSS_days_right_broadcastNon_Live=0 then 0  else d.MRSSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MRSSS_SOV_Sky_Sports_N
,case when d.NBASS_broadcast_days_viewedNon_Live=0 then 0  when d.NBASS_broadcast_days_viewedNon_Live is null then 0  when e.NBASS_days_right_viewableNon_Live =0 then 0 when e.NBASS_days_right_broadcastNon_Live=0 then 0  else d.NBASS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NBASS_SOV_Sky_Sports_N
,case when d.NFLSS_broadcast_days_viewedNon_Live=0 then 0  when d.NFLSS_broadcast_days_viewedNon_Live is null then 0  when e.NFLSS_days_right_viewableNon_Live =0 then 0 when e.NFLSS_days_right_broadcastNon_Live=0 then 0  else d.NFLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NFLSS_SOV_Sky_Sports_N
,case when d.NIFSS_broadcast_days_viewedNon_Live=0 then 0  when d.NIFSS_broadcast_days_viewedNon_Live is null then 0  when e.NIFSS_days_right_viewableNon_Live =0 then 0 when e.NIFSS_days_right_broadcastNon_Live=0 then 0  else d.NIFSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_NIFSS_SOV_Sky_Sports_N
,case when d.PGASS_broadcast_days_viewedNon_Live=0 then 0  when d.PGASS_broadcast_days_viewedNon_Live is null then 0  when e.PGASS_days_right_viewableNon_Live =0 then 0 when e.PGASS_days_right_broadcastNon_Live=0 then 0  else d.PGASS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PGASS_SOV_Sky_Sports_N
,case when d.PLDSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLDSS_broadcast_days_viewedNon_Live is null then 0  when e.PLDSS_days_right_viewableNon_Live =0 then 0 when e.PLDSS_days_right_broadcastNon_Live=0 then 0  else d.PLDSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLDSS_SOV_Sky_Sports_N
,case when d.GPLSS_broadcast_days_viewedNon_Live=0 then 0  when d.GPLSS_broadcast_days_viewedNon_Live is null then 0  when e.GPLSS_days_right_viewableNon_Live =0 then 0 when e.GPLSS_days_right_broadcastNon_Live=0 then 0  else d.GPLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GPLSS_SOV_Sky_Sports_N
,case when d.PLMCSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLMCSS_broadcast_days_viewedNon_Live is null then 0  when e.PLMCSS_days_right_viewableNon_Live =0 then 0 when e.PLMCSS_days_right_broadcastNon_Live=0 then 0  else d.PLMCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMCSS_SOV_Sky_Sports_N
,case when d.PLMNFSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLMNFSS_broadcast_days_viewedNon_Live is null then 0  when e.PLMNFSS_days_right_viewableNon_Live =0 then 0 when e.PLMNFSS_days_right_broadcastNon_Live=0 then 0  else d.PLMNFSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLMNFSS_SOV_Sky_Sports_N
,case when d.PLNLSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLNLSS_broadcast_days_viewedNon_Live is null then 0  when e.PLNLSS_days_right_viewableNon_Live =0 then 0 when e.PLNLSS_days_right_broadcastNon_Live=0 then 0  else d.PLNLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLNLSS_SOV_Sky_Sports_N
,case when d.PLOLSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLOLSS_broadcast_days_viewedNon_Live is null then 0  when e.PLOLSS_days_right_viewableNon_Live =0 then 0 when e.PLOLSS_days_right_broadcastNon_Live=0 then 0  else d.PLOLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLOLSS_SOV_Sky_Sports_N
,case when d.PLSLSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLSLSS_broadcast_days_viewedNon_Live is null then 0  when e.PLSLSS_days_right_viewableNon_Live =0 then 0 when e.PLSLSS_days_right_broadcastNon_Live=0 then 0  else d.PLSLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSLSS_SOV_Sky_Sports_N
,case when d.PLSNSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLSNSS_broadcast_days_viewedNon_Live is null then 0  when e.PLSNSS_days_right_viewableNon_Live =0 then 0 when e.PLSNSS_days_right_broadcastNon_Live=0 then 0  else d.PLSNSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSNSS_SOV_Sky_Sports_N
,case when d.PLS4SS_broadcast_days_viewedNon_Live=0 then 0  when d.PLS4SS_broadcast_days_viewedNon_Live is null then 0  when e.PLS4SS_days_right_viewableNon_Live =0 then 0 when e.PLS4SS_days_right_broadcastNon_Live=0 then 0  else d.PLS4SS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLS4SS_SOV_Sky_Sports_N
,case when d.PLSULSS_broadcast_days_viewedNon_Live=0 then 0  when d.PLSULSS_broadcast_days_viewedNon_Live is null then 0  when e.PLSULSS_days_right_viewableNon_Live =0 then 0 when e.PLSULSS_days_right_broadcastNon_Live=0 then 0  else d.PLSULSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PLSULSS_SOV_Sky_Sports_N
,case when d.PRUSS_broadcast_days_viewedNon_Live=0 then 0  when d.PRUSS_broadcast_days_viewedNon_Live is null then 0  when e.PRUSS_days_right_viewableNon_Live =0 then 0 when e.PRUSS_days_right_broadcastNon_Live=0 then 0  else d.PRUSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_PRUSS_SOV_Sky_Sports_N
,case when d.ROISS_broadcast_days_viewedNon_Live=0 then 0  when d.ROISS_broadcast_days_viewedNon_Live is null then 0  when e.ROISS_days_right_viewableNon_Live =0 then 0 when e.ROISS_days_right_broadcastNon_Live=0 then 0  else d.ROISS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ROISS_SOV_Sky_Sports_N
,case when d.RLGSS_broadcast_days_viewedNon_Live=0 then 0  when d.RLGSS_broadcast_days_viewedNon_Live is null then 0  when e.RLGSS_days_right_viewableNon_Live =0 then 0 when e.RLGSS_days_right_broadcastNon_Live=0 then 0  else d.RLGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RLGSS_SOV_Sky_Sports_N
,case when d.SARUSS_broadcast_days_viewedNon_Live=0 then 0  when d.SARUSS_broadcast_days_viewedNon_Live is null then 0  when e.SARUSS_days_right_viewableNon_Live =0 then 0 when e.SARUSS_days_right_broadcastNon_Live=0 then 0  else d.SARUSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SARUSS_SOV_Sky_Sports_N
,case when d.SFASS_broadcast_days_viewedNon_Live=0 then 0  when d.SFASS_broadcast_days_viewedNon_Live is null then 0  when e.SFASS_days_right_viewableNon_Live =0 then 0 when e.SFASS_days_right_broadcastNon_Live=0 then 0  else d.SFASS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SFASS_SOV_Sky_Sports_N
,case when d.AMSS_broadcast_days_viewedNon_Live=0 then 0  when d.AMSS_broadcast_days_viewedNon_Live is null then 0  when e.AMSS_days_right_viewableNon_Live =0 then 0 when e.AMSS_days_right_broadcastNon_Live=0 then 0  else d.AMSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_AMSS_SOV_Sky_Sports_N
,case when d.ATHSS_broadcast_days_viewedNon_Live=0 then 0  when d.ATHSS_broadcast_days_viewedNon_Live is null then 0  when e.ATHSS_days_right_viewableNon_Live =0 then 0 when e.ATHSS_days_right_broadcastNon_Live=0 then 0  else d.ATHSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_ATHSS_SOV_Sky_Sports_N
,case when d.BASESS_broadcast_days_viewedNon_Live=0 then 0  when d.BASESS_broadcast_days_viewedNon_Live is null then 0  when e.BASESS_days_right_viewableNon_Live =0 then 0 when e.BASESS_days_right_broadcastNon_Live=0 then 0  else d.BASESS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASESS_SOV_Sky_Sports_N
,case when d.BASKSS_broadcast_days_viewedNon_Live=0 then 0  when d.BASKSS_broadcast_days_viewedNon_Live is null then 0  when e.BASKSS_days_right_viewableNon_Live =0 then 0 when e.BASKSS_days_right_broadcastNon_Live=0 then 0  else d.BASKSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BASKSS_SOV_Sky_Sports_N
,case when d.BOXSS_broadcast_days_viewedNon_Live=0 then 0  when d.BOXSS_broadcast_days_viewedNon_Live is null then 0  when e.BOXSS_days_right_viewableNon_Live =0 then 0 when e.BOXSS_days_right_broadcastNon_Live=0 then 0  else d.BOXSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_BOXSS_SOV_Sky_Sports_N
,case when d.CRISS_broadcast_days_viewedNon_Live=0 then 0  when d.CRISS_broadcast_days_viewedNon_Live is null then 0  when e.CRISS_days_right_viewableNon_Live =0 then 0 when e.CRISS_days_right_broadcastNon_Live=0 then 0  else d.CRISS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CRISS_SOV_Sky_Sports_N
,case when d.DARTSS_broadcast_days_viewedNon_Live=0 then 0  when d.DARTSS_broadcast_days_viewedNon_Live is null then 0  when e.DARTSS_days_right_viewableNon_Live =0 then 0 when e.DARTSS_days_right_broadcastNon_Live=0 then 0  else d.DARTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_DARTSS_SOV_Sky_Sports_N
,case when d.EQUSS_broadcast_days_viewedNon_Live=0 then 0  when d.EQUSS_broadcast_days_viewedNon_Live is null then 0  when e.EQUSS_days_right_viewableNon_Live =0 then 0 when e.EQUSS_days_right_broadcastNon_Live=0 then 0  else d.EQUSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EQUSS_SOV_Sky_Sports_N
,case when d.EXTSS_broadcast_days_viewedNon_Live=0 then 0  when d.EXTSS_broadcast_days_viewedNon_Live is null then 0  when e.EXTSS_days_right_viewableNon_Live =0 then 0 when e.EXTSS_days_right_broadcastNon_Live=0 then 0  else d.EXTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_EXTSS_SOV_Sky_Sports_N
,case when d.FISHSS_broadcast_days_viewedNon_Live=0 then 0  when d.FISHSS_broadcast_days_viewedNon_Live is null then 0  when e.FISHSS_days_right_viewableNon_Live =0 then 0 when e.FISHSS_days_right_broadcastNon_Live=0 then 0  else d.FISHSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FISHSS_SOV_Sky_Sports_N
,case when d.FOOTSS_broadcast_days_viewedNon_Live=0 then 0  when d.FOOTSS_broadcast_days_viewedNon_Live is null then 0  when e.FOOTSS_days_right_viewableNon_Live =0 then 0 when e.FOOTSS_days_right_broadcastNon_Live=0 then 0  else d.FOOTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_FOOTSS_SOV_Sky_Sports_N
,case when d.GOLFSS_broadcast_days_viewedNon_Live=0 then 0  when d.GOLFSS_broadcast_days_viewedNon_Live is null then 0  when e.GOLFSS_days_right_viewableNon_Live =0 then 0 when e.GOLFSS_days_right_broadcastNon_Live=0 then 0  else d.GOLFSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_GOLFSS_SOV_Sky_Sports_N
,case when d.IHSS_broadcast_days_viewedNon_Live=0 then 0  when d.IHSS_broadcast_days_viewedNon_Live is null then 0  when e.IHSS_days_right_viewableNon_Live =0 then 0 when e.IHSS_days_right_broadcastNon_Live=0 then 0  else d.IHSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_IHSS_SOV_Sky_Sports_N
,case when d.MSPSS_broadcast_days_viewedNon_Live=0 then 0  when d.MSPSS_broadcast_days_viewedNon_Live is null then 0  when e.MSPSS_days_right_viewableNon_Live =0 then 0 when e.MSPSS_days_right_broadcastNon_Live=0 then 0  else d.MSPSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_MSPSS_SOV_Sky_Sports_N
,case when d.RACSS_broadcast_days_viewedNon_Live=0 then 0  when d.RACSS_broadcast_days_viewedNon_Live is null then 0  when e.RACSS_days_right_viewableNon_Live =0 then 0 when e.RACSS_days_right_broadcastNon_Live=0 then 0  else d.RACSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RACSS_SOV_Sky_Sports_N
,case when d.RUGSS_broadcast_days_viewedNon_Live=0 then 0  when d.RUGSS_broadcast_days_viewedNon_Live is null then 0  when e.RUGSS_days_right_viewableNon_Live =0 then 0 when e.RUGSS_days_right_broadcastNon_Live=0 then 0  else d.RUGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_RUGSS_SOV_Sky_Sports_N
,case when d.SNPSS_broadcast_days_viewedNon_Live=0 then 0  when d.SNPSS_broadcast_days_viewedNon_Live is null then 0  when e.SNPSS_days_right_viewableNon_Live =0 then 0 when e.SNPSS_days_right_broadcastNon_Live=0 then 0  else d.SNPSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SNPSS_SOV_Sky_Sports_N
,case when d.TENSS_broadcast_days_viewedNon_Live=0 then 0  when d.TENSS_broadcast_days_viewedNon_Live is null then 0  when e.TENSS_days_right_viewableNon_Live =0 then 0 when e.TENSS_days_right_broadcastNon_Live=0 then 0  else d.TENSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_TENSS_SOV_Sky_Sports_N
,case when d.UNKSS_broadcast_days_viewedNon_Live=0 then 0  when d.UNKSS_broadcast_days_viewedNon_Live is null then 0  when e.UNKSS_days_right_viewableNon_Live =0 then 0 when e.UNKSS_days_right_broadcastNon_Live=0 then 0  else d.UNKSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_UNKSS_SOV_Sky_Sports_N
,case when d.WATSS_broadcast_days_viewedNon_Live=0 then 0  when d.WATSS_broadcast_days_viewedNon_Live is null then 0  when e.WATSS_days_right_viewableNon_Live =0 then 0 when e.WATSS_days_right_broadcastNon_Live=0 then 0  else d.WATSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WATSS_SOV_Sky_Sports_N
,case when d.WINSS_broadcast_days_viewedNon_Live=0 then 0  when d.WINSS_broadcast_days_viewedNon_Live is null then 0  when e.WINSS_days_right_viewableNon_Live =0 then 0 when e.WINSS_days_right_broadcastNon_Live=0 then 0  else d.WINSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WINSS_SOV_Sky_Sports_N
,case when d.WRESS_broadcast_days_viewedNon_Live=0 then 0  when d.WRESS_broadcast_days_viewedNon_Live is null then 0  when e.WRESS_days_right_viewableNon_Live =0 then 0 when e.WRESS_days_right_broadcastNon_Live=0 then 0  else d.WRESS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WRESS_SOV_Sky_Sports_N
,case when d.SOLSS_broadcast_days_viewedNon_Live=0 then 0  when d.SOLSS_broadcast_days_viewedNon_Live is null then 0  when e.SOLSS_days_right_viewableNon_Live =0 then 0 when e.SOLSS_days_right_broadcastNon_Live=0 then 0  else d.SOLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SOLSS_SOV_Sky_Sports_N
,case when d.SACSS_broadcast_days_viewedNon_Live=0 then 0  when d.SACSS_broadcast_days_viewedNon_Live is null then 0  when e.SACSS_days_right_viewableNon_Live =0 then 0 when e.SACSS_days_right_broadcastNon_Live=0 then 0  else d.SACSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SACSS_SOV_Sky_Sports_N
,case when d.SPFSS_broadcast_days_viewedNon_Live=0 then 0  when d.SPFSS_broadcast_days_viewedNon_Live is null then 0  when e.SPFSS_days_right_viewableNon_Live =0 then 0 when e.SPFSS_days_right_broadcastNon_Live=0 then 0  else d.SPFSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPFSS_SOV_Sky_Sports_N
,case when d.SPLSS_broadcast_days_viewedNon_Live=0 then 0  when d.SPLSS_broadcast_days_viewedNon_Live is null then 0  when e.SPLSS_days_right_viewableNon_Live =0 then 0 when e.SPLSS_days_right_broadcastNon_Live=0 then 0  else d.SPLSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SPLSS_SOV_Sky_Sports_N
,case when d.SP5SS_broadcast_days_viewedNon_Live=0 then 0  when d.SP5SS_broadcast_days_viewedNon_Live is null then 0  when e.SP5SS_days_right_viewableNon_Live =0 then 0 when e.SP5SS_days_right_broadcastNon_Live=0 then 0  else d.SP5SS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_SP5SS_SOV_Sky_Sports_N
,case when d.USMGSS_broadcast_days_viewedNon_Live=0 then 0  when d.USMGSS_broadcast_days_viewedNon_Live is null then 0  when e.USMGSS_days_right_viewableNon_Live =0 then 0 when e.USMGSS_days_right_broadcastNon_Live=0 then 0  else d.USMGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USMGSS_SOV_Sky_Sports_N
,case when d.USOTSS_broadcast_days_viewedNon_Live=0 then 0  when d.USOTSS_broadcast_days_viewedNon_Live is null then 0  when e.USOTSS_days_right_viewableNon_Live =0 then 0 when e.USOTSS_days_right_broadcastNon_Live=0 then 0  else d.USOTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOTSS_SOV_Sky_Sports_N
,case when d.USOGSS_broadcast_days_viewedNon_Live=0 then 0  when d.USOGSS_broadcast_days_viewedNon_Live is null then 0  when e.USOGSS_days_right_viewableNon_Live =0 then 0 when e.USOGSS_days_right_broadcastNon_Live=0 then 0  else d.USOGSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USOGSS_SOV_Sky_Sports_N
,case when d.CLASS_broadcast_days_viewedNon_Live=0 then 0  when d.CLASS_broadcast_days_viewedNon_Live is null then 0  when e.CLASS_days_right_viewableNon_Live =0 then 0 when e.CLASS_days_right_broadcastNon_Live=0 then 0  else d.CLASS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLASS_SOV_Sky_Sports_N
,case when d.CLNSS_broadcast_days_viewedNon_Live=0 then 0  when d.CLNSS_broadcast_days_viewedNon_Live is null then 0  when e.CLNSS_days_right_viewableNon_Live =0 then 0 when e.CLNSS_days_right_broadcastNon_Live=0 then 0  else d.CLNSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLNSS_SOV_Sky_Sports_N
,case when d.CLOSS_broadcast_days_viewedNon_Live=0 then 0  when d.CLOSS_broadcast_days_viewedNon_Live is null then 0  when e.CLOSS_days_right_viewableNon_Live =0 then 0 when e.CLOSS_days_right_broadcastNon_Live=0 then 0  else d.CLOSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLOSS_SOV_Sky_Sports_N
,case when d.CLTSS_broadcast_days_viewedNon_Live=0 then 0  when d.CLTSS_broadcast_days_viewedNon_Live is null then 0  when e.CLTSS_days_right_viewableNon_Live =0 then 0 when e.CLTSS_days_right_broadcastNon_Live=0 then 0  else d.CLTSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLTSS_SOV_Sky_Sports_N
,case when d.CLWSS_broadcast_days_viewedNon_Live=0 then 0  when d.CLWSS_broadcast_days_viewedNon_Live is null then 0  when e.CLWSS_days_right_viewableNon_Live =0 then 0 when e.CLWSS_days_right_broadcastNon_Live=0 then 0  else d.CLWSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_CLWSS_SOV_Sky_Sports_N
,case when d.USPGASS_broadcast_days_viewedNon_Live=0 then 0  when d.USPGASS_broadcast_days_viewedNon_Live is null then 0  when e.USPGASS_days_right_viewableNon_Live =0 then 0 when e.USPGASS_days_right_broadcastNon_Live=0 then 0  else d.USPGASS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_USPGASS_SOV_Sky_Sports_N
,case when d.WIFSS_broadcast_days_viewedNon_Live=0 then 0  when d.WIFSS_broadcast_days_viewedNon_Live is null then 0  when e.WIFSS_days_right_viewableNon_Live =0 then 0 when e.WIFSS_days_right_broadcastNon_Live=0 then 0  else d.WIFSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WIFSS_SOV_Sky_Sports_N
,case when d.WICSS_broadcast_days_viewedNon_Live=0 then 0  when d.WICSS_broadcast_days_viewedNon_Live is null then 0  when e.WICSS_days_right_viewableNon_Live =0 then 0 when e.WICSS_days_right_broadcastNon_Live=0 then 0  else d.WICSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICSS_SOV_Sky_Sports_N
,case when d.WICCSS_broadcast_days_viewedNon_Live=0 then 0  when d.WICCSS_broadcast_days_viewedNon_Live is null then 0  when e.WICCSS_days_right_viewableNon_Live =0 then 0 when e.WICCSS_days_right_broadcastNon_Live=0 then 0  else d.WICCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WICCSS_SOV_Sky_Sports_N
,case when d.WDCSS_broadcast_days_viewedNon_Live=0 then 0  when d.WDCSS_broadcast_days_viewedNon_Live is null then 0  when e.WDCSS_days_right_viewableNon_Live =0 then 0 when e.WDCSS_days_right_broadcastNon_Live=0 then 0  else d.WDCSS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WDCSS_SOV_Sky_Sports_N
,case when d.WWESS_broadcast_days_viewedNon_Live=0 then 0  when d.WWESS_broadcast_days_viewedNon_Live is null then 0  when e.WWESS_days_right_viewableNon_Live =0 then 0 when e.WWESS_days_right_broadcastNon_Live=0 then 0  else d.WWESS_total_seconds_viewedNon_Live / cast(a.total_viewing_duration_sky_sports as real )end as annualised_WWESS_SOV_Sky_Sports_N


into dbarnett.v250_annualised_activity_table_analysis_metrics_SOV_SKY_SPORTS
---Master Table
from dbarnett.v250_master_account_list as a

--Overall Actual Viewing
left outer join dbarnett.v250_unannualised_right_activity as b
on a.account_number = b.account_number

--Overall Days Broadcast Watchable--
left outer join dbarnett.v250_right_viewable_account_summary as c
on a.account_number = c.account_number



--Live/Non Live Broadcast Actual Viewing
left outer join dbarnett.v250_unannualised_right_activity_by_live_NON_LIVE as d
on a.account_number = d.account_number

--Live/Non Live Days Broadcast and Watchable
left outer join dbarnett.v250_right_viewable_account_summary_by_live_status as e
on a.account_number = e.account_number

where total_days_with_viewing>=280 and total_viewing_duration_sports >0

;
commit;

grant all on dbarnett.v250_annualised_activity_table_analysis_metrics_SOV_SKY_SPORTS to public;
commit;
