CREATE OR REPLACE VIEW pitteloudj.cs_rental_2 AS
SELECT cs_rentals_binned_smpl.account_number
	, cs_rentals_binned_smpl.Age
	, cs_rentals_binned_smpl.BB_3rdParty_PL_Entry_Last_3Yr_b
	, cs_rentals_binned_smpl.BB_Active
	, cs_rentals_binned_smpl.BB_Churns_Last_1Yr_b
	, cs_rentals_binned_smpl.BB_Churns_Last_3Yr_b
	, cs_rentals_binned_smpl.BB_contract_segment
	, cs_rentals_binned_smpl.BB_CusCan_PL_Entry_Ever_b
	, cs_rentals_binned_smpl.BB_HomeMove_PL_Entry_Ever_b
	, cs_rentals_binned_smpl.BB_Last_Activation
	, cs_rentals_binned_smpl.bb_last_tenure
	, cs_rentals_binned_smpl.BB_Product_Holding
	, cs_rentals_binned_smpl.BB_Provider
	, cs_rentals_binned_smpl.BB_SysCan_PL_Entry_Last_3Yr_b
	, cs_rentals_binned_smpl.Broadband_Average_Demand
	, cs_rentals_binned_smpl.Curr_Offer_Actual_End_DTV
	, cs_rentals_binned_smpl.Curr_Offer_Amount_DTV_b
	, cs_rentals_binned_smpl.Curr_Offer_Amount_DTV_flag
	, cs_rentals_binned_smpl.Curr_Offer_Length_DTV_b
	, cs_rentals_binned_smpl.Curr_Offer_Start_DTV
	, cs_rentals_binned_smpl.DTV_1st_Activation
	, cs_rentals_binned_smpl.dtv_1st_tenure
	, cs_rentals_binned_smpl.DTV_Active_Blocks_Last_1Yr_b
	, cs_rentals_binned_smpl.DTV_Active_Blocks_Last_5Yr_b
	, cs_rentals_binned_smpl.DTV_contract_segment
	, cs_rentals_binned_smpl.DTV_Curr_Contract_Intended_End
	, cs_rentals_binned_smpl.DTV_Curr_Contract_Start
	, cs_rentals_binned_smpl.DTV_CusCan_Churns_Ever
	, cs_rentals_binned_smpl.DTV_Last_Activation
	, cs_rentals_binned_smpl.DTV_Last_Active_Block
	, cs_rentals_binned_smpl.DTV_Last_cuscan_churn
	, cs_rentals_binned_smpl.DTV_Last_Pending_Cancel
	, cs_rentals_binned_smpl.DTV_Last_SysCan_Churn
	, cs_rentals_binned_smpl.dtv_last_tenure
	, cs_rentals_binned_smpl.Dtv_Package
	, cs_rentals_binned_smpl.DTV_Pending_cancels_ever
	, cs_rentals_binned_smpl.DTV_Pending_Cancels_Last_1Yr_b
	, cs_rentals_binned_smpl.DTV_Pending_Cancels_Last_3Yr_b
	, cs_rentals_binned_smpl.DTV_PO_Cancellations_Last_5Yr_b
	, cs_rentals_binned_smpl.DTV_Product_Holding
	, cs_rentals_binned_smpl.DTV_product_holding_recode
	, cs_rentals_binned_smpl.Exchange_Status
	, cs_rentals_binned_smpl.financial_strategy
	, cs_rentals_binned_smpl.h_family_lifestage
	, cs_rentals_binned_smpl.h_household_composition
	, cs_rentals_binned_smpl.h_income_value
	, cs_rentals_binned_smpl.h_mosaic_group
	, cs_rentals_binned_smpl.h_number_of_adults_b
	, cs_rentals_binned_smpl.h_number_of_bedrooms_b
	, cs_rentals_binned_smpl.h_number_of_children_in_house_b
	, cs_rentals_binned_smpl.h_presence_of_child_aged_0_4
	, cs_rentals_binned_smpl.h_presence_of_child_aged_12_17
	, cs_rentals_binned_smpl.h_presence_of_child_aged_5_11
	, cs_rentals_binned_smpl.h_presence_of_young_person_at_ad
	, cs_rentals_binned_smpl.h_property_type
	, cs_rentals_binned_smpl.h_residence_type
	, cs_rentals_binned_smpl.Home_Owner_Status
	, cs_rentals_binned_smpl.last_TA_b
	, cs_rentals_binned_smpl.last_TA_nonsave_b
	, cs_rentals_binned_smpl.last_TA_reason_flag
	, cs_rentals_binned_smpl.last_TA_save_b
	, cs_rentals_binned_smpl.Offers_Applied_Lst_12M_DTV_b
	, cs_rentals_binned_smpl.Offers_Applied_Lst_36M_DTV_b
	, cs_rentals_binned_smpl.Offers_Applied_Lst_90D_DTV_b
	, cs_rentals_binned_smpl.p_true_touch_group
	, cs_rentals_binned_smpl.p_true_touch_type
	, cs_rentals_binned_smpl.Prev_Offer_Amount_DTV
	, cs_rentals_binned_smpl.Prev_Offer_Amount_DTV_b
	, cs_rentals_binned_smpl.Prev_Offer_Amount_DTV_flag
	, cs_rentals_binned_smpl.Prev_Offer_Length_DTV_b
	, cs_rentals_binned_smpl.skyfibre_enabled
	, cs_rentals_binned_smpl.skyfibre_enabled_perc
	, cs_rentals_binned_smpl.Superfast_Available_End_2016
	, cs_rentals_binned_smpl.Superfast_Available_End_2017
	, cs_rentals_binned_smpl.TA_nonsaves_in_last_12m_b
	, cs_rentals_binned_smpl.TA_nonsaves_in_last_36m_b
	, cs_rentals_binned_smpl.TA_saves_in_last_12m_b
	, cs_rentals_binned_smpl.TA_saves_in_last_36m_b
	, cs_rentals_binned_smpl.TA_saves_in_last_90d_b
	, cs_rentals_binned_smpl.TAs_in_last_60d_b
	, cs_rentals_binned_smpl.Throughput_Speed
	, cs_rentals_binned_smpl.UP_rental
	, cs_rentals_binned_smpl.OD_Last_3M
	, cs_rentals_binned_smpl.OD_Last_12M
	, cs_rentals_binned_smpl.OD_Months_since_Last
	, cs_rentals_binned_smpl.MS_Active
	, cs_rentals_binned_smpl.MS_Product_Holding
	, cs_rentals_binned_smpl.SGE_Active
	, cs_rentals_binned_smpl.SGE_Product_Holding
FROM cs_rentals_binned_smpl
WHERE substring(cs_rentals_binned_smpl.account_number, 6, 1) IN ('4', '7')
