/* Combining all data into one table */

-- Table_1 --BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_2012_06_01_07

select * into BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_2012_06_01_07 from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_01
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_02
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_03
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_04
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_05
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_06
union all
select * from BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_07
--40657 Row(s) affected
select Date_valid_for_DB1, count(*) from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_2012_06_01_07
group by Date_valid_for_DB1
#
--Table_2 --select top 10* from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_2012_06_01_07

select * into BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_2012_06_01_07 from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_01
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_02
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_03
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_04
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_05
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_06
union all
select * from BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_07
--97,293 Row(s) affected

select Date_of_Activity_DB1, count(*) from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_06 group by Date_of_Activity_DB1
--Table_3 --BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_2012_06_01_07

select * into BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_2012_06_01_07 from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_01
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_02
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_03
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_04
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_05
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_06
union all
select * from BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_07

--853,833 Row(s) affected

--Table_4 --BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_2012_06_01_07

select * into BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_2012_06_01_07 from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_01
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_02
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_03
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_04
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_05
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_06
union all
select * from BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_07

--68,613 Row(s) affected

--Table_5 -- BARB_VIEWING_RECORD_PANEL_GUESTS_2012_06_01_07

select * into BARB_VIEWING_RECORD_PANEL_GUESTS_2012_06_01_07 from BARB_VIEWING_RECORD_PANEL_GUESTS_01
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_02
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_03
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_04
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_05
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_06
union all
select * from BARB_VIEWING_RECORD_PANEL_GUESTS_07

--54,188 Row(s) affected

--Table_6 -- BARB_VIEWING_RECORD_PANEL_MEMBERS_2012_06_01_07

select * into BARB_VIEWING_RECORD_PANEL_MEMBERS_2012_06_01_07 from BARB_VIEWING_RECORD_PANEL_MEMBERS_01
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_02
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_03
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_04
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_05
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_06
union all
select * from BARB_VIEWING_RECORD_PANEL_MEMBERS_07

--830,257 Row(s) affected

grant all on BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_2012_06_01_07 to limac;
grant all on BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_2012_06_01_07 to limac;
grant all on BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_2012_06_01_07 to limac;
grant all on BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_2012_06_01_07 to limac;
grant all on BARB_VIEWING_RECORD_PANEL_GUESTS_2012_06_01_07 to limac;
grant all on BARB_VIEWING_RECORD_PANEL_MEMBERS_2012_06_01_07 to limac;
commit;


grant all on BARB_PANEL_VIEWING_FILE_HOME_CHARACTERISTICS_2012_06_01_07 to thompsonja;
grant all on BARB_VIEWING_FILE_INDIVIDUAL_PANEL_MEMBER_DETAILS_2012_06_01_07 to thompsonja;
grant all on BARB_PANEL_VIEWING_FILE_RESPONSE_WEIGHT_VIEWING_CATEGORY_2012_06_01_07 to thompsonja;
grant all on BARB_PANEL_VIEWING_FILE_TV_SET_CHARACTERISTICS_2012_06_01_07 to thompsonja;
grant all on BARB_VIEWING_RECORD_PANEL_GUESTS_2012_06_01_07 to thompsonja;
grant all on BARB_VIEWING_RECORD_PANEL_MEMBERS_2012_06_01_07 to thompsonja;
commit;



