create PROCEDURE BARB_MASTER_FILE_IMPORT (@in_filename varchar(60)) AS

-- Martin Neighbours
-- 19/9/12

-- BARB MASTER file.  Note that this is only for the import of the original file
-- This will clear down all files and replace with new, no log files required

BEGIN


DECLARE @file_creation_date date
DECLARE @file_creation_time time
DECLARE @file_type  varchar(12)
DECLARE @File_Version Int
DECLARE @audit_row_count bigint
DECLARE @query varchar(3000)
DECLARE @filename varchar(13)

-- clear down the data first

DELETE FROM MN_BARB_import
DELETE FROM BARB_MASTER_FILE_DB1_STATIONS_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_DB2_STATIONS_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_LOG_STATIONS_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_LOG_STATION_RELATIONSHIP_TO_DB1_RECORD
DELETE FROM BARB_MASTER_FILE_SPLIT_STATIONS_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_PANEL_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_MACRO_PANEL_RELATIONSHIP_RECORD
DELETE FROM BARB_MASTER_FILE_DB2_PANEL_STATIONS_REPORTING_RECORD
DELETE FROM BARB_MASTER_FILE_SALES_HOUSE_RECORD
DELETE FROM BARB_MASTER_FILE_BROADCAST_GROUP_RECORD
DELETE FROM BARB_MASTER_FILE_AUDIENCE_CATEGORY_RECORD
DELETE FROM BARB_MASTER_FILE_COMMERCIAL_LENGTH_RATE_FACTORS_RECORD

-- import the raw data as a string
SET @query = 'LOAD TABLE MN_BARB_import (imported_text '
SET @query = @query || ' ''\n'' ) '
SET @query = @query || ' FROM ''/ETL013/prod/sky/olive/data/share/clarityq/export/' || @in_filename || ''' QUOTES OFF ESCAPES OFF NOTIFY 1000'

EXECUTE (@query)

SET @audit_row_count = (Select count(1) from MN_BARB_IMPORT)

-- file doesn't exist

IF @audit_row_count = 0
BEGIN
        SELECT now(), @file_creation_Date, @file_creation_time, @file_type, @file_version, @filename,'File not found ' || @in_filename, @audit_row_count

        RETURN
END

-- parse out the data records


SET @file_creation_date = (SELECT CAST(substr(imported_text,7,8) AS Date)
                                FROM MN_BARB_import
                                WHERE substr(imported_text,1,2) = '01')

SET @file_creation_time = (SELECT CAST(substr(imported_text,15,2) || ':' || substr(imported_text,17,2) || ':' || substr(imported_text,19,2)  AS Time)
                                FROM MN_BARB_import
                                WHERE substr(imported_text,1,2) = '01')

SET @file_type = (SELECT substr(imported_text,21,12)
                                FROM MN_BARB_import
                                WHERE substr(imported_text,1,2) = '01')

SET @File_Version = (SELECT CAST(substr(imported_text,33,3) AS Int)
                                FROM MN_BARB_import
                                WHERE substr(imported_text,1,2) = '01')

SET @Filename = (SELECT substr(imported_text,36,13)
                                FROM MN_BARB_import
                                WHERE substr(imported_text,1,2) = '01')

-- wrong format

IF @file_type <> 'DSP14.V03.02'
BEGIN

        SELECT now(), @file_creation_Date, @file_creation_time, @file_type, @file_version, @filename,'File type DSP10.V03.03, file type imported ' || @file_type, 0

        RETURN
END


        INSERT INTO BARB_MASTER_FILE_DB1_STATIONS_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                DB1_Station_Code,
                DB2_Station_Code,
                DB1_Station_Name,
                DB1_Station_Medium_Name,
                DB1_Station_Short_Name,
                Exclude_from_Total_TV,
                Exclude_from_Commercial_TV,
                Area_Geography,
                Area_Flags,
                Transmission_Format,
                Reporting_Start_Date,
                Reporting_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS DB1_Station_Code,
                CAST(substr(imported_text,8,5) AS Int) AS DB2_Station_Code,
                substr(imported_text,13,30) AS DB1_Station_Name,
                substr(imported_text,43,15) AS DB1_Station_Medium_Name,
                substr(imported_text,58,8) AS DB1_Station_Short_Name,
                substr(imported_text,66,1) AS Exclude_from_Total_TV,
                substr(imported_text,67,1) AS Exclude_from_Commercial_TV,
                CAST(substr(imported_text,68,1) AS Int) AS Area_Geography,
                substr(imported_text,69,4) AS Area_Flags,
                CAST(substr(imported_text,73,1) AS Int) AS Transmission_Format,
                CAST(substr(imported_text,74,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,82,8) AS Date) AS Reporting_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '02'

       INSERT INTO BARB_MASTER_FILE_DB2_STATIONS_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                DB2_Station_Code,
                DB2_Station_Name,
                DB2_Station_Short_Name,
                DB2_Station_15_Char_Name,
                DB2_Station_Code_of_Parent_channel,
                Staggercast_Delay_Minutes,
                Reporting_Start_Date,
                Reporting_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS DB2_Station_Code,
                substr(imported_text,8,30) AS DB2_Station_Name,
                substr(imported_text,38,8) AS DB2_Station_Short_Name,
                substr(imported_text,46,15) AS DB2_Station_15_Char_Name,
                CAST(substr(imported_text,61,5) AS Int) AS DB2_Station_Code_of_Parent_channel,
                CAST(substr(imported_text,66,4) AS Int) AS Staggercast_Delay_Minutes,
                CAST(substr(imported_text,70,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,78,8) AS Date) AS Reporting_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '03'

      INSERT INTO BARB_MASTER_FILE_LOG_STATIONS_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Log_Station_Code,
                DB2_Station_Code,
                Log_Station_Name,
                Log_Station_Short_Name,
                Log_Station_15_Char_Name,
                Area_Geography,
                Area_Flags,
                Primary_Reporting_Panel_Code,
                Reporting_Start_Date,
                Reporting_End_Date,
                Sales_House_1,
                Sales_House_2,
                Sales_House_3,
                Sales_House_4,
                Sales_House_5,
                Sales_House_6,
                Broadcast_Group_Id,
                Station_Genre_Type)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Log_Station_Code,
                CAST(substr(imported_text,8,5) AS Int) AS DB2_Station_Code,
                substr(imported_text,13,30) AS Log_Station_Name,
                substr(imported_text,43,8) AS Log_Station_Short_Name,
                substr(imported_text,51,15) AS Log_Station_15_Char_Name,
                CAST(substr(imported_text,66,1) AS Int) AS Area_Geography,
                substr(imported_text,67,4) AS Area_Flags,
                CAST(substr(imported_text,71,5) AS Int) AS Primary_Reporting_Panel_Code,
                CAST(substr(imported_text,76,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,84,8) AS Date) AS Reporting_End_Date,
                CAST(substr(imported_text,92,5) AS Int) AS Sales_House_1,
                CAST(substr(imported_text,97,5) AS Int) AS Sales_House_2,
                CAST(substr(imported_text,102,5) AS Int) AS Sales_House_3,
                CAST(substr(imported_text,107,5) AS Int) AS Sales_House_4,
                CAST(substr(imported_text,112,5) AS Int) AS Sales_House_5,
                CAST(substr(imported_text,117,5) AS Int) AS Sales_House_6,
                CAST(substr(imported_text,122,5) AS Int) AS Broadcast_Group_Id,
                substr(imported_text,127,5) AS Station_Genre_Type
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '04'

      INSERT INTO BARB_MASTER_FILE_LOG_STATION_RELATIONSHIP_TO_DB1_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Log_Station_Code,
                DB1_Station_Code,
                Relationship_Start_Date,
                Relationship_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Log_Station_Code,
                CAST(substr(imported_text,8,5) AS Int) AS DB1_Station_Code,
                CAST(substr(imported_text,13,8) AS Date) AS Relationship_Start_Date,
                CAST(substr(imported_text,21,8) AS Date) AS Relationship_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '05'

      INSERT INTO BARB_MASTER_FILE_SPLIT_STATIONS_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Log_Station_Code,
                Split_Transmission_Indicator,
                Split_Station_Name,
                Split_Station_Short_Name,
                Split_Station_15_Char_Name,
                Split_Area_Factor,
                Reporting_Start_Date,
                Reporting_End_Date,
                Panel_Code)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Log_Station_Code,
                CAST(substr(imported_text,8,2) AS Int) AS Split_Transmission_Indicator,
                substr(imported_text,10,30) AS Split_Station_Name,
                substr(imported_text,40,8) AS Split_Station_Short_Name,
                substr(imported_text,48,15) AS Split_Station_15_Char_Name,
                CAST(substr(imported_text,63,6) AS Int) AS Split_Area_Factor,
                CAST(substr(imported_text,69,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,77,8) AS Date) AS Reporting_End_Date,
                CAST(substr(imported_text,85,5) AS Int) AS Panel_Code
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '06'

      INSERT INTO BARB_MASTER_FILE_PANEL_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Panel_Code,
                Panel_Name,
                Panel_Medium_Name,
                Panel_Short_Name,
                Macro_region,
                Used_in_DB2,
                Panel_Start_Date,
                Panel_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Panel_Code,
                substr(imported_text,8,30) AS Panel_Name,
                substr(imported_text,38,15) AS Panel_Medium_Name,
                substr(imported_text,53,8) AS Panel_Short_Name,
                substr(imported_text,61,1) AS Macro_region,
                substr(imported_text,62,1) AS Used_in_DB2,
                CAST(substr(imported_text,63,8) AS Date) AS Panel_Start_Date,
                CAST(substr(imported_text,71,8) AS Date) AS Panel_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '07'

      INSERT INTO BARB_MASTER_FILE_MACRO_PANEL_RELATIONSHIP_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Macro_Panel_Code,
                DB1_Panel_Code,
                Relationship_Start_Date,
                Relationship_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Macro_Panel_Code,
                CAST(substr(imported_text,8,5) AS Int) AS DB1_Panel_Code,
                CAST(substr(imported_text,13,8) AS Date) AS Relationship_Start_Date,
                CAST(substr(imported_text,21,8) AS Date) AS Relationship_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '08'

      INSERT INTO BARB_MASTER_FILE_DB2_PANEL_STATIONS_REPORTING_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Reporting_Panel_Code,
                DB2_Station_Code,
                Log_Station_Code,
                Reporting_Start_Date,
                Reporting_End_Date,
                Reported_in_IBT,
                Reported_in_Programme_file,
                Reported_in_Spots_file,
                Reported_in_Breaks_file,
                Reported_in_Sponsorship_file)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Reporting_Panel_Code,
                CAST(substr(imported_text,8,5) AS Int) AS DB2_Station_Code,
                CAST(substr(imported_text,13,5) AS Int) AS Log_Station_Code,
                CAST(substr(imported_text,18,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,26,8) AS Date) AS Reporting_End_Date,
                substr(imported_text,34,1) AS Reported_in_IBT,
                substr(imported_text,35,1) AS Reported_in_Programme_file,
                substr(imported_text,36,1) AS Reported_in_Spots_file,
                substr(imported_text,37,1) AS Reported_in_Breaks_file,
                substr(imported_text,38,1) AS Reported_in_Sponsorship_file
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '09'

      INSERT INTO BARB_MASTER_FILE_SALES_HOUSE_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Sales_House_Identifier,
                Sales_House_Name,
                Sales_House_Short_Name,
                Sales_House_15_Char_Name,
                Reporting_Start_Date,
                Reporting_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Sales_House_Identifier,
                substr(imported_text,8,30) AS Sales_House_Name,
                substr(imported_text,38,8) AS Sales_House_Short_Name,
                substr(imported_text,46,15) AS Sales_House_15_Char_Name,
                CAST(substr(imported_text,61,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,69,8) AS Date) AS Reporting_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '10'


      INSERT INTO BARB_MASTER_FILE_BROADCAST_GROUP_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Broadcast_Group_Id,
                Broadcast_Group_Name,
                Broadcast_Group_Short_Name,
                Broadcast_Group_15_Char_Name,
                Reporting_Start_Date,
                Reporting_End_Date)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
                CAST(substr(imported_text,3,5) AS Int) AS Broadcast_Group_Id,
                substr(imported_text,8,30) AS Broadcast_Group_Name,
                substr(imported_text,38,8) AS Broadcast_Group_Short_Name,
                substr(imported_text,46,15) AS Broadcast_Group_15_Char_Name,
                CAST(substr(imported_text,61,8) AS Date) AS Reporting_Start_Date,
                CAST(substr(imported_text,69,8) AS Date) AS Reporting_End_Date
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '11'

      INSERT INTO BARB_MASTER_FILE_AUDIENCE_CATEGORY_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
                Audience_Category_No,
                BARB_Audience_Category_Code,
                Audience_Description,
                Audience_Short_Description,
                Reporting_Start_Date,
                Reporting_End_Date,
                Audience_Category_1_Arithmetic_Operator,
                Audience_Category_2_Arithmetic_Operator,
                Audience_Category_3_Arithmetic_Operator,
                Audience_Category_4_Arithmetic_Operator,
                Audience_Category_5_Arithmetic_Operator,
                Audience_Category_6_Arithmetic_Operator,
                Audience_Category_7_Arithmetic_Operator,
                Audience_Category_8_Arithmetic_Operator,
                Audience_Category_9_Arithmetic_Operator,
                Audience_Category_10_Arithmetic_Operator,
                Audience_Category_11_Arithmetic_Operator,
                Audience_Category_12_Arithmetic_Operator,
                Audience_Category_13_Arithmetic_Operator,
                Audience_Category_14_Arithmetic_Operator,
                Audience_Category_15_Arithmetic_Operator,
                Audience_Category_16_Arithmetic_Operator,
                Audience_Category_17_Arithmetic_Operator,
                Audience_Category_18_Arithmetic_Operator,
                Audience_Category_19_Arithmetic_Operator,
                Audience_Category_20_Arithmetic_Operator,
                Audience_Category_21_Arithmetic_Operator,
                Audience_Category_22_Arithmetic_Operator,
                Audience_Category_23_Arithmetic_Operator,
                Audience_Category_24_Arithmetic_Operator,
                Audience_Category_25_Arithmetic_Operator,
                Audience_Category_26_Arithmetic_Operator,
                Audience_Category_27_Arithmetic_Operator,
                Audience_Category_28_Arithmetic_Operator,
                Audience_Category_29_Arithmetic_Operator,
                Audience_Category_30_Arithmetic_Operator,
                Audience_Category_31_Arithmetic_Operator,
                Audience_Category_32_Arithmetic_Operator,
                Audience_Category_33_Arithmetic_Operator,
                Audience_Category_34_Arithmetic_Operator,
                Audience_Category_35_Arithmetic_Operator,
                Audience_Category_36_Arithmetic_Operator,
                Audience_Category_37_Arithmetic_Operator,
                Audience_Category_38_Arithmetic_Operator,
                Audience_Category_39_Arithmetic_Operator,
                Audience_Category_40_Arithmetic_Operator,
                Audience_Category_41_Arithmetic_Operator,
                Audience_Category_42_Arithmetic_Operator,
                Audience_Category_43_Arithmetic_Operator,
                Audience_Category_44_Arithmetic_Operator,
                Audience_Category_45_Arithmetic_Operator,
                Audience_Category_46_Arithmetic_Operator,
                Audience_Category_47_Arithmetic_Operator,
                Audience_Category_48_Arithmetic_Operator,
                Audience_Category_49_Arithmetic_Operator,
                Audience_Category_50_Arithmetic_Operator,
                Audience_Category_51_Arithmetic_Operator,
                Audience_Category_52_Arithmetic_Operator,
                Audience_Category_53_Arithmetic_Operator,
                Audience_Category_54_Arithmetic_Operator,
                Audience_Category_55_Arithmetic_Operator,
                Audience_Category_56_Arithmetic_Operator,
                Audience_Category_57_Arithmetic_Operator,
                Audience_Category_58_Arithmetic_Operator,
                Audience_Category_59_Arithmetic_Operator,
                Audience_Category_60_Arithmetic_Operator,
                Audience_Category_61_Arithmetic_Operator,
                Audience_Category_62_Arithmetic_Operator,
                Audience_Category_63_Arithmetic_Operator,
                Audience_Category_64_Arithmetic_Operator,
                Audience_Category_65_Arithmetic_Operator,
                Audience_Category_66_Arithmetic_Operator,
                Audience_Category_67_Arithmetic_Operator,
                Audience_Category_68_Arithmetic_Operator,
                Audience_Category_69_Arithmetic_Operator,
                Audience_Category_70_Arithmetic_Operator,
                Audience_Category_71_Arithmetic_Operator)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
CAST(substr(imported_text,3,5) AS Int) AS Audience_Category_No,
CAST(substr(imported_text,8,6) AS Int) AS BARB_Audience_Category_Code,
substr(imported_text,14,30) AS Audience_Description,
substr(imported_text,44,15) AS Audience_Short_Description,
CAST(substr(imported_text,59,8) AS Date) AS Reporting_Start_Date,
CAST(substr(imported_text,67,8) AS Date) AS Reporting_End_Date,
substr(imported_text,75,1) AS Audience_Category_1_Arithmetic_Operator,
substr(imported_text,76,1) AS Audience_Category_2_Arithmetic_Operator,
substr(imported_text,77,1) AS Audience_Category_3_Arithmetic_Operator,
substr(imported_text,78,1) AS Audience_Category_4_Arithmetic_Operator,
substr(imported_text,79,1) AS Audience_Category_5_Arithmetic_Operator,
substr(imported_text,80,1) AS Audience_Category_6_Arithmetic_Operator,
substr(imported_text,81,1) AS Audience_Category_7_Arithmetic_Operator,
substr(imported_text,82,1) AS Audience_Category_8_Arithmetic_Operator,
substr(imported_text,83,1) AS Audience_Category_9_Arithmetic_Operator,
substr(imported_text,84,1) AS Audience_Category_10_Arithmetic_Operator,
substr(imported_text,85,1) AS Audience_Category_11_Arithmetic_Operator,
substr(imported_text,86,1) AS Audience_Category_12_Arithmetic_Operator,
substr(imported_text,87,1) AS Audience_Category_13_Arithmetic_Operator,
substr(imported_text,88,1) AS Audience_Category_14_Arithmetic_Operator,
substr(imported_text,89,1) AS Audience_Category_15_Arithmetic_Operator,
substr(imported_text,90,1) AS Audience_Category_16_Arithmetic_Operator,
substr(imported_text,91,1) AS Audience_Category_17_Arithmetic_Operator,
substr(imported_text,92,1) AS Audience_Category_18_Arithmetic_Operator,
substr(imported_text,93,1) AS Audience_Category_19_Arithmetic_Operator,
substr(imported_text,94,1) AS Audience_Category_20_Arithmetic_Operator,
substr(imported_text,95,1) AS Audience_Category_21_Arithmetic_Operator,
substr(imported_text,96,1) AS Audience_Category_22_Arithmetic_Operator,
substr(imported_text,97,1) AS Audience_Category_23_Arithmetic_Operator,
substr(imported_text,98,1) AS Audience_Category_24_Arithmetic_Operator,
substr(imported_text,99,1) AS Audience_Category_25_Arithmetic_Operator,
substr(imported_text,100,1) AS Audience_Category_26_Arithmetic_Operator,
substr(imported_text,101,1) AS Audience_Category_27_Arithmetic_Operator,
substr(imported_text,102,1) AS Audience_Category_28_Arithmetic_Operator,
substr(imported_text,103,1) AS Audience_Category_29_Arithmetic_Operator,
substr(imported_text,104,1) AS Audience_Category_30_Arithmetic_Operator,
substr(imported_text,105,1) AS Audience_Category_31_Arithmetic_Operator,
substr(imported_text,106,1) AS Audience_Category_32_Arithmetic_Operator,
substr(imported_text,107,1) AS Audience_Category_33_Arithmetic_Operator,
substr(imported_text,108,1) AS Audience_Category_34_Arithmetic_Operator,
substr(imported_text,109,1) AS Audience_Category_35_Arithmetic_Operator,
substr(imported_text,110,1) AS Audience_Category_36_Arithmetic_Operator,
substr(imported_text,111,1) AS Audience_Category_37_Arithmetic_Operator,
substr(imported_text,112,1) AS Audience_Category_38_Arithmetic_Operator,
substr(imported_text,113,1) AS Audience_Category_39_Arithmetic_Operator,
substr(imported_text,114,1) AS Audience_Category_40_Arithmetic_Operator,
substr(imported_text,115,1) AS Audience_Category_41_Arithmetic_Operator,
substr(imported_text,116,1) AS Audience_Category_42_Arithmetic_Operator,
substr(imported_text,117,1) AS Audience_Category_43_Arithmetic_Operator,
substr(imported_text,118,1) AS Audience_Category_44_Arithmetic_Operator,
substr(imported_text,119,1) AS Audience_Category_45_Arithmetic_Operator,
substr(imported_text,120,1) AS Audience_Category_46_Arithmetic_Operator,
substr(imported_text,121,1) AS Audience_Category_47_Arithmetic_Operator,
substr(imported_text,122,1) AS Audience_Category_48_Arithmetic_Operator,
substr(imported_text,123,1) AS Audience_Category_49_Arithmetic_Operator,
substr(imported_text,124,1) AS Audience_Category_50_Arithmetic_Operator,
substr(imported_text,125,1) AS Audience_Category_51_Arithmetic_Operator,
substr(imported_text,126,1) AS Audience_Category_52_Arithmetic_Operator,
substr(imported_text,127,1) AS Audience_Category_53_Arithmetic_Operator,
substr(imported_text,128,1) AS Audience_Category_54_Arithmetic_Operator,
substr(imported_text,129,1) AS Audience_Category_55_Arithmetic_Operator,
substr(imported_text,130,1) AS Audience_Category_56_Arithmetic_Operator,
substr(imported_text,131,1) AS Audience_Category_57_Arithmetic_Operator,
substr(imported_text,132,1) AS Audience_Category_58_Arithmetic_Operator,
substr(imported_text,133,1) AS Audience_Category_59_Arithmetic_Operator,
substr(imported_text,134,1) AS Audience_Category_60_Arithmetic_Operator,
substr(imported_text,135,1) AS Audience_Category_61_Arithmetic_Operator,
substr(imported_text,136,1) AS Audience_Category_62_Arithmetic_Operator,
substr(imported_text,137,1) AS Audience_Category_63_Arithmetic_Operator,
substr(imported_text,138,1) AS Audience_Category_64_Arithmetic_Operator,
substr(imported_text,139,1) AS Audience_Category_65_Arithmetic_Operator,
substr(imported_text,140,1) AS Audience_Category_66_Arithmetic_Operator,
substr(imported_text,141,1) AS Audience_Category_67_Arithmetic_Operator,
substr(imported_text,142,1) AS Audience_Category_68_Arithmetic_Operator,
substr(imported_text,143,1) AS Audience_Category_69_Arithmetic_Operator,
substr(imported_text,144,1) AS Audience_Category_70_Arithmetic_Operator,
substr(imported_text,145,1) AS Audience_Category_71_Arithmetic_Operator
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '12'

      INSERT INTO BARB_MASTER_FILE_COMMERCIAL_LENGTH_RATE_FACTORS_RECORD
                (file_creation_date,
                file_creation_time,
                file_type,
                file_version,
                filename,
Sales_House_Identifier,
Date_active_from,
Date_active_to,
Log_Station_Code,
Base_Duration_Length,
Commercial_Duration_1,
Factor_1,
Commercial_Duration_2,
Factor_2,
Commercial_Duration_3,
Factor_3,
Commercial_Duration_4,
Factor_4,
Commercial_Duration_5,
Factor_5,
Commercial_Duration_6,
Factor_6,
Commercial_Duration_7,
Factor_7,
Commercial_Duration_8,
Factor_8,
Commercial_Duration_9,
Factor_9,
Commercial_Duration_10,
Factor_10,
Commercial_Duration_11,
Factor_11,
Commercial_Duration_12,
Factor_12,
Commercial_Duration_13,
Factor_13,
Commercial_Duration_14,
Factor_14,
Commercial_Duration_15,
Factor_15,
Commercial_Duration_16,
Factor_16,
Commercial_Duration_17,
Factor_17,
Commercial_Duration_18,
Factor_18,
Commercial_Duration_19,
Factor_19,
Commercial_Duration_20,
Factor_20,
Commercial_Duration_21,
Factor_21,
Commercial_Duration_22,
Factor_22,
Commercial_Duration_23,
Factor_23,
Commercial_Duration_24,
Factor_24,
Commercial_Duration_25,
Factor_25,
Commercial_Duration_26,
Factor_26,
Commercial_Duration_27,
Factor_27,
Commercial_Duration_28,
Factor_28,
Commercial_Duration_29,
Factor_29,
Commercial_Duration_30,
Factor_30,
Commercial_Duration_31,
Factor_31,
Commercial_Duration_32,
Factor_32,
Commercial_Duration_33,
Factor_33,
Commercial_Duration_34,
Factor_34,
Commercial_Duration_35,
Factor_35,
Commercial_Duration_36,
Factor_36,
Commercial_Duration_37,
Factor_37,
Commercial_Duration_38,
Factor_38,
Commercial_Duration_39,
Factor_39,
Commercial_Duration_40,
Factor_40,
Commercial_Duration_41,
Factor_41,
Commercial_Duration_42,
Factor_42,
Commercial_Duration_43,
Factor_43,
Commercial_Duration_44,
Factor_44,
Commercial_Duration_45,
Factor_45,
Commercial_Duration_46,
Factor_46,
Commercial_Duration_47,
Factor_47,
Commercial_Duration_48,
Factor_48,
Commercial_Duration_49,
Factor_49,
Commercial_Duration_50,
Factor_50,
Commercial_Duration_51,
Factor_51,
Commercial_Duration_52,
Factor_52,
Commercial_Duration_53,
Factor_53,
Commercial_Duration_54,
Factor_54,
Commercial_Duration_55,
Factor_55,
Commercial_Duration_56,
Factor_56,
Commercial_Duration_57,
Factor_57,
Commercial_Duration_58,
Factor_58,
Commercial_Duration_59,
Factor_59,
Commercial_Duration_60,
Factor_60,
Commercial_Duration_61,
Factor_61,
Commercial_Duration_62,
Factor_62,
Commercial_Duration_63,
Factor_63,
Commercial_Duration_64,
Factor_64,
Commercial_Duration_65,
Factor_65,
Commercial_Duration_66,
Factor_66,
Commercial_Duration_67,
Factor_67,
Commercial_Duration_68,
Factor_68,
Commercial_Duration_69,
Factor_69,
Commercial_Duration_70,
Factor_70,
Commercial_Duration_71,
Factor_71,
Commercial_Duration_72,
Factor_72,
Commercial_Duration_73,
Factor_73,
Commercial_Duration_74,
Factor_74,
Commercial_Duration_75,
Factor_75,
Commercial_Duration_76,
Factor_76,
Commercial_Duration_77,
Factor_77,
Commercial_Duration_78,
Factor_78,
Commercial_Duration_79,
Factor_79,
Commercial_Duration_80,
Factor_80,
Commercial_Duration_81,
Factor_81,
Commercial_Duration_82,
Factor_82,
Commercial_Duration_83,
Factor_83,
Commercial_Duration_84,
Factor_84,
Commercial_Duration_85,
Factor_85,
Commercial_Duration_86,
Factor_86,
Commercial_Duration_87,
Factor_87,
Commercial_Duration_88,
Factor_88,
Commercial_Duration_89,
Factor_89,
Commercial_Duration_90,
Factor_90
)
        SELECT
                @file_creation_date,
                @file_creation_time,
                @file_type,
                @file_version,
                @filename,
CAST(substr(imported_text,3,5) AS Int) AS Sales_House_Identifier,
CAST(substr(imported_text,8,8) AS Date) AS Date_active_from,
CAST(substr(imported_text,16,8) AS Date) AS Date_active_to,
CAST(substr(imported_text,24,5) AS Int) AS Log_Station_Code,
CAST(substr(imported_text,29,5) AS Int) AS Base_Duration_Length,
CAST(substr(imported_text,34,5) AS Int) AS Commercial_Duration_1,
CAST(substr(imported_text,39,7) AS Decimal(7,3)) AS Factor_1,
CAST(substr(imported_text,46,5) AS Int) AS Commercial_Duration_2,
CAST(substr(imported_text,51,7) AS Decimal(7,3)) AS Factor_2,
CAST(substr(imported_text,58,5) AS Int) AS Commercial_Duration_3,
CAST(substr(imported_text,63,7) AS Decimal(7,3)) AS Factor_3,
CAST(substr(imported_text,70,5) AS Int) AS Commercial_Duration_4,
CAST(substr(imported_text,75,7) AS Decimal(7,3)) AS Factor_4,
CAST(substr(imported_text,82,5) AS Int) AS Commercial_Duration_5,
CAST(substr(imported_text,87,7) AS Decimal(7,3)) AS Factor_5,
CAST(substr(imported_text,94,5) AS Int) AS Commercial_Duration_6,
CAST(substr(imported_text,99,7) AS Decimal(7,3)) AS Factor_6,
CAST(substr(imported_text,106,5) AS Int) AS Commercial_Duration_7,
CAST(substr(imported_text,111,7) AS Decimal(7,3)) AS Factor_7,
CAST(substr(imported_text,118,5) AS Int) AS Commercial_Duration_8,
CAST(substr(imported_text,123,7) AS Decimal(7,3)) AS Factor_8,
CAST(substr(imported_text,130,5) AS Int) AS Commercial_Duration_9,
CAST(substr(imported_text,135,7) AS Decimal(7,3)) AS Factor_9,
CAST(substr(imported_text,142,5) AS Int) AS Commercial_Duration_10,
CAST(substr(imported_text,147,7) AS Decimal(7,3)) AS Factor_10,
CAST(substr(imported_text,154,5) AS Int) AS Commercial_Duration_11,
CAST(substr(imported_text,159,7) AS Decimal(7,3)) AS Factor_11,
CAST(substr(imported_text,166,5) AS Int) AS Commercial_Duration_12,
CAST(substr(imported_text,171,7) AS Decimal(7,3)) AS Factor_12,
CAST(substr(imported_text,178,5) AS Int) AS Commercial_Duration_13,
CAST(substr(imported_text,183,7) AS Decimal(7,3)) AS Factor_13,
CAST(substr(imported_text,190,5) AS Int) AS Commercial_Duration_14,
CAST(substr(imported_text,195,7) AS Decimal(7,3)) AS Factor_14,
CAST(substr(imported_text,202,5) AS Int) AS Commercial_Duration_15,
CAST(substr(imported_text,207,7) AS Decimal(7,3)) AS Factor_15,
CAST(substr(imported_text,214,5) AS Int) AS Commercial_Duration_16,
CAST(substr(imported_text,219,7) AS Decimal(7,3)) AS Factor_16,
CAST(substr(imported_text,226,5) AS Int) AS Commercial_Duration_17,
CAST(substr(imported_text,231,7) AS Decimal(7,3)) AS Factor_17,
CAST(substr(imported_text,238,5) AS Int) AS Commercial_Duration_18,
CAST(substr(imported_text,243,7) AS Decimal(7,3)) AS Factor_18,
CAST(substr(imported_text,250,5) AS Int) AS Commercial_Duration_19,
CAST(substr(imported_text,255,7) AS Decimal(7,3)) AS Factor_19,
CAST(substr(imported_text,262,5) AS Int) AS Commercial_Duration_20,
CAST(substr(imported_text,267,7) AS Decimal(7,3)) AS Factor_20,
CAST(substr(imported_text,274,5) AS Int) AS Commercial_Duration_21,
CAST(substr(imported_text,279,7) AS Decimal(7,3)) AS Factor_21,
CAST(substr(imported_text,286,5) AS Int) AS Commercial_Duration_22,
CAST(substr(imported_text,291,7) AS Decimal(7,3)) AS Factor_22,
CAST(substr(imported_text,298,5) AS Int) AS Commercial_Duration_23,
CAST(substr(imported_text,303,7) AS Decimal(7,3)) AS Factor_23,
CAST(substr(imported_text,310,5) AS Int) AS Commercial_Duration_24,
CAST(substr(imported_text,315,7) AS Decimal(7,3)) AS Factor_24,
CAST(substr(imported_text,322,5) AS Int) AS Commercial_Duration_25,
CAST(substr(imported_text,327,7) AS Decimal(7,3)) AS Factor_25,
CAST(substr(imported_text,334,5) AS Int) AS Commercial_Duration_26,
CAST(substr(imported_text,339,7) AS Decimal(7,3)) AS Factor_26,
CAST(substr(imported_text,346,5) AS Int) AS Commercial_Duration_27,
CAST(substr(imported_text,351,7) AS Decimal(7,3)) AS Factor_27,
CAST(substr(imported_text,358,5) AS Int) AS Commercial_Duration_28,
CAST(substr(imported_text,363,7) AS Decimal(7,3)) AS Factor_28,
CAST(substr(imported_text,370,5) AS Int) AS Commercial_Duration_29,
CAST(substr(imported_text,375,7) AS Decimal(7,3)) AS Factor_29,
CAST(substr(imported_text,382,5) AS Int) AS Commercial_Duration_30,
CAST(substr(imported_text,387,7) AS Decimal(7,3)) AS Factor_30,
CAST(substr(imported_text,394,5) AS Int) AS Commercial_Duration_31,
CAST(substr(imported_text,399,7) AS Decimal(7,3)) AS Factor_31,
CAST(substr(imported_text,406,5) AS Int) AS Commercial_Duration_32,
CAST(substr(imported_text,411,7) AS Decimal(7,3)) AS Factor_32,
CAST(substr(imported_text,418,5) AS Int) AS Commercial_Duration_33,
CAST(substr(imported_text,423,7) AS Decimal(7,3)) AS Factor_33,
CAST(substr(imported_text,430,5) AS Int) AS Commercial_Duration_34,
CAST(substr(imported_text,435,7) AS Decimal(7,3)) AS Factor_34,
CAST(substr(imported_text,442,5) AS Int) AS Commercial_Duration_35,
CAST(substr(imported_text,447,7) AS Decimal(7,3)) AS Factor_35,
CAST(substr(imported_text,454,5) AS Int) AS Commercial_Duration_36,
CAST(substr(imported_text,459,7) AS Decimal(7,3)) AS Factor_36,
CAST(substr(imported_text,466,5) AS Int) AS Commercial_Duration_37,
CAST(substr(imported_text,471,7) AS Decimal(7,3)) AS Factor_37,
CAST(substr(imported_text,478,5) AS Int) AS Commercial_Duration_38,
CAST(substr(imported_text,483,7) AS Decimal(7,3)) AS Factor_38,
CAST(substr(imported_text,490,5) AS Int) AS Commercial_Duration_39,
CAST(substr(imported_text,495,7) AS Decimal(7,3)) AS Factor_39,
CAST(substr(imported_text,502,5) AS Int) AS Commercial_Duration_40,
CAST(substr(imported_text,507,7) AS Decimal(7,3)) AS Factor_40,
CAST(substr(imported_text,514,5) AS Int) AS Commercial_Duration_41,
CAST(substr(imported_text,519,7) AS Decimal(7,3)) AS Factor_41,
CAST(substr(imported_text,526,5) AS Int) AS Commercial_Duration_42,
CAST(substr(imported_text,531,7) AS Decimal(7,3)) AS Factor_42,
CAST(substr(imported_text,538,5) AS Int) AS Commercial_Duration_43,
CAST(substr(imported_text,543,7) AS Decimal(7,3)) AS Factor_43,
CAST(substr(imported_text,550,5) AS Int) AS Commercial_Duration_44,
CAST(substr(imported_text,555,7) AS Decimal(7,3)) AS Factor_44,
CAST(substr(imported_text,562,5) AS Int) AS Commercial_Duration_45,
CAST(substr(imported_text,567,7) AS Decimal(7,3)) AS Factor_45,
CAST(substr(imported_text,574,5) AS Int) AS Commercial_Duration_46,
CAST(substr(imported_text,579,7) AS Decimal(7,3)) AS Factor_46,
CAST(substr(imported_text,586,5) AS Int) AS Commercial_Duration_47,
CAST(substr(imported_text,591,7) AS Decimal(7,3)) AS Factor_47,
CAST(substr(imported_text,598,5) AS Int) AS Commercial_Duration_48,
CAST(substr(imported_text,603,7) AS Decimal(7,3)) AS Factor_48,
CAST(substr(imported_text,610,5) AS Int) AS Commercial_Duration_49,
CAST(substr(imported_text,615,7) AS Decimal(7,3)) AS Factor_49,
CAST(substr(imported_text,622,5) AS Int) AS Commercial_Duration_50,
CAST(substr(imported_text,627,7) AS Decimal(7,3)) AS Factor_50,
CAST(substr(imported_text,634,5) AS Int) AS Commercial_Duration_51,
CAST(substr(imported_text,639,7) AS Decimal(7,3)) AS Factor_51,
CAST(substr(imported_text,646,5) AS Int) AS Commercial_Duration_52,
CAST(substr(imported_text,651,7) AS Decimal(7,3)) AS Factor_52,
CAST(substr(imported_text,658,5) AS Int) AS Commercial_Duration_53,
CAST(substr(imported_text,663,7) AS Decimal(7,3)) AS Factor_53,
CAST(substr(imported_text,670,5) AS Int) AS Commercial_Duration_54,
CAST(substr(imported_text,675,7) AS Decimal(7,3)) AS Factor_54,
CAST(substr(imported_text,682,5) AS Int) AS Commercial_Duration_55,
CAST(substr(imported_text,687,7) AS Decimal(7,3)) AS Factor_55,
CAST(substr(imported_text,694,5) AS Int) AS Commercial_Duration_56,
CAST(substr(imported_text,699,7) AS Decimal(7,3)) AS Factor_56,
CAST(substr(imported_text,706,5) AS Int) AS Commercial_Duration_57,
CAST(substr(imported_text,711,7) AS Decimal(7,3)) AS Factor_57,
CAST(substr(imported_text,718,5) AS Int) AS Commercial_Duration_58,
CAST(substr(imported_text,723,7) AS Decimal(7,3)) AS Factor_58,
CAST(substr(imported_text,730,5) AS Int) AS Commercial_Duration_59,
CAST(substr(imported_text,735,7) AS Decimal(7,3)) AS Factor_59,
CAST(substr(imported_text,742,5) AS Int) AS Commercial_Duration_60,
CAST(substr(imported_text,747,7) AS Decimal(7,3)) AS Factor_60,
CAST(substr(imported_text,754,5) AS Int) AS Commercial_Duration_61,
CAST(substr(imported_text,759,7) AS Decimal(7,3)) AS Factor_61,
CAST(substr(imported_text,766,5) AS Int) AS Commercial_Duration_62,
CAST(substr(imported_text,771,7) AS Decimal(7,3)) AS Factor_62,
CAST(substr(imported_text,778,5) AS Int) AS Commercial_Duration_63,
CAST(substr(imported_text,783,7) AS Decimal(7,3)) AS Factor_63,
CAST(substr(imported_text,790,5) AS Int) AS Commercial_Duration_64,
CAST(substr(imported_text,795,7) AS Decimal(7,3)) AS Factor_64,
CAST(substr(imported_text,802,5) AS Int) AS Commercial_Duration_65,
CAST(substr(imported_text,807,7) AS Decimal(7,3)) AS Factor_65,
CAST(substr(imported_text,814,5) AS Int) AS Commercial_Duration_66,
CAST(substr(imported_text,819,7) AS Decimal(7,3)) AS Factor_66,
CAST(substr(imported_text,826,5) AS Int) AS Commercial_Duration_67,
CAST(substr(imported_text,831,7) AS Decimal(7,3)) AS Factor_67,
CAST(substr(imported_text,838,5) AS Int) AS Commercial_Duration_68,
CAST(substr(imported_text,843,7) AS Decimal(7,3)) AS Factor_68,
CAST(substr(imported_text,850,5) AS Int) AS Commercial_Duration_69,
CAST(substr(imported_text,855,7) AS Decimal(7,3)) AS Factor_69,
CAST(substr(imported_text,862,5) AS Int) AS Commercial_Duration_70,
CAST(substr(imported_text,867,7) AS Decimal(7,3)) AS Factor_70,
CAST(substr(imported_text,874,5) AS Int) AS Commercial_Duration_71,
CAST(substr(imported_text,879,7) AS Decimal(7,3)) AS Factor_71,
CAST(substr(imported_text,886,5) AS Int) AS Commercial_Duration_72,
CAST(substr(imported_text,891,7) AS Decimal(7,3)) AS Factor_72,
CAST(substr(imported_text,898,5) AS Int) AS Commercial_Duration_73,
CAST(substr(imported_text,903,7) AS Decimal(7,3)) AS Factor_73,
CAST(substr(imported_text,910,5) AS Int) AS Commercial_Duration_74,
CAST(substr(imported_text,915,7) AS Decimal(7,3)) AS Factor_74,
CAST(substr(imported_text,922,5) AS Int) AS Commercial_Duration_75,
CAST(substr(imported_text,927,7) AS Decimal(7,3)) AS Factor_75,
CAST(substr(imported_text,934,5) AS Int) AS Commercial_Duration_76,
CAST(substr(imported_text,939,7) AS Decimal(7,3)) AS Factor_76,
CAST(substr(imported_text,946,5) AS Int) AS Commercial_Duration_77,
CAST(substr(imported_text,951,7) AS Decimal(7,3)) AS Factor_77,
CAST(substr(imported_text,958,5) AS Int) AS Commercial_Duration_78,
CAST(substr(imported_text,963,7) AS Decimal(7,3)) AS Factor_78,
CAST(substr(imported_text,970,5) AS Int) AS Commercial_Duration_79,
CAST(substr(imported_text,975,7) AS Decimal(7,3)) AS Factor_79,
CAST(substr(imported_text,982,5) AS Int) AS Commercial_Duration_80,
CAST(substr(imported_text,987,7) AS Decimal(7,3)) AS Factor_80,
CAST(substr(imported_text,994,5) AS Int) AS Commercial_Duration_81,
CAST(substr(imported_text,999,7) AS Decimal(7,3)) AS Factor_81,
CAST(substr(imported_text,1006,5) AS Int) AS Commercial_Duration_82,
CAST(substr(imported_text,1011,7) AS Decimal(7,3)) AS Factor_82,
CAST(substr(imported_text,1018,5) AS Int) AS Commercial_Duration_83,
CAST(substr(imported_text,1023,7) AS Decimal(7,3)) AS Factor_83,
CAST(substr(imported_text,1030,5) AS Int) AS Commercial_Duration_84,
CAST(substr(imported_text,1035,7) AS Decimal(7,3)) AS Factor_84,
CAST(substr(imported_text,1042,5) AS Int) AS Commercial_Duration_85,
CAST(substr(imported_text,1047,7) AS Decimal(7,3)) AS Factor_85,
CAST(substr(imported_text,1054,5) AS Int) AS Commercial_Duration_86,
CAST(substr(imported_text,1059,7) AS Decimal(7,3)) AS Factor_86,
CAST(substr(imported_text,1066,5) AS Int) AS Commercial_Duration_87,
CAST(substr(imported_text,1071,7) AS Decimal(7,3)) AS Factor_87,
CAST(substr(imported_text,1078,5) AS Int) AS Commercial_Duration_88,
CAST(substr(imported_text,1083,7) AS Decimal(7,3)) AS Factor_88,
CAST(substr(imported_text,1090,5) AS Int) AS Commercial_Duration_89,
CAST(substr(imported_text,1095,7) AS Decimal(7,3)) AS Factor_89,
CAST(substr(imported_text,1102,5) AS Int) AS Commercial_Duration_90,
CAST(substr(imported_text,1107,7) AS Decimal(7,3)) AS Factor_90
        FROM MN_BARB_import
        WHERE substr(imported_text,1,2) = '13'



END
