

--- Pre-capped slots
SELECT DTH_VIEWING_EVENT_ID, SCMS_SUBSCRIBER_ID, EVENT_START_DATETIME, EVENT_END_DATETIME, EVENT_ACTION
FROM DIS_REFERENCE..FINAL_DTH_VIEWING_EVENT_HISTORY 
WHERE EVENT_ACTION IN ('AdSmart Substitution', 'AdSmart No Substitution') 
AND PANEL_ID_REPORTED IN (11,12)
AND TX_DAY<4 
AND date(EVENT_START_DATETIME) = '2014-04-14' 
AND DTH_VIEWING_EVENT_DATA_SOURCE='AMS Viewing Event'
AND LIVE_EVENT_FLAG = 1




